### ISSUE TITLE
Problem with Thai language 

### ISSUE THREAD

**Issue by Syllapin** [monkeytypegame/monkeytype#1820]
Have problem with some letter that have 3 stack like แต่งตั้ง , ต่อไปนี้   
Wording of ตั้ง & นี้ show not correct (stack)
please see example in below picture
change font can't solve this problem
![image](https://user-images.githubusercontent.com/90237219/132289942-541fc1ec-f754-4de1-a987-4ea77f27fb66.png)
![image](https://user-images.githubusercontent.com/90237219/132289979-2760732a-7885-457e-8588-e6f04213a3ec.png)

**Comment by Miodec** [comment]
This is because of the way the website splits words into separate letter elements. It ends up splitting the accents into separate elements and they are not displayed correctly. Im afraid fixing this would require a *lot* of changes.
![image](https://user-images.githubusercontent.com/13181393/132690107-88c110bb-c3c0-4983-b848-8a220905ba89.png)

**Comment by niawjunior** [comment]
The Thai Language look good to me

I guess it depends on font-family in your setttings.

![image](https://user-images.githubusercontent.com/17493195/138035156-11c77d71-7980-44de-b50a-3986aae35841.png)

**Comment by Syllapin** [comment]
> Still an issue? Have you tested all fonts available on the website?
> 
> @niawjunior what browser and font are you using?

Still have same problem even change all fonts on the web , test in chrome & edge.

Note : In manoontype.web.app which forked from monkeytype , I tested in manoontype and everything fine. Don't know why.

**Comment by Miodec** [comment]
Hey @narze i see you forked monkeytype! Would you mind helping me with this issue? Did you change anything about the character rendering in your fork? Any css properties or specific fonts?

**Comment by Miodec** [comment]
I just tested this again and it seems like the characters are stacking correctly? 
![image](https://user-images.githubusercontent.com/13181393/154842768-253d4105-0d92-4230-b93a-c77e909d0b09.png)
@Syllapin can you check?

**Comment by Syllapin** [comment]
> I just tested this again and it seems like the characters are stacking correctly? ![image](https://user-images.githubusercontent.com/13181393/154842768-253d4105-0d92-4230-b93a-c77e909d0b09.png) @Syllapin can you check?

Hmm Still occur, Then I think may be some setting on my windows setting.  You can close this topic  & thank for your help.

**Comment by Miodec** [comment]
What browser are you using?

**Comment by Syllapin** [comment]
I tried Microsoft Edge, Google chrome , Firefox.  Then I think may be  font/language setting, or region setting on windows.

**Comment by Miodec** [comment]
The for you linked before uses a font called `Boon`. Maybe you could try to install it and use it as a custom font on monkeytype?

**Comment by narze** [comment]
> Hey @narze i see you forked monkeytype! Would you mind helping me with this issue? Did you change anything about the character rendering in your fork? Any css properties or specific fonts?

I'm so sorry I didn't see the notification that you mentioned me months ago
My fork does use Boon font and it works perfectly

![image](https://user-images.githubusercontent.com/248741/154853821-fc47f382-a13e-447d-80c4-2167d3795fb5.png)
Also I confirm that this is correct

**Comment by Syllapin** [comment]
![image](https://user-images.githubusercontent.com/90237219/154892717-70caadf4-c9c2-4a2b-8cc6-8e8c2659687f.png)
![image](https://user-images.githubusercontent.com/90237219/154892761-21baf1b1-3ab1-4bc4-a344-2523a8a18353.png)

already test on Edge

**Comment by Miodec** [comment]
> ![image](https://user-images.githubusercontent.com/90237219/154892717-70caadf4-c9c2-4a2b-8cc6-8e8c2659687f.png) ![image](https://user-images.githubusercontent.com/90237219/154892761-21baf1b1-3ab1-4bc4-a344-2523a8a18353.png) ![image](https://user-images.githubusercontent.com/90237219/154893131-71ac4478-ecb7-41c4-9e1c-b4ae44e5d31b.png)
> 
> already test on Edge

So... Both on Edge, both using the same font and Monkeytype is still wrong?

**Comment by Syllapin** [comment]
> > ![image](https://user-images.githubusercontent.com/90237219/154892717-70caadf4-c9c2-4a2b-8cc6-8e8c2659687f.png) ![image](https://user-images.githubusercontent.com/90237219/154892761-21baf1b1-3ab1-4bc4-a344-2523a8a18353.png) ![image](https://user-images.githubusercontent.com/90237219/154893131-71ac4478-ecb7-41c4-9e1c-b4ae44e5d31b.png)
> > already test on Edge
> 
> So... Both on Edge, both using the same font and Monkeytype is still wrong?

Yep, Edge, Firefox, Chrome Still wrong. May be some setting on my windows language/regional setting.

**Comment by Miodec** [comment]
> May be some setting on my windows language/regional setting.

If that was the case then manoontype would also be wrong. 

@narze did you only change the font and nothing else in the css?

**Comment by Miodec** [comment]
Ive added the Boon font. Let me know if it fixes this issue.

**Comment by Syllapin** [comment]
![image](https://user-images.githubusercontent.com/90237219/172853738-5aa4e7a9-c7ed-4692-9f0e-d74fb97691fa.png)
Solve! Thank you.  XD
