### ISSUE TITLE
Screenshot is not taken wide enough

### ISSUE THREAD

**Issue by oof2win2** [monkeytypegame/monkeytype#2054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

The screenshot button takes a screenshot that is not of the correct width, which removes a part of the content on the right and looks bad.

![image](https://user-images.githubusercontent.com/23482862/139862411-7447aaaa-70d0-437e-91bc-3b53a8e60f97.png)

### Expected Behavior

I would expect the screenshot to be of the correct width and capture all of the content.

### Steps To Reproduce

1. Complete a test
2. Attempt to create a screenshot
3. Paste the screenshot somewhere to observe it

### Environment

- OS: MacOS 11.4
- Browser: Chrome
- Browser Version: Version 95.0.4638.54 (Official Build) (x86_64)

### Did you check incognito mode?

- [ ] I have checked incognito mode

**Comment by Miodec** [comment]
I can't seem to reproduce. Does it happen on every test?

**Comment by oof2win2** [comment]
Yes, it seems to be so. Even on incognito mode, 15s: https://imgur.com/a/XTmFvdu

**Comment by Miodec** [comment]
Is your zoom level at 100%? Did you change your browser font size settings?

**Comment by oof2win2** [comment]
I did not change my font size and my zoom level is at 100%.

**Comment by Miodec** [comment]
Please paste in your config then, because i cant reproduce this.

**Comment by oof2win2** [comment]
I assume that you requested the MonkeyType config.
```
{"theme":"80s_after_dark","customTheme":true,"customThemeColors":["#1b1d36","#fca6d1","#99d6ea","#99d6ea","#fca6d1","#fffb85","#fffb85","#fffb85","#fffb85"],"favThemes":["80s_after_dark"],"showKeyTips":false,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickTab":false,"punctuation":false,"numbers":false,"words":25,"time":60,"mode":"words","quoteLength":[0],"language":"english","fontSize":15,"freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":false,"timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"text","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","playSoundOnError":false,"playSoundOnClick":"off","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"custom","paceCaretCustomSpeed":"65","repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":"65","highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false}
```

**Comment by brneor** [comment]
Can confirm that happens with my settings too.

**Comment by Miodec** [comment]
Could you guys get a screen recording of this? This has to be something super specific.

**Comment by oof2win2** [comment]
https://user-images.githubusercontent.com/23482862/146941968-c38a727d-4b58-4a5c-8512-3a28bac3940d.mov

![image](https://user-images.githubusercontent.com/23482862/146941989-eb419069-3bdf-43c4-a400-20d7f207461c.png)

Above is the screen recording and the resultant image.

**Comment by CameronCT** [comment]
Just something I noticed, in the video provided above it shows a scroll bar on the right side. Could this simply be offsetting the results screen?

**Comment by Miodec** [comment]
Scrollbar wouldnt cause that much to be cut off.

Also just did a test and the screenshot was fine with the scrollbar (at least for me)

**Comment by bragefuglseth** [comment]
Hey, I managed to reproduce this in Firefox. It happens on seemingly random occasions. The image size is always the same, with only the content stretching outside of it on the X axis. After some research, I believe it's caused by a bug html2canvas. I have managed to code up a temporary workaround which just consists of increasing the padding. It patches the bug in most cases, without making the screenshot look weird for those that are not experiencing the bug.

**Comment by Miodec** [comment]
Reopening since im not 100% sure the PR is a definite fix.

Deployed a new version, clear cache and test again.

**Comment by oof2win2** [comment]
It works on dev for me. I assume prod not yet, since it's not a definite one?

**Comment by Miodec** [comment]
It is live already

**Comment by oof2win2** [comment]
Works for me (bad score so meh)!

![image](https://user-images.githubusercontent.com/23482862/149223026-e9d0cc6d-0d0c-4eff-bc54-05c1c3d0f38c.png)

**Comment by Nugget1308** [comment]
![image](https://user-images.githubusercontent.com/97735564/150359522-e41d71b4-0865-49fe-b055-3b63d5fde5a6.png)

**Comment by Ferotiq** [comment]
Is anybody still experiencing this issue with the fix?
