### ISSUE TITLE
Split contributing.md into basic and advanced

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#2629]
Basic guide should go over basic contributing without setting up a local server. (working just in github). This will be good for absolute noobies who want to add languages or quotes. (Maybe include a link to a good youtube guide on git/github basics)

Advanced will go through the full process (what we have now)

**Comment by UnrealApex** [comment]
I could work on partially this.

**Comment by UnrealApex** [comment]
@Miodec / @Bruception maybe assign me to the issue?

**Comment by UnrealApex** [comment]
Thanks, wow that was quick!

**Comment by Miodec** [comment]
@UnrealApex any progress?

**Comment by UnrealApex** [comment]
Sorry for the delay, been kinda busy lately with school and forgot that I was even assigned to this issue. I'll get cracking on it this weekend.

**Comment by sambhavsaxena** [comment]
I would like to work on this issue if its available?

**Comment by Miodec** [comment]
@UnrealApex if you're busy would you like to pass this issue to @sambhavsaxena ?

**Comment by UnrealApex** [comment]
Sure thing, if I have time, I can review the changes.

**Comment by Miodec** [comment]
@sambhavsaxena any updates?

**Comment by Matthew-Kwan** [comment]
Is the outcome of this ticket a single `CONTRIBUTING.MD` that has a basic and advanced section, or two separate `.md` files for each? 

Also, for the basic guide, would it simply be a guide that shows how to edit files in the github web ui?

**Comment by Miodec** [comment]
> Is the outcome of this ticket a single `CONTRIBUTING.MD` that has a basic and advanced section, or two separate `.md` files for each?

I was thinking contributing.md would a small file with some basic information and then it links to the basic or advanced file. 

> Also, for the basic guide, would it simply be a guide that shows how to edit files in the github web ui and be able to contribute exclusively through that web UI?

Yeap.

**Comment by Miodec** [comment]
@sambhavsaxena unassigning due to inactivity

**Comment by Matthew-Kwan** [comment]
@Miodec I can write up a draft for this. Can you assign this to me?
