### ISSUE TITLE
Webpack Not Working on Windows

### ISSUE THREAD

**Issue by Ferotiq** [monkeytypegame/monkeytype#2867]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Ferotiq

### Current Behavior

"Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems."

### Steps To Reproduce

1. Clone the repo on windows
2. Go through the necessary requirements to get it running
3. `npm run dev`

### Environment

- OS: Windows 11

**Comment by Miodec** [comment]
@CameronCT could you verify this is an issue, please?

**Comment by Miodec** [comment]
Renaming index.html to main.thml seems to have fixed this
