### ISSUE TITLE
fix accuracy calculation when not inserting characters

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#2967]
using alt codes or hex input on Linux decreases the accuracy for each keypress. It should be modified to only alter accuracy if the input actually changes

Windows: unknown
Mac: Does not happen
Linux: Does happen

**Comment by Dang3r0us** [comment]
Windows: Does not happen

**Comment by TheJazzDev** [comment]
@Dang3r0us Has this issue been fixed if i may ask?

**Comment by Dang3r0us** [comment]
Its still open so I guess not ¯\_(ツ)_/¯

**Comment by TheJazzDev** [comment]
Alright, thanks mate.

**Comment by Miodec** [comment]
Retested, some change since then and now mustve fixed it.
