### ISSUE TITLE
Wrong width of the caret

### ISSUE THREAD

**Issue by enheit** [monkeytypegame/monkeytype#2973]
### Current Behavior

The caret width is wider than underlying character

### Expected Behavior

The caret width must be the same as the width of underlying character.

### Steps To Reproduce

1. Default settings are set
2. Open settings
3. Change the caret style to the "filled rectangle"
4. Close settings
5. Verify that caret is wider than underlying character

### Environment

- OS: macOS 12.1
- Browser: Chrome
- Browser Version: Version 101.0.4951.54 (Official Build) (arm64)

### Anything else?

<img width="233" alt="Screenshot 2022-05-13 at 03 42 09" src="https://user-images.githubusercontent.com/8645216/168189333-8255a7df-ce4f-453b-85ef-56575541a5d0.png">

**Comment by Miodec** [comment]
Fixed and deployed
