### ISSUE TITLE
accuracy lower than 100% although no incorrect keys were pressed

### ISSUE THREAD

**Issue by Akanksh12** [monkeytypegame/monkeytype#2976]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

Akanksh

### Account config

{"theme":"catppuccin","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#000","#eee","#eee","#444","#000000","#eee","#fff","#ffffff","#fff","#ffffff"],"favThemes":["matrix","mint"],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickTab":true,"punctuation":false,"numbers":false,"words":10,"time":15,"mode":"time","quoteLength":[1],"language":"english","fontSize":"4","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":true,"layout":"qwerty","funbox":"none","confidenceMode":"off","indicateTypos":"below","timerStyle":"bar","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"react","keymapStyle":"matrix","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","fontFamily":"Source_Code_Pro","smoothLineScroll":true,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":false,"swapEscAndTab":false,"showOutOfFocusWarning":false,"paceCaret":"off","paceCaretCustomSpeed":120,"repeatedPace":true,"pageWidth":"max","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"max","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":true,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

the accuracy is not right. This happens when I make a new pr, happened on 30 seconds and now 15 seconds

### Expected Behavior

the accuracy shown should be 100%

### Steps To Reproduce

have a 100% accuracy pr and break that pr but maintain the 100% accuracy

### Environment

- OS: Windows 10
- Browser: Chrome
- Browser Version: 101.0.4951.54

### Anything else?

![monkebug](https://user-images.githubusercontent.com/55909985/168294624-ac5bb9b2-3c44-4fb5-8f94-8424e4ab3dcd.JPG)
![monkeybug2](https://user-images.githubusercontent.com/55909985/168294797-bd22d0c3-ca58-4916-bbf2-63a6b4dc2a77.jpeg)

**Comment by Miodec** [comment]
I can see errors on the graph.

Did you press the wrong keys but then corrected them?

**Comment by Akanksh12** [comment]
oops, the 130 wpm pic  doesn't have the issue but the 142 wpm one has

**Comment by Miodec** [comment]
> Did you press the wrong keys but then corrected them?

**Comment by Akanksh12** [comment]
no I didn't make a single mistake

**Comment by Miodec** [comment]
![image](https://user-images.githubusercontent.com/13181393/168338313-6d519410-662e-4003-88cd-0f0545d86a63.png)

Theres an error right there

**Comment by Akanksh12** [comment]
I remember this now, it's a minor hardware issue. this happens on the keyboard it sometimes gives random outputs.
