### ISSUE TITLE
error - test stopped due to bad performance after every test

### ISSUE THREAD

**Issue by suryanshmak** [monkeytypegame/monkeytype#2977]
### Did you clear cache before opening an issue?

- [x] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time I submit a test, i get the same error: 

![](https://i.ibb.co/QJz1Rkt/Screenshot-2022-05-14-at-1-09-06-PM.png)

### Environment

- OS: macOS 
- Browser: Microsoft Edge
- Browser Version: Version 101.0.1210.39 (Official build) (arm64)

**Comment by Miodec** [comment]
Go into Edge settings and disable high efficiency mode. It will fix it.

**Comment by suryanshmak** [comment]
upon some research, I do see what the efficiency mode does. there was also a time where I could see the popup which mentions disable efficiency mode but just for some milliseconds. would be better if you could increase the duration.
