### ISSUE TITLE
Arrows not showing

### ISSUE THREAD

**Issue by TheHackerCoding** [monkeytypegame/monkeytype#2986]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

0x0

### Account config

{"theme":"stealth","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["arch","dark","superuser","nord","vscode","mountain","fire","aurora","matrix","stealth","shadow","gruvbox_dark","dev","terminal","midnight"],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickTab":true,"punctuation":false,"numbers":false,"words":10,"time":15,"mode":"time","quoteLength":[3],"language":"english","fontSize":"2","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":true,"layout":"default","funbox":"arrows","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"matrix","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","fontFamily":"JetBrains_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"4","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"average","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":true,"showLiveBurst":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"https://c.tenor.com/x15S5rhHVscAAAAC/anime-purple.gif","customBackgroundSize":"cover","customBackgroundFilter":[0.1,0.5,0,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"letter"}

### Current Behavior

I have tape mone on letters and arrows on and for some reason when I have these both on the arrows don't actually scroll meaning I can't see the rest of the arrows after I finish the ones on-screen

### Expected Behavior

The arrows to scroll from left to right so I can see them

### Steps To Reproduce

1. Turn on `funbox` -> `arrows` & `tape mode` -> `letters`
2. Go back home and start typing how you would normally

### Environment

- OS: Linux (Ubuntu 20.04.4 LTS x86_64) (Kubuntu)
- Browser: Brave
- Browser Version: Version 1.38.115 Chromium: 101.0.4951.64 (Official Build) (64-bit)
 
(p.s. issue also occurs on a chromebook)

### Anything else?

![Screenshot_20220516_162416](https://user-images.githubusercontent.com/29006605/168677904-cc454349-5f2a-4453-8c7b-8e632a87c708.png)

**Comment by Miodec** [comment]
It works if you use WASD but doesn't work if you use arrow keys. Fixing.

**Comment by TheHackerCoding** [comment]
oh wow that was quick thanks
