### ISSUE TITLE
Public API is not working for me

### ISSUE THREAD

**Issue by ThangaAyyanar** [monkeytypegame/monkeytype#3032]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

starseven

### Account config

{
  "theme": "nord",
  "themeLight": "serika",
  "themeDark": "serika_dark",
  "autoSwitchTheme": false,
  "customTheme": false,
  "customThemeColors": [
    "#323437",
    "#e2b714",
    "#e2b714",
    "#646669",
    "#2c2e31",
    "#d1d0c5",
    "#ca4754",
    "#7e2a33",
    "#ca4754",
    "#7e2a33"
  ],
  "favThemes": [],
  "showKeyTips": true,
  "showLiveWpm": false,
  "showTimerProgress": true,
  "smoothCaret": true,
  "quickTab": false,
  "punctuation": true,
  "numbers": false,
  "words": 50,
  "time": 60,
  "mode": "words",
  "quoteLength": [
    1
  ],
  "language": "english",
  "fontSize": "15",
  "freedomMode": false,
  "difficulty": "normal",
  "blindMode": false,
  "quickEnd": false,
  "caretStyle": "default",
  "paceCaretStyle": "default",
  "flipTestColors": false,
  "layout": "default",
  "funbox": "none",
  "confidenceMode": "off",
  "indicateTypos": "off",
  "timerStyle": "mini",
  "colorfulMode": false,
  "randomTheme": "off",
  "timerColor": "main",
  "timerOpacity": "1",
  "stopOnError": "off",
  "showAllLines": false,
  "keymapMode": "off",
  "keymapStyle": "staggered",
  "keymapLegendStyle": "lowercase",
  "keymapLayout": "overrideSync",
  "fontFamily": "Source_Code_Pro",
  "smoothLineScroll": false,
  "alwaysShowDecimalPlaces": false,
  "alwaysShowWordsHistory": false,
  "singleListCommandLine": "manual",
  "capsLockWarning": true,
  "playSoundOnError": false,
  "playSoundOnClick": "off",
  "soundVolume": "0.5",
  "startGraphsAtZero": true,
  "swapEscAndTab": false,
  "showOutOfFocusWarning": true,
  "paceCaret": "off",
  "paceCaretCustomSpeed": 100,
  "repeatedPace": true,
  "pageWidth": "100",
  "chartAccuracy": true,
  "chartStyle": "line",
  "minWpm": "off",
  "minWpmCustomSpeed": 100,
  "highlightMode": "letter",
  "alwaysShowCPM": false,
  "enableAds": "off",
  "hideExtraLetters": false,
  "strictSpace": false,
  "minAcc": "off",
  "minAccCustom": 90,
  "showLiveAcc": false,
  "showLiveBurst": false,
  "monkey": false,
  "repeatQuotes": "off",
  "oppositeShiftMode": "off",
  "customBackground": "",
  "customBackgroundSize": "cover",
  "customBackgroundFilter": [
    0,
    1,
    1,
    1,
    1
  ],
  "customLayoutfluid": "qwerty#dvorak#colemak",
  "monkeyPowerLevel": "off",
  "minBurst": "off",
  "minBurstCustomSpeed": 100,
  "burstHeatmap": false,
  "britishEnglish": false,
  "lazyMode": false,
  "showAverage": "off",
  "tapeMode": "off"
}

### Current Behavior

I have created the ape keys from the setting, When i try to access the mokey type api, i get the following error
```
{"message":"Unknown authentication scheme","data":{"errorId":"ad4c6788-8046-41ed-af52-410071459573","uid":""}}
```
so far i tried these two api and got the same error
- user_data_api = "https://api.monkeytype.com/users/stats"
- last_result = "https://api.monkeytype.com/results/last"

### Environment

- OS:
- Browser:
- Browser Version:

### Anything else?

Can you tell me if i miss anything ?.

Also i like to inform you that, URL provided in the API documentation example is wrong. I have attached the image for your reference.
<img width="1376" alt="monkeytype-docs-issue" src="https://user-images.githubusercontent.com/18457002/170648157-c964df76-e6ed-48ea-b15a-f16d2a48af9a.png">

**Comment by Miodec** [comment]
Did you remember to add the authorization header?

**Comment by razairl** [comment]
Did you add the "ApeKey" before your ape key in the authentication headers? Your authentication HTTP header should look like `Authorization: ApeKey YOUR_APE_KEY`.

**Comment by ThangaAyyanar** [comment]
Yep i did it.
<img width="1140" alt="Screenshot 2022-05-27 at 10 44 49 PM" src="https://user-images.githubusercontent.com/18457002/170756878-690efe15-5174-4b67-b0b7-314c8324f30c.png">

**Comment by Miodec** [comment]
Be sure to say "ApeKey" before the ape key. Also seems like Postman has its own Authorization tab, so try using that too.

**Comment by ThangaAyyanar** [comment]
Yep that made it worked and also i forgot to tick the active checkbox in ape keys. I will close the issue. 

One more thing, I like to remind you that example url generated in the docs for api reference is improper.

Thanks @Miodec
