### ISSUE TITLE
Swapping <tab> and <esc> functionality swaps the keys everywhere

### ISSUE THREAD

**Issue by Gvanderl** [monkeytypegame/monkeytype#3051]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

When enabling the option for swapping the esc and tab behavior, the swaps happens everywhere. So you can restart using <esc> (expected behavior), but you can't use it to swap fields or type tab in text. For example in python quotes, you have to press <esc> for indentation.

### Expected Behavior

Allow the user to set custom keys to avoid conflicts. 

### Steps To Reproduce

1. Swap esc and tab in options
2. Select Python language
3. Select the "Quote" mode
4. When prompted to type tabs, note that you have to press escape. 

### Environment

- OS: OSX, Ubuntu, Win10
- Browser: FireFox, Chrome

**Comment by Miodec** [comment]
Replaced with #3130
