### ISSUE TITLE
"Off" option text not displaying on Gruvbox (dark) theme

### ISSUE THREAD

**Issue by EncryptedUser7** [monkeytypegame/monkeytype#3052]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

EncryptedUser7

### Account config

{"theme":"gruvbox_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":false,"quickTab":true,"punctuation":false,"numbers":false,"words":50,"time":15,"mode":"time","quoteLength":[0,1,2,3],"language":"english","fontSize":"15","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"block","paceCaretStyle":"block","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"below","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"word","showAllLines":true,"keymapMode":"react","keymapStyle":"alice","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","fontFamily":"Source_Code_Pro","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":true,"playSoundOnClick":"4","soundVolume":"0.5","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"max","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"word","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"custom","minAccCustom":96,"showLiveAcc":true,"showLiveBurst":false,"monkey":false,"repeatQuotes":"typing","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"wpm","tapeMode":"off"}

### Current Behavior

When Looking at the "blind mode" setting, (havn't tested on other themes but,) the text for the "on" option does not display

### Expected Behavior

There should be the "On" text on the button

### Steps To Reproduce

1. Set the colortheme to Gruvbox Dark
2. Go to settings
3. Scroll down to "Blind Mode"

### Environment

- OS: Chrome OS
- Browser: Google Chrome
- Browser Version: 99.0.4844.94 (Official Build) （64 ビット） 

### Anything else?

![Screenshot 2022-05-31 14 54 17](https://user-images.githubusercontent.com/86505727/171283315-1d287bb7-3eec-427a-8b8c-6e3ce9b15446.png)

**Comment by Miodec** [comment]
Its a joke, button is 'blind'
