### ISSUE TITLE
Inconsistencies with the anticheat

### ISSUE THREAD

**Issue by Fate1405** [monkeytypegame/monkeytype#3079]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

None

### Current Behavior

The anticheat needs to be upgraded significantly after recent testing. It seems that with only a few lines of code, you can easily bypass it and acheive impossibly high wpm scores.

Example code. (NB. Screen dimensions are for a Macbook Air)

```
"""

This Simple Program will play monkeyType at a very fast wpm (300).
It is not very accurate with about 1/3 of games ending erroneously.

This is for testing purposes only and the author does not condone cheating.

"""

import pytesseract
import numpy as np
import pyautogui
import random
from time import sleep

timings =  {"30_seconds": 4, "15_seconds": 3}

def monkeyTyper(time):
    sleep(1)
    for i in range(timings[time]):
        text = pytesseract.image_to_string(np.array(pyautogui.screenshot(region=(500,809, 1900, 290)))) # Change the values in region for different screens

        text = text.replace("\n", " ")

        print(text)

        pyautogui.write(text, interval=random.randrange(1, 20) * 0.001)

monkeyTyper("15_seconds")```

This is a very crude example but malicious users could easily manufacture far superior and more covert algorithms.

### Expected Behavior

It would be expected that the anticheat flags the behaviour exhibited by nefarious programs such as the one above for further study and invalidates the results.

### Steps To Reproduce

1. Install all necessary dependencies
2. Change region to fit text on screen dimensions
3. Turn of caret in settings
4. Run code and switch to browser
5. Wait.

### Environment

- OS: MacOS
- Browser: Chrome
- Browser Version: Latest


### Anything else?

_No response_

**Comment by Bruception** [comment]
There’s not much we can do about this at the moment. I’ll leave this issue open for others to pitch in.

**Comment by Miodec** [comment]
Can you post a screenshot of an example cheated result?

**Comment by Fate1405** [comment]
Here is an example:

<img width="1075" alt="cheat example" src="https://user-images.githubusercontent.com/58146913/172681980-f68dc6fa-1c39-4b30-b01d-eb189bd5b228.png">

**Comment by Bruception** [comment]
> Here is an example:
> 
> <img alt="cheat example" width="1075" src="https://user-images.githubusercontent.com/58146913/172681980-f68dc6fa-1c39-4b30-b01d-eb189bd5b228.png">

Anti-cheat doesn’t kick in until a result is saved. Which requires an account.

**Comment by Fate1405** [comment]
Ah I see thank you for clarifying, apologies for any confusion or delay. After testing on an alt account, it seems that your anti-cheat does work as intended. Perhaps then the only suggestion I would make would be to evaluate results regardless of whether they are being saved.

**Comment by Miodec** [comment]
> Ah I see thank you for clarifying, apologies for any confusion or delay. After testing on an alt account, it seems that your anti-cheat does work as intended. Perhaps then the only suggestion I would make would be to evaluate results regardless of whether they are being saved.

This would require additional API requests (which are not worth because the result is not being saved) or storing the anticheat system on the client. Obviously this would enable cheaters to just analyse how it works and avoid all checks (anticheat is not open source)
