### ISSUE TITLE
custom text random seems buggy

### ISSUE THREAD

**Issue by ubitux** [monkeytypegame/monkeytype#3127]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

ux

### Current Behavior

When using `custom` mode, with the following word sequence: `many I'll I'm I've it'll it's he'll he's they're don't won't can't however ease`, with `Random` enabled and `Time=60`, only "however", "ease" and "many" are present. Strangely, removing the last word ("ease") makes the other words appear. There may be something wrong in the random...

### Expected Behavior

A correct distribution of all the words.

### Steps To Reproduce

1. Click `custom`
2. Click `change`
3. Enter `many I'll I'm I've it'll it's he'll he's they're don't won't can't however ease`
4. Check `Random`
5. Enter `60` in the `Time` field
6. Click `ok`

### Environment

- OS: Linux
- Browser: Firefox
- Browser Version: 101.0.1

**Comment by ubitux** [comment]
> Im pretty sure this is because i recently added a check which removes punctuated words if punctuation mode is disabled. Ill remove that check for custom mode.

Note that the punctuated words actually start appearing if we remove the "ease", probably because the number or words end up being smaller than 3?

**Comment by Miodec** [comment]
> Note that the punctuated words actually start appearing if we remove the "ease", probably because the number or words end up being smaller than 3?

The generation tries its best to avoid repeated words. If it fails after 100 tries it just gets any word. That's why the punctuated words *sometimes* appeared.

Anyway, its fixed. Will be deployed with the next update.

**Comment by ubitux** [comment]
Thanks for the fix.

I wanted to point it out because it means we can bypass the non-quote mechanism, but I assume this is not for security reasons so I guess that's fine.
