### ISSUE TITLE
Implement a better profanity detection solution

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3207]
Our current naive solution marks a lot of false positives. We need to consider existing technologies that might handle this better.

**Comment by angusjoshi1** [comment]
Hey! How about using this package for this? https://www.npmjs.com/package/bad-words . It works in much the same way as the current profanity detection, but contains a few extra useful functions and perhaps a more comprehensive list?

**Comment by rustom** [comment]
What are examples of the false positives? Could implement a library solution quickly @Miodec

**Comment by Miodec** [comment]
The main problem is with short words in those lists (either ours or the one that @angusjoshi1 suggested) - if your nickname happens to contain those combinations of letters it will be considered profane. I think best solution here for now is just to manually refactor the list (compare it to https://github.com/web-mech/badwords/blob/master/lib/lang.json perhaps) to include anything we have missed and exclude anything that is not very explicit/ could be easily misinterpreted.

**Comment by scpdavis1** [comment]
Hi, I am interested in attempting this. is anyone assigned to it yet?

**Comment by scpdavis1** [comment]
Hi! im new to contributing to open source projects but I would like to try this out. Can someone point me to where I can get started on understanding the related code?

**Comment by Miodec** [comment]
> Hi! im new to contributing to open source projects but I would like to try this out. Can someone point me to where I can get started on understanding the related code?

No code to understand really. Just expand this list a bit, and make sure its not prone to false positives https://github.com/monkeytypegame/monkeytype/blob/master/backend/src/constants/profanities.ts

**Comment by scpdavis1** [comment]
Hello again! what current methods are you guys using to test for false positives? or if there is documentation on that topic could someone point me there?

**Comment by Miodec** [comment]
We dont really have any process set up for that. When I went through the list last time I just removed very short words and combinations of letters that seemed too generic
