### ISSUE TITLE
Inconsistent highest wpm in profile

### ISSUE THREAD

**Issue by Cuzzie** [monkeytypegame/monkeytype#3208]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

Cuzzie

### Account config

{"theme":"catppuccin","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"tab","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"quote","quoteLength":[1],"language":"english","fontSize":"15","freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"block","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"text","colorfulMode":false,"randomTheme":"off","timerColor":"black","timerOpacity":"0.25","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"dvorak","fontFamily":"Fira_Code","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"5","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

In my profile, the highest wpm shown at the upper section (the correct one) is different from the one shown at the lower section (incorrect one). I've attached the screenshot for your reference. The 216wpm is the correct one, and the 200.71wpm is the incorrect one.

![image](https://user-images.githubusercontent.com/4451176/175244816-1c8a900b-9472-4cd8-8cab-9bf9d24d00a5.png)

![image](https://user-images.githubusercontent.com/4451176/175246017-88820f28-a9e0-4799-a532-5a6768f3061c.png)

### Expected Behavior

Both the highest wpm at upper section and lower section should be consistent. 

### Steps To Reproduce

1. Login to MonkeyType as my user.
2. Go to my profile.
3. The highest wpm at the upper section has different value from the one at the lower section.

### Environment

- OS: Windows 11
- Browser: Chrome
- Browser Version: 102.0.5005.115

**Comment by Miodec** [comment]
Stats at the top are all time. The stats below the graph are only from the last 1000 tests. Meaning if your best is outside the '1000 range', the two numbers will appear out of sync.
