### ISSUE TITLE
API Rate Limit - HTTP Status 429

### ISSUE THREAD

**Issue by MadMalisko** [monkeytypegame/monkeytype#3211]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

BruceLeeRoy

### Current Behavior

I'm using a simple python script to test the API.  Every (approx) 30 seconds the script makes one call to /results/last using a single API key.  

After 60 successful requests, I will start getting HTTP error 429.  

In my testing so far 60 **successful** requests seems to be the trigger.  

I receive error 429 consecutively, so when I do receive it and make a subsequent API call 30 seconds later, it will fail again with the same message.  The API continues to respond in this manner for about 20 minutes.  

Sample log (omitting previous 59 successful API calls)  
```
...
2022-06-23 10:58:24.248157 SUCCESS - HTTP Status: 200
2022-06-23 10:58:54.517874 ERROR - HTTP Status: 429
Headers sent: {'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'ApeKey Blah', 'Content-Type': 'application/json'}
Response: {"message":"Too many attempts, please try again later.","data":{"errorId":"c80077cc-7947-4ec1-a432-49c800a4c5da","uid":""}}
2022-06-23 10:59:24.762200 ERROR - HTTP Status: 429
Headers sent: {'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'ApeKey Blah', 'Content-Type': 'application/json'}
Response: {"message":"Too many attempts, please try again later.","data":{"errorId":"797b57e0-6143-4410-bdbb-ec7e9138672f","uid":""}}
2022-06-23 10:59:54.990281 ERROR - HTTP Status: 429
Headers sent: {'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'ApeKey Blah', 'Content-Type': 'application/json'}
Response: {"message":"Too many attempts, please try again later.","data":{"errorId":"2406d114-6b5e-4aee-bb93-f9f617b9574c","uid":""}}
...


2022-06-23 11:22:05.967628 ERROR - HTTP Status: 429
Headers sent: {'User-Agent': 'python-requests/2.28.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'ApeKey Blah', 'Content-Type': 'application/json'}
Response: {"message":"Too many attempts, please try again later.","data":{"errorId":"df51b708-d2fa-4106-b885-efcbc06c06d7","uid":""}}
2022-06-23 11:22:36.189544 SUCCESS - HTTP Status: 200
2022-06-23 11:23:06.451411 SUCCESS - HTTP Status: 200
2022-06-23 11:23:36.718379 SUCCESS - HTTP Status: 200
2022-06-23 11:24:07.037356 SUCCESS - HTTP Status: 200
2022-06-23 11:24:37.336966 SUCCESS - HTTP Status: 200
```

### Expected Behavior

As I am hitting a single endpoint using a single API key every 25 seconds, I would not expect to hit any sort of rate limiting.

### Steps To Reproduce

Super simple example (excuse any typos or bugs).  
My next test will be to decrease the sleep time to 2 or 3 seconds - this shouldn't hit the actual limit and will speed up testing.  
```
import datetime, json, requests, time
def retrieve_last_test(ape_key):
    uri = "https://api.monkeytype.com/results/last"
    headers = {
        "Authorization": f"ApeKey {ape_key}",
        "Content-Type": "application/json"
    }
    try:
        test_results = requests.get(uri, headers=headers)
    except Exception as e:
        print(e)
    if test_results.status_code != 200:
        print(f"{datetime.datetime.utcnow()} ERROR - HTTP Status: {test_results.status_code}")
        print(f"Headers sent: {test_results.request.headers}")
        print(f"Response: {test_results.text}")
    else:
        print(f"{datetime.datetime.utcnow()} SUCCESS - HTTP Status: 200")
        

if __name__ == "__main__":
    ape_key = "someApiKey"
    while True:
        retrieve_last_test(ape_key)
        time.sleep(30)
```

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by MadMalisko** [comment]
Clarification -- I'm using the api of monkeytype.com.  

I'm looking in /backend/src/middlewares/rate-limits.ts.  I'm seeing  
```
const REQUEST_MULTIPLIER = process.env.MODE === "dev" ? 100 : 1;  
  
export const resultsGet = rateLimit({
  windowMs: ONE_HOUR,
  max: 60 * REQUEST_MULTIPLIER,
  keyGenerator: getAddress,
  handler: customHandler,
});  
```  
I feel like monkeytype.com resultsGet.max == 60 and the timespan that this is being checked against is greater than one minute.   

Additionally I *was* logged in with an errant browser tab while making API calls.  Intuitively I feel like the API keys would be rate-limited separately from live browser sessions but no clue.  So making sure I'm logged out everywhere and testing again.

**Comment by Miodec** [comment]
> To reconcile this, we could bypass the web client rate limiter when a requests tries to authenticate with an Ape key.
> 
> @Miodec what do you think?

Sounds good to me
