### ISSUE TITLE
Can't open command line when using a foreign language

### ISSUE THREAD

**Issue by Eloren1** [monkeytypegame/monkeytype#3233]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Since you have changed the way Tab and Esc work, I can't open a command line like before with Tab key.
I restart the test with Esc key. So now the only option is to use a keyboard shortcut `CTRL-SHIFT-P` that works on the English layout, but in Russian this shortcut opens the print page menu.

### Expected Behavior

1. Return ability to open a command line with Tab key when swapped Tab and Esc behaviours. 
1. Use a different method of reading shortcuts to capture them from other types of layouts.

### Steps To Reproduce

1. `Quick restart` = `ESC`
2. Done, you can't use TAB/ESC keys to open a command line
3. When using a Russian or other layout other than English, the command line cannot be opened in any way.

**Comment by Miodec** [comment]
What do you think would be a good new shortcut for the command line?

**Comment by devkennyy** [comment]
In general or language specific?

**Comment by Eloren1** [comment]
@devkennyy Tested only on Russian layout

@Miodec I would use Tab for this
Right now it's:
👍 When `Quick restart` = `Tab`, there are two options: long shortcut or Esc key 
👎 When `Quick restart` = `Esc`, there is only one option: long shortcut (plus which doesn't work in other languages)

**Comment by Ferotiq** [comment]
@Miodec maybe have another option for q

**Comment by Ferotiq** [comment]
What if we just disable tab navigation if you're using quick restart regardless, and just have the commandline open with the other key. And only have tab navigation available if you're not using quick restart. ¯\_(ツ)_/¯

**Comment by Miodec** [comment]
I dont wanna disable tab navigation all together when quick restart is enabled. I found myself missing it a lot when tabbing through forms or popups and I use quick restart all the time.

**Comment by Eloren1** [comment]
But right now we can't use tab navigation when quick restart is enabled (Esc / Tab) anyway

Holding the key is a good idea

**Comment by Miodec** [comment]
> But right now we can't use tab navigation when quick restart is enabled (Esc / Tab) anyway

You can if a popup is open or you are on the login page.

**Comment by Miodec** [comment]
I could also make it so you cant open the cmmandline with tab when you are on the login page or a popup is open
