### ISSUE TITLE
Min Accuracy should have a "grace period" at the beginning

### ISSUE THREAD

**Issue by MichaelDeutschCoding** [monkeytypegame/monkeytype#3299]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

When attempting to type with a minimum accuracy setting, it will fail the test if one of the first characters happens to be typed incorrectly. This certainly fits the technical specification for a minimum accuracy **percentage**, but leads to a less pleasant user experience. One mistyped character within the first "x" number of characters will have disproportionally greater impact than one mistyped character later on in the test.

There does seem to be an attempt at a "grace period", but it doesn't help -- because if you've already made more than one mistake earlier, it won't fail immediately, but once you type enough characters it does fail, no matter how accurate you are for the rest of it.

### Expected Behavior

Addition of logic to provide some sort of "grace period" or "smoothing" for the beginning of a test. One mistyped character at the beginning shouldn't immediately fail the test.

### Steps To Reproduce

Go to "settings"
Set "min accuracy"
Start a test, and make a mistake within the first few characters
Continue typing perfectly, and then "randomly" at some point it will fail the test due to the minimum accuracy requirement

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 103.0.5060.53 (Official Build) (64-bit)

**Comment by MichaelDeutschCoding** [comment]
So, I feel like that might be a bit better, just to give a more predictable experience.
I couldn't think of a good approach to allow for smoothing in time based tests. In tests that have a specific length (of words, characters, or quotes), perhaps the min accuracy could be set to only take effect after a certain percentage (perhaps 10%) of the test is completed. Time based tests ends up being a bit more tricky.

If you can just point me in the right direction where the minimum accuracy is enforced, I'm happy to open a PR removing the grace period for now, if you'd like.

**Comment by casualpigeon** [comment]
maybe let the users input a word grace period

**Comment by mintbird** [comment]
IMO The Min Accuracy should be calculated on the end of the test.

**Comment by Miodec** [comment]
Closing due to the grace period being removed in favor of predictability and consistency
