### ISSUE TITLE
Weird lines showing while typing

### ISSUE THREAD

**Issue by Tamir198** [monkeytypegame/monkeytype#3305]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Current Behavior

Sometimes when typing I see those lines:

![image](https://user-images.githubusercontent.com/34707669/177286796-16904ed1-26b9-4215-8253-32514fb2d85c.png)

This is a picture that I took from my phone, because when I try to Print Screen it the line are no longer on the screen, the screenshot:
![image](https://user-images.githubusercontent.com/34707669/177287017-cad9d018-280d-49fe-a515-f9b72842700a.png)

### Expected Behavior

Expected no lines on the screen while writing 

### Environment

- OS: Windows 10
- Browser: chrome
- Browser Version: 103.0.5060.66 (Official Build) (64-bit)

### Anything else?

This problem only occurs on the site, so I don't think that my PC is the problem here.

**Comment by devkennyy** [comment]
So it doesn't occur when you're signed in, nor does it occur when you're signed out...?

**Comment by Miodec** [comment]
Yeah, its a rendering glitch thats showing up on some machines. Try other browsers or as a last resort disable smooth caret. Im afraid not much else can be done about this.
