### ISSUE TITLE
Annoying scroll bar on typing page

### ISSUE THREAD

**Issue by pingshunhuangalex** [monkeytypegame/monkeytype#3330]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

pingshun huang

### Current Behavior

A scroll bar shows up on the typing page that allows the page to be scrolled down a bit
![image](https://user-images.githubusercontent.com/17170199/178131860-9ffcc5a0-22ef-46e3-8371-2de021923a33.png)

### Expected Behavior

No scroll bar on typing page

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
Looks like its grammarly.. Can you verify that? 
![image](https://user-images.githubusercontent.com/13181393/178259299-550bd1d3-a212-40e2-bdbf-90a75ca1f9a6.png)

**Comment by Miodec** [comment]
> Turning off writing suggestions is not enough, I had to turn everything off in Grammarly to make the scroll bar go away. However, I can turn everything back on and the issue won't reproduce itself.
> 
> Weird but it's fixed. Thanks.

Ive emailed Grammarly about this, hopefully they will be able to fix this / show me how to stop this from happening
