### ISSUE TITLE
All time typing speed graph not showing full timeline

### ISSUE THREAD

**Issue by kleenkanteen** [monkeytypegame/monkeytype#3333]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

monketypistgay

### Current Behavior

![latest](https://user-images.githubusercontent.com/67878058/178161463-846b9abe-afb4-4a89-8385-374fec372bca.PNG)

As you can see my mouse hovers over one of the rightmost points which is in Dec 2021. I took many tests since then to now but the points are not shown in the graph. Also the rightmost text box pop ups go outside the graph. I am using a 4k monitor scaled at 175%. Zooming in or out the browser makes no difference.

### Expected Behavior

All speed test wpm shows from July 2021 to July 2022.

### Steps To Reproduce

1. Go to profile
2. Pull all time filter
3. Make sure your history goes back at least a year

### Environment

- OS: W10
- Browser: Chrome
- Browser Version: Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by Miodec** [comment]
This is because you are only able to view 1000 of your recent results. The limitation is there for cost and performance reasons. A way to view more of your history is planned.

**Comment by MathildeMousset** [comment]
So the "all time button" is in fact a "last 1000 tests" button?
