### ISSUE TITLE
Check if "show average" is working correctly

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3356]
It might be delayed by 1 result

**Comment by kleenkanteen** [comment]
You should add more details to your issue

**Comment by Miodec** [comment]
> You should add more details to your issue

Show average setting is not updating immediately after going back to the test page from the results page. Its delayed by one result.

**Comment by Ferotiq** [comment]
> You should add more details to your issue

Also, that's a bot account, for collaborators and devs to submit issues from the Discord server.
