### ISSUE TITLE
input autocomplete showing when typing

### ISSUE THREAD

**Issue by daklay** [monkeytypegame/monkeytype#3362]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Daklay

### Environment

- OS: Windows 10
- Browser: Microsoft Edge
- Browser Version: 103

### Anything else?

![image](https://user-images.githubusercontent.com/71189108/182616786-9c7ae757-9fe9-4efd-a01f-d477ccee48ea.png)

**Comment by Miodec** [comment]
Yeah, Edge broke something in the latest update. There is `autocomplete="off"` on the input but its just ignored for some reason..

**Comment by kashyapabhinav1906** [comment]
The issue is persistent only on the EDGE browser, it's working fine on the other ones.

**Comment by Miodec** [comment]
https://www.tenforums.com/tutorials/160845-enable-disable-save-fill-personal-info-microsoft-edge.html Here is a fix for now
