### ISSUE TITLE
Make sure profile bio text wraps instead of overflowing the container

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3365]

**Comment by jeffrey-zang** [comment]
![image](https://user-images.githubusercontent.com/66485719/183220918-663275ac-9552-43f9-9d02-51f226425596.png)

**Comment by jeffrey-zang** [comment]
multiple lines:
![image](https://user-images.githubusercontent.com/66485719/183220954-5521e781-40a2-41d9-bf9c-ee5f9e5ce0fe.png)
