### ISSUE TITLE
Bad Performance message while typing test and end the test immediately

### ISSUE THREAD

**Issue by DhananjayPorwal** [monkeytypegame/monkeytype#3367]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

DhananjayPorwal

### Account config

{"theme":"cyberspace","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":30,"mode":"time","quoteLength":[0,1,2,3],"language":"english","fontSize":"15","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When I start the typing test, it stops me and throws me to the result page along with error message. Browser is upto-date and I checked website behavior before/after clearing the cookies/cache.
![Web capture_4-8-2022_184722_monkeytype com](https://user-images.githubusercontent.com/51775507/182857636-7ab5c71f-c56e-4fc3-966c-fad1a17efd6a.jpeg)

### Expected Behavior

Test should be done and after that, it show the typing speed and graphs related to it.

### Environment

- OS: Windows 11
- Browser: Microsoft Edge
- Browser Version: Version 103.0.1264.77 (Official build) (64-bit)

### Anything else?

![Web capture_4-8-2022_184722_monkeytype com](https://user-images.githubusercontent.com/51775507/182858579-453f38a7-1727-453e-b40f-1512ae3c0150.jpeg)

**Comment by kevidoplz** [comment]
Do you have efficiency mode enabled in Edge? If so, disabling it may fix your issue.

**Comment by Miodec** [comment]
Disable high efficiency mode in Edge settings to fix this issue.

**Comment by DhananjayPorwal** [comment]
Thanks @Miodec and @kevidoplz buddy, It works.
