### ISSUE TITLE
XP Glitch

### ISSUE THREAD

**Issue by teddinotteddy** [monkeytypegame/monkeytype#3370]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues
(I saw I similar issue however it doesn't have a description and it seems to be different then what I did)

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

No

### Account name

Teddi

### Current Behavior

I went to monkeytype did a test and I wasn't logged in so I clicked the sign in button to save my result and I logged in successfully. However when I logged in I had 26 more levels than I had before. I am not sure about the exact number I just know that I was level 20 or 21. It still says I have that many points.

### Steps To Reproduce

(I haven't tried to reproduce this but this is how it happened) Sign out, do a test, click the sign in to save your results button.

### Environment

- OS: Mac OS Monterey
- Browser: Safari
- Browser Version: 15.6

### Anything else?

<img width="2032" alt="Screen Shot 2022-08-04 at 11 23 25 AM" src="https://user-images.githubusercontent.com/83455454/182902385-a895a174-7dda-4770-aee5-908ef6029c6b.png">

**Comment by Miodec** [comment]
I just awarded everyone xp based on their time typing so that's why it looked like you jumped 20 levels.

**Comment by teddinotteddy** [comment]
Oh.
