### ISSUE TITLE
Daily bonus not refreshed at local time

### ISSUE THREAD

**Issue by pingshunhuangalex** [monkeytypegame/monkeytype#3408]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

I wanted to create a thread in the discussion, but can't find the create discussion button somehow, so I have to raise a ticket here.

Not sure when the daily bonus is reset atm, but it's definitely not 12am in my local time

### Expected Behavior

The daily bonus should refresh at 12am local time.

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
It is not meant to reset local time. Sending any data from the user (including timezone) is not safe and could let the user get multiple daily bonuses. That's why the daily bonus is based on server time.

**Comment by pingshunhuangalex** [comment]
The check should happen on the server side, but the time shouldn't.

Anyways, what's the timezone of the server, so at least I can do the calculation and have an idea myself? Thanks.

**Comment by Bruception** [comment]
> The check should happen on the server side, but the time shouldn't.
> 
> Anyways, what's the timezone of the server, so at least I can do the calculation and have an idea myself? Thanks.

Daily bonus is awardable at 0:00 UTC
