### ISSUE TITLE
AZERTY Keyboard with french accents. "^"

### ISSUE THREAD

**Issue by sannier3** [monkeytypegame/monkeytype#3417]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

JBSAN3

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"custom","quoteLength":[0],"language":"french","fontSize":"15","freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"azerty","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"next","keymapStyle":"matrix","keymapLegendStyle":"uppercase","keymapLayout":"azerty","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":true,"playSoundOnClick":"4","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

It's the same issue with the #2081 but I repost it in english now
I am with an AZERTY keyboard with the French words (accents too). I can't write the words that includes ê û ô...
For write this letter with this accent, I must to use the "^" with the letter after. When I press the "^", the letter appears directly in red before I can use the letter

### Expected Behavior

Example :
The text to write : être ou ne pas être
When "^" pressed : (nothing, waiting to press the letter)
When letter pressed : ê

### Steps To Reproduce

Example :
The text to write : être ou ne pas être
When "^" pressed : ê (in red)
When letter pressed : êe (in red)

### Environment

- OS: All systems (linux or windows
- Browser: All browsers (Chrome mainly)
- Browser Version: 104.0.5112.101

### Anything else?

![image](https://user-images.githubusercontent.com/72016241/185479588-3605d25b-9db7-479b-8724-4426a166afef.png)

**Comment by Miodec** [comment]
Setting layout emulator to `off` instead of `azerty` will fix this issue
