### ISSUE TITLE
There is no option to create a new discussions in the repo.

### ISSUE THREAD

**Issue by nishu-murmu** [monkeytypegame/monkeytype#3441]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

nishumurmu

### Steps To Reproduce

1. Go to discussions and try to create new discussions.

### Environment

- OS: MacOs
- Browser: Any
- Browser Version: Any

**Comment by Miodec** [comment]
Can you check now?

**Comment by nishu-murmu** [comment]
Yeah it's there now. Thanks 👍
