### ISSUE TITLE
Make escape close the commandline when quick restart is set to escape

### ISSUE THREAD

**Issue by dwelle** [monkeytypegame/monkeytype#3448]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

dwelle

### Current Behavior

When `esc` is set as quick restart key, it ceases to work to dismiss dialogs/actions.

### Expected Behavior

It should still work to dismiss dialogs.

### Steps To Reproduce

1. set `esc` as quick restart key
2. open a dialog, e.g. with `tab` key
3. press `esc` to dismiss it
4. nothing happens

### Environment

- OS: Windows 10
- Browser: Chrome
- Browser Version: 104

**Comment by nishu-murmu** [comment]
@Miodec he is talking about commandline, btw if you'd suggest it's a genuine bug, I'd like to work on that.

**Comment by Miodec** [comment]
@nishu-murmu alright, all yours
