### ISSUE TITLE
Add "add current theme to favorite" command

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3463]

**Comment by sondrekje** [comment]
I can take this 🙌

**Comment by Miodec** [comment]
Unassigned due to inactivity

**Comment by varunKT001** [comment]
@Miodec Can I work on this issue?

**Comment by varunKT001** [comment]
@Miodec Please assign me this issue. I would love to work on this feature.

**Comment by Miodec** [comment]
> @Miodec Please assign me this issue. I would love to work on this feature 😄

Sure thing
