### ISSUE TITLE
Make ctrl shift p toggle the command line instead of just opening it

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3465]

**Comment by Jonny-exe** [comment]
Right now, you can toggle the command line with the escape key. It could be changed so that the escape and ctrl-shift-p do the same thing. I would be happy to submit a PR if this is the desired behavior.

**Comment by Miodec** [comment]
@nishu-murmu as mentioned on the pr, please comment on issues you want to work on first, so there is no overlap. 

Sorry about that @Jonny-exe

**Comment by nishu-murmu** [comment]
Sorry about that @Jonny-exe and @Miodec next time I'll be sure of that.

**Comment by Jonny-exe** [comment]
No problem
