### ISSUE TITLE
PWA installion button no longer shows up in Chrome (Mac)

### ISSUE THREAD

**Issue by pingshunhuangalex** [monkeytypegame/monkeytype#3489]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Environment

- OS: macOS Monterey 12.5.1
- Browser: Chrome
- Browser Version: 104.0.5112.101

**Comment by Miodec** [comment]
PWA got removed for now because of issues with caching. You can still get a similar experience by going to the chrome menu, more tools, create shortcut and checking "open as window"
