### ISSUE TITLE
Make block, outline and underline caret width dynamic (based on the letter width)

### ISSUE THREAD

**Issue by jfabellera** [monkeytypegame/monkeytype#3518]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

jannifer

### Account config

{"theme":"8008","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#36393f","#f44c7f","#f44c7f","#939eae","#2e343d","#e9ecf0","#da3333","#791717","#c5da33","#849224"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":25,"time":30,"mode":"time","quoteLength":[1],"language":"korean","fontSize":1.5,"freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"block","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":false,"paceCaret":"off","paceCaretCustomSpeed":40,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":115,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":100,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"letter"}

### Current Behavior

When the language is set to Korean and caret style set to block, the caret does not always display around the entire Korean syllable that you are currently on. This is especially problematic because depending on the theme (background color, text color, caret color), it may render the current syllable unreadable to the user while the caret is visible.

### Expected Behavior

The block caret style should surround the entire current syllable for Korean as it does for the current character in English.

### Steps To Reproduce

1. Set caret style to `block`
2. Set language to English
3. See that the block surrounds each character correctly
4. Set language to Korean
5. See that the block does **not** surround each syllable correctly

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 104.0.5112.102 (Official Build) (64-bit)

### Anything else?

Example:
In the below image, the block caret should cover the entirety of "중"

![image](https://user-images.githubusercontent.com/15681113/188671722-8c3347ca-424c-4523-a3db-0fb520cb145e.png)

**Comment by neezacoto** [comment]
I'll work on this

**Comment by neezacoto** [comment]
turns out this isn't Korean specific, this has a problem to do with the block being a static size.
