### ISSUE TITLE
Can't type with layout emulator active after typing in another language previously

### ISSUE THREAD

**Issue by jfabellera** [monkeytypegame/monkeytype#3524]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

jannifer

### Account config

{"theme":"8008","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#36393f","#f44c7f","#f44c7f","#939eae","#2e343d","#e9ecf0","#da3333","#791717","#c5da33","#849224"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":25,"time":30,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"block","paceCaretStyle":"default","flipTestColors":false,"layout":"qwerty","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":false,"paceCaret":"off","paceCaretCustomSpeed":40,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":115,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":100,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"letter"}

### Current Behavior

I'm learning to type in korean as well as the halmak layout (english), and I am constantly switching between qwerty, halmak, and korean. I've noticed that after doing a typing test in korean and switching to halmak, I am not able to type in halmak i.e. when I start typing, the test starts but none of the characters are registered. The only way I have found to fix this is to refresh the site.

I use a preset to switch to halmak, but I have been able to isolate the issue (see reproduction steps).

### Expected Behavior

I should be able to switch between english, another language, and another english layout seamlessly without needing to refresh the page.

### Steps To Reproduce

1. Set language to `English`
2. Set layout emulator to `off`
3. Type English characters into monkeytype and see that they register correctly
4. Type Korean characters into monkeytype and see that they register correctly as well (even though it is a an English typing test)
5. Set layout emulator to any other layout (e.g. halmak or even qwerty)
6. Type Korean characters into monkeytype and see that they do **not** register
7. Type English characters into monkeytype and see that they **continue to not** register

Should be able to type with layout emulator active after switching from a different language to English.

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 104.0.5112.102 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Ive deployed a new version with some changes. Could you please test it now?

**Comment by jfabellera** [comment]
Looks to be working fine now 👍
