### ISSUE TITLE
Timer is running in reverse when set to 0.5 sec

### ISSUE THREAD

**Issue by whoadnan101** [monkeytypegame/monkeytype#3533]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

i dont have an account but i'm sure this bug is legit.

### Current Behavior

timer starts running in reverse

### Steps To Reproduce

1. Go to time setting
2. Click on manual time setting
3. set time to 0.5 sec
4. then you will see timer will run in reverse way

### Environment

- OS:
- Browser:
- Browser Version:

### Anything else?

This is not a vulnerability but a bug hope you got my point and resolve this issue

**Comment by meropis** [comment]
If you set to 0.5 seconds you will do an infinite test. Is there any other steps necessary to reproduce?

**Comment by Miodec** [comment]
Looks like 0.5 is floored to 0 which starts an infinite test - that's why the timer goes up. This is intended.
![image](https://user-images.githubusercontent.com/13181393/189621491-496f47f3-0fc8-4799-af5c-e04e89b2f2e3.png)
