### ISSUE TITLE
Refactor funboxes

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3547]
Add a type to each funbox and allow to select mutliple funboxes (but limit to one per type)

**Comment by egorguslyan** [comment]
I could try it, look at my fork's [readme](https://github.com/egorguslyan/monkeytype#funboxes).

**Comment by Miodec** [comment]
> I could try it, look at my fork's [readme](https://github.com/egorguslyan/monkeytype#funboxes).

Looks alright, I'm sure more conflicts will popup if you actually wann work on this

**Comment by rizwanmustafa** [comment]
> I could try it, look at my fork's [readme](https://github.com/egorguslyan/monkeytype#funboxes).

So can we assign you?

**Comment by egorguslyan** [comment]
I'm afraid of breaking internal settings structure. I guess we need to store funboxes split by # and validate when loading. Also it was a bad idea to put poetry/wikipedia into the quotes mode, cause it acts like in _words 0_ or _time 0_. Maybe it's necessary to leave them in time/words modes, but I would like to have an endless wikipedia experience until bailing out.

**Comment by egorguslyan** [comment]
![20 09 2022_12:23:1663687430](https://user-images.githubusercontent.com/42677093/191299196-8bab9ac2-4bc3-4d77-beaa-e4cdae024284.png)
