### ISSUE TITLE
Remove user from leaderboards on user reset

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3551]

**Comment by nishu-murmu** [comment]
Can try this one?

**Comment by Miodec** [comment]
> Can I try this one?

FYI the all time leaderboards are already reset, its the daily leaderboards that are the issue right now

**Comment by nishu-murmu** [comment]
@Miodec User reset means Reset Account or Reset Personal Bests?

**Comment by Miodec** [comment]
> @Miodec User reset means Reset Account or Reset Personal Bests?

Let's do both
