### ISSUE TITLE
The website stops working randomly, and it's unusable even clearing the cache

### ISSUE THREAD

**Issue by dvgniele** [monkeytypegame/monkeytype#3562]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

dvgniele

### Account config

{"theme":"onedark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"tab","punctuation":false,"numbers":false,"words":50,"time":30,"mode":"words","quoteLength":[1],"language":"italian","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

The website stops working after a sudden “refresh” it does. I was typing in words mode, 50 words, italian default, no numbers or punctuation. Firefox. 
Already triet to whitelist on ADBlock, but didn’t work, even tried clearing cache

### Expected Behavior

Load the login screen

### Environment

- OS: Windows 11
- Browser: Firefox Developer Edition
- Browser Version: 105.0b9 

### Anything else?

To get the config i had to log with edge, otherwise it would have been impossible, because i get a blank page when i try to open the website from firefox

**Comment by Miodec** [comment]
Stops working? Can you send a screenshot?

**Comment by dvgniele** [comment]
It automatically reloads the page, but all ii get after that is a blank page. Once i try to go on the site i get the same blank page as before
![monkeytype](https://user-images.githubusercontent.com/32111035/190969858-537fc43c-b245-414d-ae6d-006eb3e9cee2.gif)
if you look at the "reload" button, it animates automatically, just like the website wants to reload itself

**Comment by Miodec** [comment]
What about other browsers? Private/incognito mode?

**Comment by dvgniele** [comment]
Not happened yet on Edge, normal nor private. On firefox dev happened in both modes.
Btw if i open the browser console i get the following messages. (I'll attach the translation just below)

![image](https://user-images.githubusercontent.com/32111035/190998935-18a3a71a-98c6-4bd1-b32b-ff1fb10291a9.png)


![image](https://user-images.githubusercontent.com/32111035/190998969-c0dd8d24-fb82-4c85-b561-c7e02f2a490e.png)
> The request to access cookies and storage resources for "https://pixel.quantserve.com/pixel;r=1684298924;source=gtm;rf=0;a=p-5pR25819dph-b;url=https%3A% 2F% 2Fmonkeytype.com% 2F; uht = 2; fpan = 0; fpa = P0-1677784154-1663583503979; pbc =; ns = 0; ce = 1; qjs = 1; qv = d18171e5-20220913105912; cm =; gdpr = 0; ref =; d = monkeytype.com; dst = 1; et = 1663583503981; tzo = -120; ogl = title.Monkeytype% 2Curl.https% 3A% 2F% 2Fmonkeytype% 252Ecom% 2F% 2Ctype.website% 2Cimage. https% 3A% 2F% 2Fmonkeytype% 252Ecom% 2Fimages% 2Fmtsocial% 252Epng% 2Cdescription.A% 20minimalistic% 252C% 20customisable% 20typing% 20website% 252E% 20Test% 20yourself% 20in% 20various% 20modes% 20xtra96; sltra96; 252C sxc = 70096; ses = c721a237-bd6b-4df7-8a4c-a842e16534ab "has been blocked as it comes from a tracker and content blocking is active


![image](https://user-images.githubusercontent.com/32111035/190999015-c2fc50af-dd66-4a6f-929a-5df6c451d3a1.png)
>The "_dlt" cookie does not have a valid value for the "SameSite" attribute. Soon cookies without the "SameSite" attribute or with an invalid value will be handled as "Lax". This means that the cookie will no longer be sent in third party contests. If the application depends on the availability of this cookie in this type of context, add the attribute "SameSite = None". For more information on the "SameSite" attribute, see https://developer.zilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by Miodec** [comment]
Im pretty sure those errors are just related to the ads script. Is your firefox using some uber aggressive mode where it rejects website loading completely if it doesnt like something?

**Comment by sandrock** [comment]
I have a similar situation,  not sure if exactly the same. The homepage is empty.

Console output:

> 16:07:07.164 getting language json 2 [monkeytype.ef84d72f.js:1:619542](https://monkeytype.com/js/monkeytype.ef84d72f.js)
16:07:07.226
Edge users: Latest browser update is causing an autofill popup to appear on the typing page. <a href="https://www.tenforums.com/tutorials/160845-enable-disable-save-fill-personal-info-microsoft-edge.html">Click here</a> for a temporary fix. [monkeytype.ef84d72f.js:1:265171](https://monkeytype.com/js/monkeytype.ef84d72f.js)
16:07:07.227 updating margin [monkeytype.ef84d72f.js:1:264513](https://monkeytype.com/js/monkeytype.ef84d72f.js)
16:07:07.389 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.enthusiastgaming.net/scripts/cdn.enthusiast.gg/script/eg-aps/release/eg-aps-bootstrap-v2.0.0.bundle.js?site=monkeytype.com. (Reason: CORS request did not succeed). Status code: (null).
16:07:15.609 updating margin [monkeytype.ef84d72f.js:1:264513](https://monkeytype.com/js/monkeytype.ef84d72f.js)
16:08:07.366 Uncaught (in promise) TypeError: window.egAdPack is undefined

My uMatrix permissions seem acceptable for the website to work:

![umatrix config](https://i.imgur.com/iVb01BL.png)

Firefox 102.0 (64-bit)

**Comment by Miodec** [comment]
> I have a similar situation, not sure if exactly the same. The homepage is empty.
> 
> Console output:
> 
> > 16:07:07.164 getting language json 2 [monkeytype.ef84d72f.js:1:619542](https://monkeytype.com/js/monkeytype.ef84d72f.js)
> > 16:07:07.226
> > Edge users: Latest browser update is causing an autofill popup to appear on the typing page. [Click here](https://www.tenforums.com/tutorials/160845-enable-disable-save-fill-personal-info-microsoft-edge.html) for a temporary fix. [monkeytype.ef84d72f.js:1:265171](https://monkeytype.com/js/monkeytype.ef84d72f.js)
> > 16:07:07.227 updating margin [monkeytype.ef84d72f.js:1:264513](https://monkeytype.com/js/monkeytype.ef84d72f.js)
> > 16:07:07.389 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.enthusiastgaming.net/scripts/cdn.enthusiast.gg/script/eg-aps/release/eg-aps-bootstrap-v2.0.0.bundle.js?site=monkeytype.com. (Reason: CORS request did not succeed). Status code: (null).
> > 16:07:15.609 updating margin [monkeytype.ef84d72f.js:1:264513](https://monkeytype.com/js/monkeytype.ef84d72f.js)
> > 16:08:07.366 Uncaught (in promise) TypeError: window.egAdPack is undefined
> 
> My uMatrix permissions seem acceptable for the website to work:
> 
> ![umatrix config](https://camo.githubusercontent.com/e56bc9cdc3ea3eb8656156fe7fca841184d0f76dc88d1a47c62c1b3e0a302912/68747470733a2f2f692e696d6775722e636f6d2f6956623031424c2e706e67)
> 
> Firefox 102.0 (64-bit)

Nothing else in the console?

**Comment by dvgniele** [comment]
i get a similar table, but nothing else in the console other than what i already shared

![image](https://user-images.githubusercontent.com/32111035/191949926-1637a891-c3f6-4de0-a421-99f93e08e4db.png)

**Comment by Miodec** [comment]
Im assuming youre using some super locked down firefox version right? How do I get that?

**Comment by dvgniele** [comment]
I'm using [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/)
But the website was working fine for about 10 minutes, and then this problem occurred.
I don't think it's a locked version since it's a dev edition for web development

**Comment by Miodec** [comment]
Downloaded it, turned up the Firefox protection thing to strict, the website still works as normal...

**Comment by sandrock** [comment]
> I don't think it's a locked version since it's a dev edition for web development

We are using the [uMatrix extension](https://addons.mozilla.org/en-US/firefox/addon/umatrix/). I believe that qualifies as "locked-down" since it helps block undesired contents.

**Comment by dvgniele** [comment]
I installed the extension just to check if we had similar tables, but it wasn't installed when i had this problem at first, so i don't think it's related to the extension

**Comment by sandrock** [comment]
Just tested now. It works on my side. Sorry for my useless intervention ^^"

**Comment by ethericist** [comment]
I have the same issue and I was able to reproduce it by changing `dom.webaudio.enabled` to false in about:config

**Comment by Miodec** [comment]
> I have the same issue and I was able to reproduce it by changing `dom.webaudio.enabled` to false in about:config
> 
> I got these error codes
> 
> `Uncaught ReferenceError: AudioContext is not defined 5929 https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 n https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 4626 https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 n https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 8673 https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 n https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 5209 https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 n https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 9294 https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 n https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 i https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 O https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 <anonymous> https://monkeytype.com/js/monkeytype.ba0de2ef.js:1 <anonymous> https://monkeytype.com/js/monkeytype.ba0de2ef.js:1`

Nice find!

**Comment by Miodec** [comment]
Pushed an update, please check now @ethericist @dvgniele

**Comment by ethericist** [comment]
> Pushed an update, please check now @ethericist @dvgniele

Working for me now

**Comment by dvgniele** [comment]
It works for me too
