### ISSUE TITLE
Add 'require-await' rule to es lint

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3566]

**Comment by harshsinghatz** [comment]
Can I add this?

**Comment by Miodec** [comment]
> Can I add this?

Sorry for the late reply - this rule changes quite a lot of logic and I think I would prefer to do it myself just to be sure nothing changes.

**Comment by Miodec** [comment]
Looking into it more i dont think its needed

**Comment by harshsinghatz** [comment]
Got it!!

**Comment by harshsinghatz** [comment]
Do you have any different issues for me to pick?
