### ISSUE TITLE
Setting option is not displayed

### ISSUE THREAD

**Issue by stan-solov** [monkeytypegame/monkeytype#3579]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

Periscope

### Current Behavior

On the blind mode options, the off option shows, but the on option doesn't.

(Also Incognito is blocked, so the selection would've benn N/A

### Expected Behavior

The Yes option must write yes.

### Steps To Reproduce

1. Go to settings
2. scroll down to blind mode option
3. Look for the yes option

### Environment

- OS: Chrome
- Browser: Chrome
- Browser Version: 102

### Anything else?

![Screenshot 2022-09-21 18 13 49](https://user-images.githubusercontent.com/113939594/191622976-c91e538e-cfa2-444f-a28b-377fb2027de2.png)

**Comment by Miodec** [comment]
Intended, button is "blind"
