### ISSUE TITLE
Account Creation "Vulnerability"

### ISSUE THREAD

**Issue by Mepaers** [monkeytypegame/monkeytype#3580]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

https://streamable.com/156bwk

### Account config

https://streamable.com/156bwk

### Current Behavior

https://streamable.com/156bwk

### Expected Behavior

https://streamable.com/156bwk

### Steps To Reproduce

https://streamable.com/156bwk

### Environment

https://streamable.com/156bwk

### Anything else?

https://streamable.com/156bwk

**Comment by Miodec** [comment]
Can you email me some details?
