### ISSUE TITLE
Detagging old test does not also re-check pb

### ISSUE THREAD

**Issue by KyroKrypt** [monkeytypegame/monkeytype#3604]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

KyroKrypt

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#282a36","#d7b4f3","#d7b4f3","#646669","#000000","#f2f2f2","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"tab","punctuation":false,"numbers":false,"words":25,"time":60,"mode":"words","quoteLength":[0],"language":"english","fontSize":2,"freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"block","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"below","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"dvorak","keymapShowTopRow":"layout","fontFamily":"roboto_mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":19,"repeatedPace":true,"pageWidth":"150","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":80,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":96,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":80,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

what should have been my pb, note there is no crown next to "colemak" tag
![image](https://user-images.githubusercontent.com/64659762/192171538-15474587-eba5-4212-b2ee-6347aeffef49.png)

history of my typing with the colemak tag. My previous pb of 31 it told me was a pb. shortly after I accidentally switched back to qwerty and completed a test with the colemak tag, so I went into my history and removed the tag from the test.
![image](https://user-images.githubusercontent.com/64659762/192171543-771e6f9a-f733-4d1b-aa2d-e8854730a79c.png)

### Expected Behavior

The test should have said that I had gotten a new PB with the tag.

### Steps To Reproduce

1. Make a new tag
2. Get a PB with that tag
3. Remove the tag from the PB test
4. Take another test and have your WPM be above all tests except for this last test (it has to be below the previous test)
5. At the end of the test where it should say that you have a new PB it doesn't.

### Environment

- OS: Windows
- Browser: Opera
- Browser Version: 90.0.4480.84

**Comment by Miodec** [comment]
The way the system currently works - there is no connection between the personal bests tracking object and the results themselves, so there is no real way of "getting the previous pb for that tag" without doing a very expensive, full results scan. Im afraid the solution here is just to reset personal bests for that tag.

**Comment by asasine** [comment]
This same issue occurs when you untag a test on the page that shows the results for a test you just completed. It's a weird bug but definitely bummed me out when I encountered it.

**Comment by dmyTRUEk** [comment]
> The way the system currently works - there is no connection between the personal bests tracking object and the results themselves, so there is no real way of "getting the previous pb for that tag" without doing a very expensive, full results scan. Im afraid the solution here is just to reset personal bests for that tag.

If I understand correctly, with #5715 it's now possible to get PB with currently set tags, right? If yes, then maybe this issue could be reviewed/reopened?

**Comment by Miodec** [comment]
> > The way the system currently works - there is no connection between the personal bests tracking object and the results themselves, so there is no real way of "getting the previous pb for that tag" without doing a very expensive, full results scan. Im afraid the solution here is just to reset personal bests for that tag.
> 
> If I understand correctly, with #5715 it's now possible to get PB with currently set tags, right? If yes, then maybe this issue could be reviewed/reopened?

No, thats completely unrelated.
