### ISSUE TITLE
Korean accuracy % calculation error

### ISSUE THREAD

**Issue by Repiked** [monkeytypegame/monkeytype#3634]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

nguyj29

### Current Behavior

Just 4 days ago, the accuracy % in Korean worked fine. However, on October 4, accuracy stopped counting individual incorrect keystrokes as errors. Instead, it only counts an error when a submitted word is incorrect. As it currently is, incorrect keystrokes won't count against you unless you hit space. Master mode doesn't work as intended, as seen below.

![master mode fail](https://user-images.githubusercontent.com/52291608/194632420-d5330358-da2b-4183-a174-84ddd9cb5db2.jpg)

Note: this bug only works if you use Korean Hangeul (한국어) instead of Latin (abc) when entering incorrect characters

### Expected Behavior

Every incorrect keystroke should count against you, like in English. If you enter an incorrect character in English, it will drop the accuracy %. Furthermore, you should be able to practice missed words in Korean, but this does not work since an error is counted only when you miss a whole word, not a single character. Messing up a single character in a word in English allows you to practice it again.

![Results screen](https://user-images.githubusercontent.com/52291608/194631747-b9366817-86b6-42c5-99aa-1e3f7dd50bd5.png)

### Steps To Reproduce

1. Download the Korean IME
2. Set monkeytype to Korean
3. Set monkeytype to master mode
4. Enter incorrect Hangeul characters without hitting space
5. Observe results

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 106.0.5249.103 (Official Build) (64-bit)

### Anything else?

Upon further investigation, this may be related to #2545.

**Comment by Miodec** [comment]
I swear there is no way to make everything work with Korean... The change from #2545 was meant to ignore compose keypresses but i guess im missing a check where composition ends and a new character is started. I think i need to look back on each new character? This is really confusing

**Comment by Miodec** [comment]
Can you test now?

**Comment by Repiked** [comment]
It's working now. Thanks for the quick response.
