### ISSUE TITLE
Arabic vowels 

### ISSUE THREAD

**Issue by MostafaEwis** [monkeytypegame/monkeytype#3637]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

mastf

### Current Behavior

Arabic words in the words mode and time mode show Arabic vowels on every letter, but actually Arabic vowels are rarely written.

### Expected Behavior

The expected behavior is to show clear words without vowels just like in the quotes mode.

### Steps To Reproduce

just choose Arabic language and then choose either time mode or words mode.

### Environment

- OS: Windows 11
- Browser: Microsoft Edge
- Browser Version:

**Comment by Miodec** [comment]
Enable lazy mode in the settings to remove vowels
