### ISSUE TITLE
Color of level badge fails to update after recently opening a notification

### ISSUE THREAD

**Issue by LeviOP** [monkeytypegame/monkeytype#3638]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

Levi_OP

### Account config

{"theme":"red_samurai","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#ffffff","#3c7afc","#000000","#5e6369","#000000","#000000","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["alpine","sweden","modern_dolch"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":false,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":60,"mode":"time","quoteLength":[0,1,2,3],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":110,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":100,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"contain","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

If you have recently received and opened a notification, changing your theme will not update the color of your level badge. 

### Expected Behavior

Changing your theme will change the color of your level badge regardless of any other actions.

### Steps To Reproduce

1. Get a notification 
2. Open the notification
3. Immediately open your settings 
4. Change your theme to something with radically different colors (or not)
5. Observe that the color of the level badge next to your name has not updated

### Environment

- OS: Windows 10
- Browser: Firefox
- Browser Version: 105.0.2 (64-bit)

### Anything else?

Some images, to show what I'm talking about:
Before these screenshots, I was using the "alpine" theme, which makes the level badge look like this:
![image](https://user-images.githubusercontent.com/35459268/194728668-bf18db09-05da-4096-b606-52cb93bcea03.png)

But after following the instructions above, you can see that it doesn't change (this happens with all themes):
![image](https://user-images.githubusercontent.com/35459268/194728641-9c0cac6c-fb53-4a71-ac07-0f0006e81b3b.png)
![image](https://user-images.githubusercontent.com/35459268/194728648-2de6e540-1ebd-401e-a3b3-b29cf5eea5f9.png)
![image](https://user-images.githubusercontent.com/35459268/194728656-83f38dd5-bf6c-4634-a1ac-01bb95810e9a.png)

**Comment by Miodec** [comment]
By "open the notification" you mean opening the alerts panel? (the panel where account mail is)

**Comment by Miodec** [comment]
Oh wait, do you mean redeeming the XP rewards?

**Comment by LeviOP** [comment]
Seems like you figured it out :)
