### ISSUE TITLE
Test invalid - repeated toast notification appears and score is not computed for the repeated test

### ISSUE THREAD

**Issue by akashchouhan16** [monkeytypegame/monkeytype#3639]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Steps To Reproduce

1. Start the typing test based on words.
2. Once completed, click on the `repeat test` icon.
3. Retake the same typing test.
4. This time, with the test result, a toast notification appears with 'Test Invalid - repeated' 

### Environment

- OS: macOS Catalina Version 10.15.7 (19H15)
- Browser: Google Chrome
- Browser Version: 105.0.5195.125 (Official Build) (x86_64)

### Anything else?

![monkeytype_bug_2](https://user-images.githubusercontent.com/56465610/194750565-e024a709-7e92-4fe7-aa45-b193a72d015a.jpg)

**Comment by Miodec** [comment]
Working as intended - repeated tests are not meant to be saved
