### ISSUE TITLE
Streaks not displayed where they used to.

### ISSUE THREAD

**Issue by Godje** [monkeytypegame/monkeytype#3646]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

mayo_colemak

### Account config

{"theme":"red_samurai","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":60,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"text","colorfulMode":false,"randomTheme":"off","timerColor":"black","timerOpacity":"0.25","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":false,"chartStyle":"scatter","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

No visible streak

### Expected Behavior

Maximum streak visible. Or at least current streak visible

### Steps To Reproduce

Go to the account in which after the implementation of 1.16.2 there is at least one missing streak day.

### Environment

- OS: Linux
- Browser: Brave
- Browser Version: 106.1.44.108

### Anything else?

It used to display the "Current longest streak: 20 days", but now it doesn't display anything there, despite the streak going.
Related Images: https://imgur.com/a/So2241B

**Comment by Miodec** [comment]
Streaks are not displayed if your current streak is less than two. Looking at your account your max streak is 30 and you lost it when you didnt complete a test on October 12th

**Comment by Godje** [comment]
@Miodec then there is some sort of issue with the graph display. Because the picture attached in the ticket clearly shows that I have completed multiply tests on October 12th

**Comment by Miodec** [comment]
Its probably confusing because the streaks (and daily leaderboards) use the UTC midnight as the reset point, but your account page results use your local timezone. When looking at your account with the dates in my timezone (+1 from UTC i think) you can see you missed a day: 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/13181393/195903608-fb26f2a3-6740-4a3a-aab6-100610758e63.png">
