### ISSUE TITLE
Arabic words set is pracically unusable due to harakat/diacritics

### ISSUE THREAD

**Issue by AlawamiAZ** [monkeytypegame/monkeytype#3648]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Arabic words set all have [diacritics/harakat](https://en.wikipedia.org/wiki/Arabic_diacritics) making the arabic language in monkeytype practically useless. They are NOT part of the arabic alphabet.. no one writes arabic with [diacritics/harakat](https://en.wikipedia.org/wiki/Arabic_diacritics), not even in the most official docuemnts.

Arabic words should be plain word without diacritics. Keeping the diacritics as optional would be optimal, the default should defintly by just plain arabic words without diacritics.

Example:
Currently
   "أَتَمَنَّى",
    "أَثِقْ",
    "الِاثْنَيْنِ",

the default It should be:
    "أتمنى",
    "أثق",
    "الاثنين",

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
Enable lazy mode in the settings to remove diacritics

**Comment by mshwf** [comment]
@Miodec Lazy mode should be enabled by default for Arabic, the current default makes it impossible to use the site to practice Arabic, also this setting should be in the top row of the main page if has to exist at all
