### ISSUE TITLE
Histogram of speed for time 15 and 60 for all users

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3650]

**Comment by mrbrianevans** [comment]
# Feature request
It would be nice to see a distribution of typing speeds of all users. Example from humanbenchmark:
![image](https://user-images.githubusercontent.com/53117772/195842782-eef6c3b1-2909-4655-9853-a7fea0fb3fcb.png)

### Basic idea
Take leaderboard data (eg each users best score for 15 or 60 seconds) and display it in a histogram or distrubtion graph of some kind. 

Shows what percentile of users are at 50wpm, 60wpm ... etc

At the moment the leaderboard says "you are in the top 20% of users" or something, and this would be a way to visualise that. Helps users see if they are above average and by how much.

### Implementation notes
I'm not too sure how this data can be computed or retrieved the DB, so would appreciate a comment from other devs with any ideas of how this could be achieved.

I'm happy to work on implementing this feature.
