### ISSUE TITLE
Typing stops being smooth when opening another tab

### ISSUE THREAD

**Issue by 1netanel** [monkeytypegame/monkeytype#3651]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

paimon

### Current Behavior

When starting to type, if mid typing test I open another tab and search something then come back to MonkeyType it's becomes laggy, like the smooth cursor stops working.

### Expected Behavior

I expect the typing to stay smooth when searching something in another tab and then going back to the typing test.

### Steps To Reproduce

1. Start typing
2. open new tab and google something or enter url
3. go back to MoneyType to keep typing
4. typing becomes not smooth

### Environment

- OS: Windows 10
- Browser: Google Chrome / Firefox
- Browser Version: 106.0.5249.119

**Comment by 1netanel** [comment]
Issue seems to be solevd.

**Comment by Miodec** [comment]
When the tab loses focus browsers will limit the resources available to it. This might cause the test timer to drift (seconds taking longer or shorter than an actual second) - to compensate, the animations will be disabled to limit the amount of resources need as much as possible while trying to keep the test running. If the timer drifts too much the test is automatically stopped. This is working as intended.
