### ISSUE TITLE
Notification Bell with dot shows thick square outline on Safari

### ISSUE THREAD

**Issue by Calihrymn** [monkeytypegame/monkeytype#3658]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

calihrymn

### Account config

{"theme":"lime","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["watermelon","bento","sweden","nautilus","metaverse","dev","striker","fledgling","aether","honey","aurora","miami_nights","8008","mint","strawberry","lavender","grand_prix","luna","lime","ryujinscales","vaporwave","red_dragon","retrocast","terra","miami","dots","fire","bliss","horizon","night_runner","alpine","dracula","trackday","bushido","matcha_moccha","copper","carbon","passion_fruit","ishtar","red_samurai","laser","wavez","menthol","mizu","catppuccin","terminal","rose_pine_moon","chaos_theory","matrix","blueberry_dark","stealth","norse","trance","peach_blossom","rudy","superuser"],"showKeyTips":false,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"underline","paceCaretStyle":"block","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":true,"randomTheme":"fav","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"react","keymapStyle":"staggered","keymapLegendStyle":"blank","keymapLayout":"qwerty","keymapShowTopRow":"never","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"1.0","startGraphsAtZero":false,"showOutOfFocusWarning":false,"paceCaret":"off","paceCaretCustomSpeed":140,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"scatter","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0.2,0.6,0.9,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When a notification is present in the inbox while logged in on Safari, the bell icon has a thick square cutout in the top right.
<img width="150" alt="image" src="https://user-images.githubusercontent.com/43664297/196031418-22ceda0d-4b5b-4387-b1ca-742d062ac976.png">

### Expected Behavior

The bell and dot icons would have no overlap or interference in Safari, and would appear as they do in other browsers.
<img width="131" alt="image" src="https://user-images.githubusercontent.com/43664297/196031437-bd79c033-f567-4aa8-8c3e-f49ab58fd384.png">

### Steps To Reproduce

1. Log into an account on Safari on a Mac
2. Receive a new, unseen notification in the inbox or announcements (i.e. making it onto the Daily Leaderboard the previous day).
3. The bell in the top right will show a visible cutout

### Environment

- OS: macOS Monterey 12.6
- Browser: Safari 
- Browser Version: 16.0 (17614.1.25.9.10, 17614)

### Anything else?

nah, pre simple purely visual bug, not much to it :thumbs

**Comment by Miodec** [comment]
Haha, of course safari doesnt round the outline according to the border radius like every other browser
