### ISSUE TITLE
Make results with funboxes which only affect the site visually eligible for pbs and leaderboards

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3667]

**Comment by Miodec** [comment]
> Should layoutfluid and memory be applied (and every funbox without wordset changing or text altering)?

I guess? Those will slow you down really so i think it would be fine

**Comment by grigoriynikolaev** [comment]
Could you also apply it to "read ahead(easy/hard)"? I use it all the time because otherwise the caret stutters on fast typed letters on my slow laptop.
