### ISSUE TITLE
Gmail logs out when on clearing cookies 

### ISSUE THREAD

**Issue by ArpitMittal468** [monkeytypegame/monkeytype#3668]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

N/A

### Steps To Reproduce

1. Open Incognito tab
2. Log in to Gmail
3. Open monkeytype (refresh 1 time if you want)
4. Open browser dev tools (on monkeytype)
5. go to Application > cookies > clear the cookies
6. Gmail should get logged out

### Environment

- OS: macOs monterey v12.4 (21F79)
- Browser: Brave
- Browser Version: [Version 1.43.88 Chromium: 105.0.5195.68 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by Miodec** [comment]
Cookies will be used to store your token that is used to authenticate requests made by your account. Clearing local site data will remove any memory that you were ever signed in, and sign you out for security.
