### ISSUE TITLE
Banner moves content when hidden in typing mode

### ISSUE THREAD

**Issue by vetusst** [monkeytypegame/monkeytype#3670]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

vetus

### Account config

{"theme":"dark_magic_girl","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#323437","#bd93f9","#bd93f9","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["serika_dark","vscode"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":25,"time":30,"mode":"words","quoteLength":[1],"language":"english","fontSize":1.25,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"0.75","stopOnError":"off","showAllLines":false,"keymapMode":"react","keymapStyle":"staggered","keymapLegendStyle":"uppercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":80,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":95,"showLiveAcc":true,"showLiveBurst":true,"monkey":false,"repeatQuotes":"typing","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Preconditions: 
banner "Update ready - please refresh" is present on the page
![image](https://user-images.githubusercontent.com/76970581/196645447-5c62a4b9-b1d9-485f-befc-214a23ceac98.png)

## Actual result:
Banner is hidden, but still on the page and moves content 
![image](https://user-images.githubusercontent.com/76970581/196646055-47980af3-78a0-42ce-8cda-6a0c3411ada4.png)

## Expected result: 
Banner is hidden and removed from the page, content is not moved
![image](https://user-images.githubusercontent.com/76970581/196646734-3a09ef23-e235-401a-a8af-837eff822ed5.png)

### Steps:
Start typing, when banner is present 

### Environment

- OS: Windows 10 Pro
- Browser: Google Chrome
- Browser Version: 106.0.5249.119 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Banners are just hidden (not reduced in size) when typing to avoid moving the content all the time. This is not a bug.
