### ISSUE TITLE
Unable to start typing test; any keyboard input does not do anything

### ISSUE THREAD

**Issue by euphoria2k** [monkeytypegame/monkeytype#3671]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

AmberStarlight

### Current Behavior

Unable to start typing test; any keyboard input does not do anything other than pressing F5, which restarts the test.
Swapping keyboards or using onboard laptop keyboard does not solve the problem.

### Expected Behavior

Typing any keyboard input should start the typing test.

### Steps To Reproduce

1. Land on monkeytype.com
2. Attempt to start a typing test by typing any keyboard input

### Environment

- OS: Windows 11
- Browser: Microsoft Edge
- Browser Version: 106.0.1370.42 (Official build) (64-bit)

**Comment by Miodec** [comment]
Can you try another browser?

**Comment by krux02** [comment]
I have the exact same problem. I use chromium on Manjaro Linux. I tried using firefox as well, there it works for some reason.

**Comment by Miodec** [comment]
Any extensions installed?

**Comment by euphoria2k** [comment]
> Can you try another browser?

Switching browsers to Firefox solved the problem.

> Any extension installed?

I have three extensions installed on my Edge browser:
1. Vue Devtools
2. Dashlane
3. Google Input Tools

**Comment by Miodec** [comment]
> > Can you try another browser?
> 
> Switching browsers to Firefox solved the problem.
> 
> > Any extension installed?
> 
> I have three extensions installed on my Edge browser:
> 
> 1. Vue Devtools
> 2. Dashlane
> 3. Google Input Tools

Most likely the input tools extension. Test without extensions please.

**Comment by geekyBoogiepop** [comment]
It happens on my end too, using brave in incognito mode (extensions disabled) and the issue still happening.

**Comment by Miodec** [comment]
Any errors in the browser console?

**Comment by geekyBoogiepop** [comment]
Here's the log in incognito mode:
```
monkeytype.637d7910.js:1 loading localStorage config
monkeytype.637d7910.js:1 Analytics unavailable
vendor.2dea3439.js:1 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
f @ vendor.2dea3439.js:1
monkeytype.637d7910.js:1 Analytics unavailable
monkeytype.637d7910.js:1 updating margin
monkeytype.637d7910.js:1 auth state changed, user false
monkeytype.637d7910.js:1 change page test
monkeytype.637d7910.js:1 getting language json
monkeytype.637d7910.js:1 getting language json
monkeytype.637d7910.js:1 Service worker registration succeeded: ServiceWorkerRegistrationactive: ServiceWorker {scriptURL: 'https://monkeytype.com/service-worker.js', state: 'activated', onstatechange: null, onerror: null}backgroundFetch: BackgroundFetchManager {}cookies: CookieStoreManager {}installing: nullnavigationPreload: NavigationPreloadManager {}onupdatefound: nullpaymentManager: PaymentManager {instruments: PaymentInstruments, userHint: ''}periodicSync: PeriodicSyncManager {}pushManager: PushManager {}scope: "https://monkeytype.com/"sync: SyncManager {}updateViaCache: "imports"waiting: null[[Prototype]]: ServiceWorkerRegistration
api.enthusiastgaming.net/scripts/cdn.enthusiast.gg/script/eg-aps/release/eg-aps-bootstrap-v2.0.0.bundle.js?site=monkeytype.com:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.googletagmanager.com/gtm.js?id=GTM-W7WN5QV:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
monkeytype.637d7910.js:1 updating margin
monkeytype.637d7910.js:1 updating margin
monkeytype.637d7910.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'gptAdSlots')
    at monkeytype.637d7910.js:1:198711
    at Generator.next (<anonymous>)
    at monkeytype.637d7910.js:1:196040
    at new Promise (<anonymous>)
    at s (monkeytype.637d7910.js:1:195785)
    at S (monkeytype.637d7910.js:1:198641)
    at monkeytype.637d7910.js:1:197526
(anonymous) @ monkeytype.637d7910.js:1
(anonymous) @ monkeytype.637d7910.js:1
s @ monkeytype.637d7910.js:1
S @ monkeytype.637d7910.js:1
(anonymous) @ monkeytype.637d7910.js:1

```

**Comment by geekyBoogiepop** [comment]
https://user-images.githubusercontent.com/32626891/197873002-ecc812c6-a510-4dc0-a4ac-a5c2c8c747fa.mp4

I'm sorry for the flickering. In the first part of the video, I was trying to type, that's why you see like I'm doing nothing.

**Comment by Miodec** [comment]
So, it works eventually. Maybe the words are not focused? Refresh the page, click somewhere on the page (not on the words) and then click on the words again - can you type then?

**Comment by geekyBoogiepop** [comment]
You can see in the video that it just works when I switch to Firefox. It doesn't work in Brave even after refreshing when website multiple times or clicking outside of the paragraph.

**Comment by Miodec** [comment]
I dont know honestly, im out of any basic debugging ideas. Do you think you could set up the project locally and join the discord server so we can try fix this together?

**Comment by Miodec** [comment]
Yeap, you dont need it anymore

**Comment by Miodec** [comment]
Can you check if its still a problem? Recently I've identified a problem with the cookie popup blocking typing.

**Comment by geekyBoogiepop** [comment]
I'm sorry for not helping debugging the issue before, I didn't have enough time. Getting back to the issue. I've been testing the website everyday since I reported the issue, and noticed that the issue was fixed about a week ago. I didn't report it back because I was thoroughly testing it.

Everything is working fine with the latest version of Brave. Thank you so much for your hard work 🙏❤️
