### ISSUE TITLE
Implement eslint-plugin-unicorn

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3686]
Implement https://github.com/sindresorhus/eslint-plugin-unicorn

**Comment by varunKT001** [comment]
@Miodec I would like to work on this issue. Please assign me.

**Comment by Miodec** [comment]
> @Miodec I would like to work on this issue. Please assign me.

Sorry, its huge change that will affect the whole project - i want to do it myself.

**Comment by varunKT001** [comment]
Okay, fine 👍
