### ISSUE TITLE
Very low accuracy with Dotterel on Android

### ISSUE THREAD

**Issue by MarkoSchuetz** [monkeytypegame/monkeytype#3690]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

I use MonkeyType in two scenarios:
- on laptop with steno keyboard through Plover
- on tablet with steno keyboard through Dotterel.
With Plover the keyboard uses Gemini PR and with Dotterel it uses NKRO.
Using the tablet I see much lower accuracy reported than when using the laptop: on the laptop MonkeyType reports about 90% and doing the same test on the tablet it will report below 30%.

### Expected Behavior

I would expect about the same accuracy on both.

### Environment

- OS: Android on tablet, Linux on laptop
- Browser: Brave on tablet, Firefox on laptop
- Browser Version: Brave 1.14.114, Firefox 105.0.3

**Comment by Miodec** [comment]
I dont have an android device so im honestly stuck here.

I do know that android does some super funky stuff with keyboard events, and adding a steno-like keyboard on top probably doesn't help things here.

**Comment by nimble0** [comment]
The problem seems to be because Dotterel outputs blocks of text, a bit like pasting text, instead of generating key press events (like Plover).

Specifically, it causes an issue when a word is prefixed by a space. Manually writing the spaces gives 100% accuracy:
```
"say"
" "
"high"
" "
"between"
" "
"few"
```
But this gives a low accuracy:
```
"say"
" high"
" between"
" few"
```

**Comment by Miodec** [comment]
Actually, this happens with swipe typing as well (on iOS atleast). Spacing in between swipes gives 100% accuracy, but letting the swipe prefix the space gives low accuracy. 

Is it the same on Android with a swipe keyboard?

**Comment by nimble0** [comment]
I don't see this issue with swiping in Gboard.

**Comment by Miodec** [comment]
Hey, i fixed the accuracy calculation for swipe typing. Could you check if Dotterel is fixed?

**Comment by nimble0** [comment]
Looks completely fixed with Dotterel.

**Comment by Miodec** [comment]
Nice. Let me know if you run into any other issues
