### ISSUE TITLE
Pace caret in korean doesn't consider compose characters

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3693]
In Korean, the pace caret will go much quicker than it should, because it just goes character by character. Each character is built using multiple keypresses - this needs to be considered when moving the pace caret.

This might be difficult

**Comment by Miodec** [comment]
I just gave it more thought - this is fine. The extra keystrokes used in character composition don't count towards the final speed. So considering them in the pace caret movement wouldnt make sense.
