### ISSUE TITLE
ipv4 and ipv6 funboxes

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3694]
add funboxes which randomly generate ipv4s and ipv6s. Punctuation mode adds CIDRs

**Comment by egorguslyan** [comment]
https://github.com/egorguslyan/monkeytype/tree/ip

**Comment by Miodec** [comment]
> https://github.com/egorguslyan/monkeytype/tree/ip

Can you split it into v4 and v6?

**Comment by egorguslyan** [comment]
Done

**Comment by rizwanmustafa** [comment]
@Miodec is this feature completed?

**Comment by Miodec** [comment]
> @Miodec is this feature completed?

Needs #3578 merged first
