### ISSUE TITLE
No option to hide warning/bad banners

### ISSUE THREAD

**Issue by deerawj** [monkeytypegame/monkeytype#3697]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

deerawj

### Current Behavior

My internet connection is often very slow. Thus a banner appears reading,

> Looks like the server is experiencing maintenance or some unexpected down time.
Check the [status page](https://monkeytype.instatus.com/) or [Twitter](https://twitter.com/monkeytypegame) for more information.

While this seems to be expected behaviour, due to the lack of an option to hide it, the banner can be very intrusive especially since it stacks with other banners (such as a promotional banner). Even though the banner is hidden during the typing test. It still leaves some padding at the top and overall reducing the elegant feel of the site.

You can reproduce this by enabling throttling under the network tab in the developer tools (tested only in firefox). "Good 2G" option with Download 450Kbps, Upload 150Kbps, latency 150ms worked the most consistently.

### Expected Behavior

An option to hide the banner similar to how notices (pop ups) can be hid or an option to permanently hide these banners in the settings for users who get them often.

### Steps To Reproduce

# Only tested in firefox
1. Open developer tools (by right clicking and choosing inspect)
2. Goto the networks tab
3. Click No throttling and select the "Good 2G" option
4. Reload the site and cache (Shift reload)
5. You will see the banner on the top.

### Environment

- OS: Linux (Pop Os)
- Browser: Mozilla Firefox for Ubuntu canoical - 1.0
- Browser Version: 104.0 (64-bit)

**Comment by Miodec** [comment]
Fixed in 5cef5d0cbcc4710f6bc6940db5c84d52de3dab4b
