### ISSUE TITLE
"ctrl + backspace" doesn't work with some special characters.

### ISSUE THREAD

**Issue by MostafaEwis** [monkeytypegame/monkeytype#3715]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

mastf

### Current Behavior

Using the shortcut "ctrl + backspace" doesn't work when typing special characters listed below: 
1. =
2. +  (plus sign)
3. ^
4. $
5. `
6. ~

These characters work as if they have spaces before and after them thus if the shortcut were used in a word like "test======(((((((((", the shortcut will remove all of the parentheses then remove equal signs one by one then remove all characters in "test" at once.

### Expected Behavior

It is expected that if multiple characters of any type were typed in a single word with no spaces, they will be removed if the shortcut "ctrl + backspace" was used.

### Steps To Reproduce

1. Type one of the characters mentioned in the "Current Behavior" section. 
2. Try to use the shortcut mentioned.

### Environment

- OS: Windows 11
- Browser: Microsoft Edge
- Browser Version: 107.0.1418.26 (Official build) (64-bit)

### Anything else?

https://user-images.githubusercontent.com/64862002/199197187-34f05754-ca29-4c17-ad49-8a0f41a3ab79.mp4

**Comment by Miodec** [comment]
What is your layout emulator setting set to?

**Comment by MostafaEwis** [comment]
It is off, and the issue doesn't stop when using a layout.

**Comment by Miodec** [comment]
When layout emulator is off it will behave just like a normal system input field. Ctrl + backspace behavior should be the same as any other input field.

**Comment by MostafaEwis** [comment]
ok, cool, I'll close the issue since this is not really a bug, thanks for your help.
