### ISSUE TITLE
incorrect social media username checking

### ISSUE THREAD

**Issue by ray-1337** [monkeytypegame/monkeytype#3729]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

[goodfaith](https://monkeytype.com/profile/goodfaith)

### Account config

{"theme":"metaverse","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":25,"time":15,"mode":"time","quoteLength":[0],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":true,"showLiveBurst":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

it gives you an error while changing your github username that had a dash or underscore characters on it

> "socialProfiles.github" must only contain alpha-numeric characters (ray-1337)

### Expected Behavior

the profile should be able to saved even the github username had a dash/underscore characters on it

### Steps To Reproduce

1. Go to your Monkeytype profile
2. Click **Edit Profile**
3. If you have a dash or underscore characters on your GitHub username, try to change your GitHub username

### Environment

- OS: Windows 10
- Browser: Brave
- Browser Version: Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)

### Anything else?

https://github.com/monkeytypegame/monkeytype/blob/master/backend/src/api/routes/users.ts#L466

**Comment by TamasRaj** [comment]
Hi @Miodec 
Your recent commit 310db635977da2c04419860ae42340f9e46ec23a, it is checking for twitter and github usernames to be alphanumeric.
But according to github policies hypen is allowed in the user name.

**Comment by TamasRaj** [comment]
Hi @Miodec 
Should 310db635977da2c04419860ae42340f9e46ec23a these changes be reverted?
