### ISSUE TITLE
Make sure media queries are working correctly even if browser font size is increased

### ISSUE THREAD

**Issue by satelerd** [monkeytypegame/monkeytype#3745]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

Sateler

### Account config

{"theme":"blueberry_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":25,"time":60,"mode":"time","quoteLength":[0,1,2,3],"language":"spanish","fontSize":2,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":true,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"average","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":false,"chartStyle":"scatter","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":true,"showAverage":"both","tapeMode":"off"}

### Current Behavior

The ui/components of the page is not aligned with the screen. 
I mean, everything is shifted to the right, as seen in the screenshot.

The page was displaying correctly until I noticed an alert at the top that said there was an update that needed to reload the page... once that was done, I realized there was a bug about how the components where aligned on the page.

I think the problem may be with the `<div id="centerContent" class="" style="opacity: 1; padding-top: 40px;">`

![Captura de pantalla 2022-11-14 175654](https://user-images.githubusercontent.com/62968964/201763954-00fafcd8-b8c2-4cff-a45b-e915e1315b31.png)

### Expected Behavior

All the info should be centered on the screen... 
On incognito mode it is working correctly:

![image](https://user-images.githubusercontent.com/62968964/201765282-816e86c4-df8d-401b-8d28-6ee4ffe3149d.png)

### Steps To Reproduce

Just having the landing page logged to an account (or at least with my account)

### Environment

- OS: Windows 11
- Browser: Google Chrome
- Browser Version: Versión 107.0.5304.107 (Build oficial) (64 bits)

**Comment by Miodec** [comment]
Can you check if this still happens after you login in incognito?

**Comment by satelerd** [comment]
It does (but only if I'm logged in)

**Comment by Miodec** [comment]
Can you check if this happens without extensions?

**Comment by satelerd** [comment]
The same...

but, I just realized that the problem has to do (or can be modified) with the color theme; when I'm logged in (with or without incognito) and I select the "8008" theme it looks fine, but when I select the "80s after dark" theme it's misaligned from the center. 
(this happen with lots of themes)

![image](https://user-images.githubusercontent.com/62968964/201788157-cf1388b4-748a-4140-9041-79926c6ae6ba.png)
![image](https://user-images.githubusercontent.com/62968964/201788176-55022174-11d7-40cf-99e1-d0842db987cc.png)

**Comment by Miodec** [comment]
Did you change your font size settings in the browser?

**Comment by satelerd** [comment]
I did change the font size on the monketype settings, but now I change it back to default and the problem still remains.

I think the bug has to do with the `<div id="centerContent" ... >` because of this:

- Without loging to my account (working properly)
![image](https://user-images.githubusercontent.com/62968964/202805893-d6c8287e-6754-4146-b3e2-47b8bc7f5b62.png)

- With my account (bugged)
![image](https://user-images.githubusercontent.com/62968964/202805955-498d445e-a69e-47ef-9540-99f06546ebf0.png)

**Comment by Miodec** [comment]
I meant browser settings, not monkeytype settings

**Comment by Miodec** [comment]
Yeap, looks like i can reproduce the problem by setting the browser font size to large. You can fix this by increasing the page width in monkeytype settings or decreasing the font size back to medium in browser settings.

**Comment by satelerd** [comment]
OOOH that´s awesome, thanks so much for the help!

**Comment by satelerd** [comment]
ups, wrong button...

In the next few days I will be trying to contribute and solve this problem
