### ISSUE TITLE
Can't type letters with accent mark.

### ISSUE THREAD

**Issue by roco3d** [monkeytypegame/monkeytype#3748]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

sinewave_cl

### Account config

{"theme":"night_runner","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["night_runner"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":true,"numbers":false,"words":50,"time":60,"mode":"time","quoteLength":[1],"language":"spanish","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"spanish_qwerty","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

Can't type letters with an accent mark (á é í ó ú) required for typing test in spanish. Both keystrokes required to type any of these are registered indepently and not as one unique letter.

### Expected Behavior

Combination of two keys, ´ and a vowel, should type the required accented vowel.

### Steps To Reproduce

Change the language to spanish and try to type any of theese: á é í ó ú

### Environment

- OS: Windows 10
- Browser: Edge
- Browser Version: Version 107.0.1418.42 (Official build) (64-bit)

**Comment by Miodec** [comment]
Be sure to disable layout emulator in the settings. Layout emulation is pretty basic and doesn't support compose / dead keys.

**Comment by roco3d** [comment]
> Be sure to disable layout emulator in the settings. Layout emulation is pretty basic and doesn't support compose / dead keys.

Thank you very much, it works.
