### ISSUE TITLE
Move commandline to the side when chosing a theme

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3750]

**Comment by Miodec** [comment]
Decided to just remove the background

**Comment by moanatari** [comment]
Yes, by removing the opacity you can see the general atmosphere a little better.
But show a small extract of the text, which is the heart of the site.
See how the text is when it is not typed or typed or with mistakes, how is the text bar.
Even the end screen with the graph and the statistics.
That's what I imagined when I proposed to see what was behind the list of themes.
![image](https://user-images.githubusercontent.com/10980077/202502220-e1f90f17-e4fc-43a0-960c-b2f8b4720adf.png)
