### ISSUE TITLE
Blind mode setting is not highlighting 'On' option correctly

### ISSUE THREAD

**Issue by danielschristian** [monkeytypegame/monkeytype#3760]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

On the setting page, the 'Blind mode' setting is defaulted to off. When looking/hovering at the 'On' button, the text does not appear. The <button> element is space character.
![image](https://user-images.githubusercontent.com/97717621/202862791-b6a80d97-eb63-4c51-8a21-ffbd9a4078ea.png)

### Expected Behavior

On button text should be visible like other settings

### Steps To Reproduce

1. Go to setting page
2. Navigate the blind mode option

### Environment

- OS: Windows 10
- Browser: Firefox
- Browser Version: 107.0

**Comment by Miodec** [comment]
Not a bug, button is "blind"
