### ISSUE TITLE
Change min wpm to min speed, live wpm to live speed

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3785]
- Make sure config gets converted correctly
 - Update ui
 - Add aliases to the commandline to make sure people can still find the settings
 - Consider changing "always show cpm" setting to "use cpm" or something else

**Comment by abhinandanwadwa** [comment]
Hey, I'd like to work on this issue

**Comment by Miodec** [comment]
> Hey, I'd like to work on this issue

Go for it

**Comment by Miodec** [comment]
@abhinandanwadwa any updates?

**Comment by abhinandanwadwa** [comment]
Hey @Miodec, do i just have to change the word `min wpm` to `min speed` and `live wpm` to `live speed`?

**Comment by Miodec** [comment]
Yeah, also make sure that the backend will accept both for a short duration of time. And that if the database config is still in the old format the frontend can handle that.

**Comment by Miodec** [comment]
Also change pace caret speed to cpm.

**Comment by afrozkhan12** [comment]
hey, I can solve this problem, can I go for it?

**Comment by tahamandviwala4** [comment]
hey, I would like to solve this problem, can I go for it?

**Comment by tahamandviwala4** [comment]
Hey, I would like to work on this problem, can I go for it ?

**Comment by Miodec** [comment]
@afrozkhan12 unassigning due to inactivity.

Assigning @tahamandviwala4

**Comment by Deepanshu-in** [comment]
Hey @Miodec can I go for it?

**Comment by Miodec** [comment]
Unassigning due to inactivity
