### ISSUE TITLE
Using funbox still prevents you from setting a PB

### ISSUE THREAD

**Issue by grigoriynikolaev** [monkeytypegame/monkeytype#3787]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

anikavoin

### Account config

{"theme":"bliss","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":120,"mode":"words","quoteLength":[-2],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"read_ahead_easy","confidenceMode":"off","indicateTypos":"replace","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Comic_Sans_MS","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"on","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":true,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

#3667 
I've seen that issue about making funbox's results eligible for PB and leaderboards was marked as completed. So I went to test it and it still doesn't count for me. At least "easy read ahead" mod. Haven't checked other modes, because yknow, it requires you to set a PB.

### Environment

- OS: Debian testing
- Browser: Firefox
- Browser Version: 91.10.0esr (64-bit)

### Anything else?

![Screenshot 2022-12-01 at 01-49-32 Monkeytype](https://user-images.githubusercontent.com/47868839/204886615-da0bbe5b-1668-4b0f-a367-c3c70bd53c50.png)
![2022-12-01 01-52-22](https://user-images.githubusercontent.com/47868839/204886623-62723422-4cfb-4e9f-8c0d-449179ba4c21.png)

**Comment by Miodec** [comment]
Looks like i forgot to deploy the server side code. Should be good now.

**Comment by grigoriynikolaev** [comment]
Yes, it works now. Thank you.
