### ISSUE TITLE
css fails to load on webkit based browsers, clearing the account cache is the only way it becomes usable again

### ISSUE THREAD

**Issue by svk-works** [monkeytypegame/monkeytype#3794]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account config

{"theme":"dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["bliss","olivia","carbon","rgb","serika_dark","paper","dark"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"tab","punctuation":false,"numbers":false,"words":1,"time":15,"mode":"words","quoteLength":[3],"language":"english","fontSize":1.25,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"colemak_dhv","keymapShowTopRow":"layout","fontFamily":"Operator_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.1","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":false,"chartStyle":"scatter","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

site fails to load, and i manually need to clear the cache everytime

### Expected Behavior

site should load

### Environment

- OS: MacOS Ventura
- Browser: Orion, Safari
- Browser Version: latest

### Anything else?

<img width="1440" alt="SCR-20221202-v5z-2" src="https://user-images.githubusercontent.com/59787884/205346186-004ea1c0-4633-4098-9b06-f4f227a20b2c.png">

**Comment by Miodec** [comment]
Have you tried clicking the reinstall button?

**Comment by svk-works** [comment]
> Have you tried clicking the reinstall button?

I did, and as I mentioned it logs me out but manages to open correctly.

**Comment by svk-works** [comment]
> I just deployed a new version, can you check if everything is working now?

Yay, it's working fine now!!
Thank you ☺️☺️
