### ISSUE TITLE
Large font size and long words cause the words to extend past the bottom of the typing test wrapper making the caret invisible

### ISSUE THREAD

**Issue by YummyOreo** [monkeytypegame/monkeytype#3805]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

YummyOreo

### Account config

{"theme":"gruvbox_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#000000","#bb86fc","#bb86fc","#7f7f7f","#363636","#f0efe6","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["gruvbox_dark","night_runner"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"tab","punctuation":false,"numbers":false,"words":1,"time":15,"mode":"time","quoteLength":[-3],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"block","paceCaretStyle":"underline","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"below","timerStyle":"bar","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"react","keymapStyle":"staggered","keymapLegendStyle":"dynamic","keymapLayout":"dvorak","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":60,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":97,"showLiveAcc":false,"showLiveBurst":false,"monkey":true,"repeatQuotes":"typing","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"max","customBackgroundFilter":[0,0,2,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When you get to a line that is bigger than the box can hold, and there is no space, it overflows, but does not scroll so your cursor gets hidden. 

### Expected Behavior

It scrolls down or resizes the window thing to show the lines.
Or 
`Show all lines` gets set to false, this happens if you set the text manually.

### Steps To Reproduce

1. Set the funbox to "Look at me. I am the developer now."
2. Type. The place where i saw this happen is just after the No Javascript section
3. Observe

### Environment

- OS: Chrome Os
- Browser: Chrome
- Browser Version: 107.0.5304.110 (Official Build) (64-bit)

### Anything else?

![Screenshot 2022-12-05 11 28 00 AM](https://user-images.githubusercontent.com/76080854/205704890-ca13e707-56fd-4401-ae14-b82281aadb6a.png)

I think this is because I have `Show all lines` to false. But it still should work

**Comment by Miodec** [comment]
This looks like its related to font size, not show all lines

**Comment by Miodec** [comment]
Temporary fix is to lower the font size

**Comment by YummyOreo** [comment]
> Temporary fix is to lower the font size
> 
> 

Yea, another thing is if you try to replicate this with a custom text, it will just show all the lines.
