### ISSUE TITLE
Move large live wpm down if quick tab is disabled

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3806]

**Comment by Miodec** [comment]
@abhinandanwadwa Do you have anything? Need help?

**Comment by abhinandanwadwa** [comment]
Hey @Miodec, I've tried to fix the issue, but i need help with detecting if the quick tab is disabled or not.

**Comment by Miodec** [comment]
You can check the `Config` object for `quickRestart != "off"`
