### ISSUE TITLE
Personal Best Speed Improvement Tooltip Shows Incorrect Value

### ISSUE THREAD

**Issue by UnrealApex** [monkeytypegame/monkeytype#3836]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

UnrealApex

### Account config

{"theme":"miami_nights","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#f5f5f5","#0171cd","#4ddb47","#dd51ad","#000000","#0171cd","#4ddb47","#42ba3b","#4ddb47","#42ba3b"],"favThemes":["8008","rgb","matrix","paper","serika_dark","onedark","gruvbox_dark","trance","fire","aurora","dark","miami_nights","80s_after_dark","luna"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"tab","punctuation":false,"numbers":false,"words":10,"time":60,"mode":"time","quoteLength":[0],"language":"english","fontSize":2.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"underline","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"4","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":150,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"scatter","minWpm":"off","minWpmCustomSpeed":50,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":50,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"both","tapeMode":"off"}

### Current Behavior

When achieving a new personal best, the tooltip value that shows how much your personal best has increased does not increase; it is just zero(`+0`):
![image](https://user-images.githubusercontent.com/79121360/207947159-684215fd-e899-486f-9d43-694d15746a39.png)

### Expected Behavior

The number should be the WPM of the new personal best minus the WPM of the old personal best.

### Steps To Reproduce

1. Get a personal best
2. hover over the "Crown" icon
3. see error

### Environment

- OS: ChromeOS
- Browser: Google Chrome
- Browser Version: 108.0.5359.111 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Is it still an issue? Can't reproduce.

**Comment by UnrealApex** [comment]
Hmm, I guess perhaps it is just a glitch. Not able to reproduce with a test account.

**Comment by unrealapex** [comment]
Does this happen after reloading the page or in a private browsing window?
