### ISSUE TITLE
Result Data Doesn't Make Sense

### ISSUE THREAD

**Issue by CyrilSharma** [monkeytypegame/monkeytype#3848]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

csharma

### Account config

{"theme":"modern_dolch","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"words","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"text","colorfulMode":false,"randomTheme":"off","timerColor":"black","timerOpacity":"0.25","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":true,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When I complete a test I get an error stating: "Result data doesn't make sense". This error does not show up when I use MonkeyType on Safari. The result data (posted below, excluding UID and Hash) seems pretty normal, so I'm not sure what could be causing it.

{
    "result": {
        "wpm": 89.2,
        "rawWpm": 106.19,
        "charStats": [
            42,
            3,
            1,
            0
        ],
        "acc": 90,
        "mode": "words",
        "mode2": "10",
        "punctuation": false,
        "numbers": false,
        "lazyMode": false,
        "timestamp": 1671667040367,
        "language": "english",
        "restartCount": 2,
        "incompleteTests": [
            {
                "acc": 62.5,
                "seconds": 1.03
            },
            {
                "acc": 72.73,
                "seconds": 1.4
            }
        ],
        "incompleteTestSeconds": 2.43,
        "difficulty": "normal",
        "blindMode": false,
        "tags": [],
        "keySpacing": [
            5651.3
        ],
        "keyDuration": [
            125.2,
            0.8,
            74.3,
            84.3,
            67.9,
            14,
            113.8,
            86,
            113.7,
            321.7,
            163.9,
            102.4,
            165,
            35.4,
            67,
            119.5,
            43.6,
            52.7,
            144.6,
            76.8,
            115.3,
            104.5,
            482.8,
            149.3,
            60.4,
            160.6,
            52.2,
            170.5,
            28.9,
            86.3,
            96.9,
            103.7,
            70.2,
            70.9,
            191.5,
            118,
            68.5,
            39.4,
            71.7,
            133.4,
            21.5,
            173.6,
            28.1,
            79.1,
            199.8,
            468.2,
            99.2,
            108.6
        ],
        "consistency": 69.28,
        "keyConsistency": 0,
        "funbox": "none",
        "bailedOut": false,
        "chartData": {
            "wpm": [
                108,
                78,
                68,
                84,
                86,
                89
            ],
            "raw": [
                126,
                104,
                108,
                96,
                96,
                78
            ],
            "err": [
                0,
                5,
                0,
                0,
                0,
                0
            ]
        },
        "testDuration": 5.65,
        "afkDuration": 0,
        "smoothConsistency": 85.69,
        "wpmConsistency": 85.81,
        "uid": "q35DPGxCLKemDgSYKAbtHN9tnXh1",
        "hash": "bd167059064ff4dbd41405b2772f9f1edf377f5e"
    }
}

### Environment

- OS: 
- Browser: Brave Browser
- Browser Version:

**Comment by samyosm** [comment]
Perhaps you could delete all cookies, clear localStorage, and sessionStorage because it seems to be a browser related issue.

**Comment by Miodec** [comment]
Still an issue?

**Comment by CyrilSharma** [comment]
It’s still an issue after clearing all cookies, local storage, etc. and it’s an issue only present on Brave, although I’ve only tried Brave and Safari.

**Comment by Miodec** [comment]
Your keyspacing data for some reason only has one entry. It should have spacing for each keypress. Are you using some sort of keyboard rebinding software? Can you check Chrome and Firefox?

**Comment by CyrilSharma** [comment]
Not sure exactly what the issue was, but removing all extensions and restarting the browser seems to have made it go away.
