### ISSUE TITLE
Send feedback to user about their report

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3909]

**Comment by Miodec** [comment]
Maybe store accepted and denied reports

**Comment by mohammadsaadraza** [comment]
Can you elaborate more on this? 

If I can, I'd like to make a PR on this.

**Comment by Miodec** [comment]
Sorry, you can't work on this issue because its a admin-panel specific. Mainly made this issue for myself so I don't forget ;D

**Comment by mohammadsaadraza** [comment]
okay. ill browse some others.
