### ISSUE TITLE
Score Reset

### ISSUE THREAD

**Issue by Doob123123** [monkeytypegame/monkeytype#3950]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

Dabman2392

### Account config

{"theme":"red_dragon","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#000000","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["dark"],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"tab","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"time","quoteLength":[0],"language":"english","fontSize":2.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"qwerty","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"react","keymapStyle":"staggered","keymapLegendStyle":"dynamic","keymapLayout":"qwerty","keymapShowTopRow":"never","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"5","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","chartAccuracy":false,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":120,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":true,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":true,"showLiveBurst":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":120,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"letter"}

### Current Behavior

I had a 15 second score of 160ish words per minute, and it just got changed to 126 words per minute, what I am thinking is going on is that I did enough tests that it deleted the 160 wpm score to make room for the 126 word per minute score.

### Expected Behavior

My expected behaviour was for it to save my 160 wpm score, that bit is kind of self explainatory.

### Steps To Reproduce

I am not sure how to reproduce this

### Environment

- OS: Chrome
- Browser: Chrome
- Browser Version: Version 102.0.5005.194 (Official Build) (64-bit)

### Anything else?

none

**Comment by Miodec** [comment]
I dont delete any results from the database. When did you get the 160 wpm?

**Comment by Doob123123** [comment]
4-ish months ago, its like it never existed

**Comment by Doob123123** [comment]
I figured you dont delete things from the database, but I am not sure what caused this to happen.

**Comment by Miodec** [comment]
I checked the database and you only have 3 results that are over 160:

 - Zen mode 231wpm
 - Zen mode 179wpm
 - Words 10 163wpm

Im going to assume that you are either misremembering that it was a time 15 when in fact it was a words 10, you were signed in to the wrong account or not signed in at all. Sorry, but 4 month old results don't just disappear like that.

**Comment by Doob123123** [comment]
I suppose that is possible. Thank you.
