### ISSUE TITLE
data not getting saved

### ISSUE THREAD

**Issue by smeet07** [monkeytypegame/monkeytype#3956]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

smeet07

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":15,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

The data is not getting saved to my account . I tried logging out and logging back again but the problem persists.
![image](https://user-images.githubusercontent.com/81572407/215172146-13a36455-4fc0-438a-95ca-f0129064f3a3.png)

### Expected Behavior

The data should get saved to my monkeytype account

### Environment

- OS: windows 11
- Browser: google chrome 
- Browser Version: 109.0.5414.76 (Official Build) (64-bit)

**Comment by anzepintar** [comment]
Tags are not showing for me

**Comment by Miodec** [comment]
> Test in incognito when logged in. This was a problem earlier today but was fixed. Try clearing your local website data so that your browser pulls the latest code from the server.

What about this?

**Comment by anzepintar** [comment]
> > Test in incognito when logged in. This was a problem earlier today but was fixed. Try clearing your local website data so that your browser pulls the latest code from the server.
> 
> What about this?

It is the same in incognito, in both firefox and edge

**Comment by Miodec** [comment]
What alert message do you get when you shift click the version number in the bottom right?

**Comment by anzepintar** [comment]
I get `2023.01.28_19.51.26a19a87b`

**Comment by Miodec** [comment]
Try again, i just deployed a version. It should also fix the missing tags thing

**Comment by smeet07** [comment]
It's working now
