### ISSUE TITLE
Subpages not loading 

### ISSUE THREAD

**Issue by brentspine** [monkeytypegame/monkeytype#3957]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

Brentspine

### Account config

Can't access the page but retrieved the response in the Network tab:
```
{
    "message": "Configuration retrieved",
    "data": {
        "_id": "63c48844bd098f2ba57ff1d9",
        "uid": "WH5GZ1LaINUc6mj0ZZJne2f3Nam2",
        "config": {
            "time": 15,
            "punctuation": false,
            "numbers": false,
            "mode": "words",
            "quoteLength": [0, 1, 2, 3],
            "ads": "result",
            "alwaysShowCPM": false,
            "alwaysShowDecimalPlaces": false,
            "alwaysShowWordsHistory": false,
            "autoSwitchTheme": false,
            "blindMode": false,
            "britishEnglish": false,
            "burstHeatmap": false,
            "capsLockWarning": true,
            "caretStyle": "default",
            "chartAccuracy": true,
            "chartStyle": "line",
            "colorfulMode": false,
            "confidenceMode": "off",
            "customBackground": "",
            "customBackgroundFilter": [0, 1, 1, 1, 1],
            "customBackgroundSize": "cover",
            "customLayoutfluid": "qwerty#dvorak#colemak",
            "customTheme": false,
            "customThemeColors": ["#323437", "#e2b714", "#e2b714", "#646669", "#2c2e31", "#d1d0c5", "#ca4754", "#7e2a33", "#ca4754", "#7e2a33"],
            "difficulty": "normal",
            "favThemes": [],
            "flipTestColors": false,
            "fontFamily": "Roboto_Mono",
            "fontSize": 1.5,
            "freedomMode": false,
            "funbox": "none",
            "hideExtraLetters": false,
            "highlightMode": "letter",
            "indicateTypos": "off",
            "keymapLayout": "overrideSync",
            "keymapLegendStyle": "lowercase",
            "keymapMode": "off",
            "keymapShowTopRow": "layout",
            "keymapStyle": "staggered",
            "language": "english",
            "layout": "default",
            "lazyMode": false,
            "minAcc": "off",
            "minAccCustom": 90,
            "minBurst": "off",
            "minBurstCustomSpeed": 100,
            "minWpm": "off",
            "minWpmCustomSpeed": 100,
            "monkey": false,
            "monkeyPowerLevel": "off",
            "oppositeShiftMode": "off",
            "paceCaret": "off",
            "paceCaretCustomSpeed": 100,
            "paceCaretStyle": "default",
            "pageWidth": "125",
            "playSoundOnClick": "off",
            "playSoundOnError": false,
            "quickEnd": false,
            "quickRestart": "off",
            "randomTheme": "off",
            "repeatQuotes": "off",
            "repeatedPace": true,
            "showAllLines": false,
            "showAverage": "off",
            "showKeyTips": true,
            "showLiveAcc": false,
            "showLiveBurst": false,
            "showLiveWpm": false,
            "showOutOfFocusWarning": true,
            "showTimerProgress": true,
            "singleListCommandLine": "manual",
            "smoothCaret": true,
            "smoothLineScroll": false,
            "soundVolume": "0.5",
            "startGraphsAtZero": true,
            "stopOnError": "off",
            "strictSpace": false,
            "tapeMode": "off",
            "theme": "8008",
            "themeDark": "serika_dark",
            "themeLight": "serika",
            "timerColor": "main",
            "timerOpacity": "1",
            "timerStyle": "mini",
            "words": 10
        }
    }
}
```

### Current Behavior

The subpages don't load when I'm logged in.

### Expected Behavior

Well the website should work as intended

### Steps To Reproduce

I don't exactly know, but it might have something to do with me changing the window size while being on the page. 

I'm currently testing how I can achieve smooth transitions between websites and a website where the client doesn't have to reload the header and footer for every page (By using AJAX to request subcontent).

### Environment

- **OS:** Windows 11 Version 22H2 (Build 22621.1105)
- **Browser:** Brave
- **Browser Version:**  1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Any errors in the console? Can you send some screenshots or images? Does it happen when logged out?

**Comment by andreasbruckmeier** [comment]
I`m not sure if i run into the same or an other issue, but since today my subpages are not loading too.
I found out that is has to do with the selected theme. I have 8008 selected as has @brentspine. When I change the theme to bliss for example using the toogle on the bottom of the page and reload, then it works again.

Error from console is
`VM609 op.js:1 Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '.pageSettings .section.themes .theme[theme=8008]' is not a valid selector.
    at a6.<computed> [as querySelector] (https://tagan.adlightning.com/enthusiastgaming/op.js:1:39866)
    at b (https://monkeytype.com/js/monkeytype.c4a55166.js:1:567718)
    at Object.<anonymous> (https://monkeytype.com/js/monkeytype.c4a55166.js:1:572076)
    at Generator.next (<anonymous>)
    at r (https://monkeytype.com/js/monkeytype.c4a55166.js:1:566922)`

**Comment by Miodec** [comment]
Both issues should be fixed now

**Comment by brentspine** [comment]
Yes, works fine on my end
