### ISSUE TITLE
Lost saved texts

### ISSUE THREAD

**Issue by m7mdtiger** [monkeytypegame/monkeytype#3958]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Not being able to retrieve saved texts or store new texts

### Expected Behavior

Store new texts or retrieve my saved texts

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
Can you send some screenshots? Is it that your texts don't show or clicking the button does nothing.

Have you tested incognito?

**Comment by m7mdtiger** [comment]
The buttons are working fine.. But when I click on my saved texts, I don't get the text.. Yes, I've tested incognito. And I've asked a friend and it's the same for him too. 

I select a saved text:
![b1](https://user-images.githubusercontent.com/8851759/215204027-bc71c90b-a87b-4641-95bd-2568cca85036.png)

But I don't get the text back and instead I get this again:
![b2](https://user-images.githubusercontent.com/8851759/215204200-61dc5ed1-98ca-4864-9a7e-ac50ca4d95ef.png)

**Comment by Miodec** [comment]
What alert message do you get when shift click the version number in the bottom right?

**Comment by m7mdtiger** [comment]
> What alert message do you get when shift click the version number in the bottom right?

2023.01.27_17.37.e94364f26

**Comment by Miodec** [comment]
Ok, found a potential fix. Just pushed an update. Make sure the version number in that alert changed and please test again.

**Comment by m7mdtiger** [comment]
> Ok, found a potential fix. Just pushed an update. Make sure the version number in that alert changed and please test again.

Perfect, thank you :hearts:

**Comment by Miodec** [comment]
Let me know if it works

**Comment by m7mdtiger** [comment]
> Let me know if it works

Yes it works.. Thank you : )
