### ISSUE TITLE
Add strong types to later queue

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#3966]

**Comment by gaurav7019** [comment]
I would like to contribute to this. Can you please add some more description? I am just starting out with this project and setting up the repo locally.

**Comment by Miodec** [comment]
> I would like to contribute to this. Can you please add some more description? I am just starting out with this project and setting up the repo locally.

If you're just starting off this might not be the issue for you.

Basically, currently the later queue is using `any` for its context parameter. #3964 is basically the same code as later queue, but for email - that has examples of strong types for the context.

Let me know if it makes sense.
