### ISSUE TITLE
Binary funbox mode

### ISSUE THREAD

**Issue by Miodec** [monkeytypegame/monkeytype#3993]
### Discussed in https://github.com/monkeytypegame/monkeytype/discussions/3992

<div type='discussions-op-text'>

<sup>Originally posted by **WriteThatDown** February 14, 2023</sup>
It would be cool to make a binary funbox mode, for those old-school programmers. It would be like regular Monkeytype, except with each letter replaced with its ASCII binary equivalent.</div>

**Comment by robsassack** [comment]
I can try working on this, I have already made some progress:
![image](https://user-images.githubusercontent.com/91514586/219883202-66051ffa-6b51-4b30-a80f-77cd571d090d.png)
