### ISSUE TITLE
RGB theme's label colors for daily leaderboard placement not synced up when appearing at a later score in the session

### ISSUE THREAD

**Issue by Rekkonnect** [monkeytypegame/monkeytype#4030]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

Rekkon

### Account config

{"theme":"rgb","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"time","quoteLength":[3],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"roboto_mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"6","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":false,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":true,"strictSpace":false,"minAcc":"off","minAccCustom":76,"showLiveAcc":true,"showLiveBurst":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"both","tapeMode":"off"}

### Current Behavior

The daily leaderboard text's RGB colors are not synchronized with other texts

### Expected Behavior

Despite the label appearing at a later time, it should be synced up with all the others from a common source.

### Steps To Reproduce

1. Use the RGB theme
2. Make a score that does not get it to the daily leaderboard
3. Make another score that makes it to the leaderboard, causing the label for the leaderboard placement to show  
4. Pay close attention to the colors of the label

### Environment

- OS: Windows 11
- Browser: Google Chrome
- Browser Version: Version 110.0.5481.178 (Official Build) (64-bit)

**Comment by Miodec** [comment]
It wont be synced up because it takes time for the request to come back from the server, telling the client what daily position they got.
