### ISSUE TITLE
Cursor starts at middle of screen (not start of words) in tape mode

### ISSUE THREAD

**Issue by fprasx** [monkeytypegame/monkeytype#4051]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

N/A

### Account config

N/A

### Current Behavior

The cursor starts in the middle of a word and the first word is cut off.
<img width="1470" alt="Screenshot 2023-03-07 at 2 15 08 PM" src="https://user-images.githubusercontent.com/91577249/223527198-db82ddaf-cf92-4de3-b0fb-e1a408392b19.png">

### Expected Behavior

The words normally start at the middle of the screen and the cursor is at the first word.

### Steps To Reproduce

Turn on tape mode.

### Environment

- OS: MacOS Ventura
- Browser: Firefox
- Browser Version: 110.0.1

**Comment by Miodec** [comment]
Fixed in de0ea5e288254ead827ac8e5a691cb88c4fb951f, deploying soon
