### ISSUE TITLE
Favicon Does Not Update in Firefox Bookmarks

### ISSUE THREAD

**Issue by UnrealApex** [monkeytypegame/monkeytype#4080]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

UnrealApex

### Current Behavior

Monkeytype's favicon does not update in Firefox's bookmarks bar.

**theme**(`cherry blossom`):
![image](https://user-images.githubusercontent.com/79121360/225829423-9c20a146-0b5e-411c-a75b-b1c2ad567871.png)

**favicon**(`serika dark`):
![image](https://user-images.githubusercontent.com/79121360/225829685-4fdc387a-272b-4b2f-8e8e-0fea3f02854f.png)

From my testing, it appears that Firefox does not seem to detect the favicon URL's [change](https://github.com/monkeytypegame/monkeytype/blob/a04768bbfaa406b20f9ff8a5702b371a798be2c0/frontend/src/ts/controllers/theme-controller.ts#L151). It also does not change when you delete it's link tag and reappend it to the document:
```js
    $("#favicon").remove();
    $("head").append(`
    <link
      id="favicon"
      rel="shortcut icon"
      type="image/x-icon"
      href="${canvas.toDataURL("image/x-icon")}"
    />
    `);
  }, 125);
```
 Though I am unsure of how Firefox retrieves the favicon files.

### Expected Behavior

Monkeytype's favicon would update in Firefox's bookmarks bar.

For example, if I selected the theme `cherry blossom`, the bookmark's favicon should change accordingly.

### Steps To Reproduce

1. Open the command line
2. Go to `themes > `
3. Go down the themes with your arrow keys
4. The bookmark's favicon should change to reflect the theme

### Environment

- OS: Windows 10 + WSL
- Browser: Mozilla Firefox
- Browser Version: 111.0 (64-bit)

### Anything else?

Note that this functions properly in Google Chrome(`111.0.5563.65 (Official Build) (64-bit) (cohort: Stable) `):
![image](https://user-images.githubusercontent.com/79121360/225829922-44db8e28-7684-4323-8b79-54b536b32fef.png)

This issue is related to #38.

**Comment by Miodec** [comment]
Yeah im not sure if this feature has ever / will ever work on Firefox. They seem to be doing the favicon caching once or something.

**Comment by UnrealApex** [comment]
I see. In that case, should I just close this issue? Shall I file a report on Bugzilla?

**Comment by Miodec** [comment]
Well, im not sure if it would be appropriate for Bugzilla either. Their bookmark icons technically work, they just don't have a feature where they auto update when the website changes it. You can try though.
