### ISSUE TITLE
Require Strict Equality

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4098]
Currently, much of the codebase has instances of `==` which is known to be unreliable due to type coercion. Replacing it with `===` and enforcing it with lint will improve the security of the codebase.

Tasks: 
- String Mode2: #4094 
- Backend: #4086

**Comment by AshwanthramKL** [comment]
Hey can I work on this?

**Comment by Ferotiq** [comment]
> Hey can I work on this?
> 
> 

I've been working on this (slowly) and we're waiting for the mode2 pr to merge before making anymore progress. But once it's merged I can assign you.

I recommend you make a pr for a couple files at a time to make reviewing easier. Also, double/triple check the types of each operand to ensure the loose equality isn't doing an implicit conversion (our type system is messy atm).

**Comment by aviiciii** [comment]
hey, i noticed that the #4097 has been merged. can i work on this?

**Comment by aviiciii** [comment]
I just went through all the files in the `./backend` directory and found that all the equality checking operands are **strict**.

**Comment by Miodec** [comment]
Frontend doesn't yet

**Comment by aviiciii** [comment]
Yes, I am working on it. Just gave an update since backend was what I first went through.

**Comment by aviiciii** [comment]
could someone review the files changed, so i can proceed further. cheers
i checked the data types of all them except the ones with subgroups like MonkeyTypes.CommandsSubgroup which I couldn't understand. it would be great if someone could help me with that

**Comment by aviiciii** [comment]
In the file `./frontend/src/ts/commandline/index.ts`, there are couple instances of Config.singleListCommandLine but I couldn't find the data type of them

**Comment by Miodec** [comment]
Which line sorry

**Comment by aviiciii** [comment]
The lines 539, 682, 697 and 786.

**Comment by Miodec** [comment]
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/46841f8f-337e-4927-8678-c5cb1fa452fa)

`types.d.ts:85`

**Comment by aviiciii** [comment]
thank you for that.
