### ISSUE TITLE
MS Edge: Autofill modal toggles on and off during typing

### ISSUE THREAD

**Issue by eti-iniER** [monkeytypegame/monkeytype#4130]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

randombernie

### Current Behavior

Whenever I open the website and I start typing (regardless of which mode I'm in) the autofill modal flashes on and off on the left side of the words. Mouse cursor position doesn't stop it from happening. I observed that the modal only appears when the typing cursor moves to the start of a new word, and it disappears once a letter of the word is typed. It appears again on the next word.

### Expected Behavior

I expected to type regularly

### Steps To Reproduce

1. Open the website using MS Edge
2. Try switching between modes
3. Begin typing

### Environment

- OS: Windows 10
- Browser: Microsoft Edge
- Browser Version: Version 111.0.1661.54 (Official build) (64-bit)

**Comment by StarKnightt** [comment]
It was happening with me too, then I logged out and logged in and it was solved automatically, How I don't know. Give it a try. Hopefully it will work for you.

**Comment by Miodec** [comment]
You have to disable autofill in Edge settings. I tried everything on my end including contacting Edge about it, but I dodn't get a response from them.

**Comment by eti-iniER** [comment]
Okay then. Thanks y'all
