### ISSUE TITLE
Custom text needs to be selected every time the page is reloaded

### ISSUE THREAD

**Issue by lucaspessivaldo** [monkeytypegame/monkeytype#4182]
### Current Behavior

I have a custom text saved on my profile, but every time I practice it and reload the page, I need to choose the custom text again.

### Expected Behavior

The custom text needs to keep as the current text after reloading the page

### Steps To Reproduce

1. Create a custom text.
2. Save it.
3. Choose the custom text
4. Reload the page.
5. And you will see the default custom text 'The quick brown fox jumps over the lazy dog', not your custom text

### Environment

- OS: Linux Ubuntu
- Browser: Google Chrome
- Browser Version: 112.0.5615.49 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Not a bug - the custom text is meant to reset on refresh

**Comment by karl** [comment]
Any chance we could look at changing this?

I've been using monkeytype to teach my daughter to touch type and help her learn her weekly spelling list, and having to set up the custom text again on every reload is a noticeable speed bump in the process.

**Comment by Miodec** [comment]
To be fair this this decision was made very early and I ended up sticking with it, but after giving it some thought there is no reason not to save it in local storage.

**Comment by karl** [comment]
Amazing, thanks you!
