### ISSUE TITLE
Language List Not In Alphabetical Order

### ISSUE THREAD

**Issue by meyerhenning** [monkeytypegame/monkeytype#4189]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The language list is not in alphabetical order

![image](https://user-images.githubusercontent.com/82178058/232566512-7df5c328-1ebf-483d-8b68-3c91c271e528.png)

### Expected Behavior

The language list is in alphabetical order.
It's common to expect a list in alphabetical order, so this should be considered a bug.

I know there is a search to find the language you want but this doesn't mean that the list should be unordered.

### Steps To Reproduce

1. Go to https://monkeytype.com/
2. Open the language list

### Environment

- OS: Fedora 37
- Browser: Brave & Firefox
- Browser Version:

**Comment by Miodec** [comment]
The list is ordered roughly by popularity by design. This is not a bug.
