### ISSUE TITLE
Investigate if its possible to run the backend server without the Firebase service account

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4190]
Currently the contributing file suggests thats possible, but the server errors out if the file is not present. Using an empty json file also crashes the server

**Comment by ArijanJ** [comment]
From [CONTRIBUTING_ADVANCED.md](https://github.com/monkeytypegame/monkeytype/blob/master/CONTRIBUTING_ADVANCED.md):
`Within the frontend/src/ts/constants directory, duplicate firebase-config-example.ts, rename it to firebase-config.ts`
So, not an empty json file but the example config with all the fields empty.

**Comment by Miodec** [comment]
Firebase config is different to the service account. One is responsible for the frontend and one is for the backend.
