### ISSUE TITLE
?gnineppah s'tahW (What's happening?)

### ISSUE THREAD

**Issue by rocketraccon220** [monkeytypegame/monkeytype#4251]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Everything in the site is mirrored today. 
Issue persists even after opening in incognito/ another browser. Pls resolve. 

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
Hhahahah i love that title. Sorry about that, should be good now.
