### ISSUE TITLE
API requests blocked by Cloudflare

### ISSUE THREAD

**Issue by qixils** [monkeytypegame/monkeytype#4254]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The API subdomain is protected by Cloudflare anti-DDoS which sometimes intercepts requests to access the API and instead returns a browser challenge page.

### Expected Behavior

As accessing the API is an inherently robotic action, I expected Cloudflare anti-DDoS to not be enabled on the API subdomain, or at the very least set to "Essentially Off." I believe the simplest way to accomplish this while protecting the rest of the site is to setup a configuration rule (Rules -> Configuration Rules) which matches the hostname "api.monkeytype.com" and sets the Security Level to Essentially Off.

### Steps To Reproduce

1. Try to curl https://api.monkeytype.com/ on various machines
2. Find that some machines are inexplicably challenged by Cloudflare no matter what headers or user agent is set

### Environment

- OS: Ubuntu 20.04.6 LTS on Windows 10 x86_64
- Browser: curl
- Browser Version: 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

### Anything else?

This was previously reported at #2868 but the fix seems to have been specific to GitHub actions as I'm encountering the issue still on my home network (and, surprisingly, not my actual server for apps and bots).

![image](https://user-images.githubusercontent.com/13265322/235981003-c2663043-ab22-470f-bbc7-5332e6a37b3e.png)

**Comment by Brianalmeida** [comment]
I am able to reproduce this as well:
```
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">


</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
```
**Environment:**
- SLES 15 SP5 
- Brave Browser (Version 1.53.33 Chromium: 113.0.5672.92 (Official Build) nightly (64-bit)](https://brave.com/latest/)
- Curl version (curl 7.79.1 (x86_64-suse-linux-gnu) libcurl/7.79.1 OpenSSL/1.1.1l-fips zlib/1.2.13 brotli/1.0.7 zstd/1.5.0 libidn2/2.2.0 libpsl/0.20.1 (+libidn2/2.2.0) libssh/0.9.6/openssl/zlib nghttp2/1.40.0 OpenLDAP/2.4.46)

**Comment by Brianalmeida** [comment]
Seems to be resolved:
```
curl https://api.monkeytype.com/
{"message":"ok","data":{"uptime":537927952,"version":"2023.05.09_14.07.306de5f2e"}}
```

**Comment by qixils** [comment]
Yes

**Comment by Miodec** [comment]
Try now, I've implemented the change recommended by @qixils

**Comment by qixils** [comment]
For the moment I still seem to be getting the CF challenge on my home network but it does take some time for changes to propagate to all their servers, I'll try again a little bit later

**Comment by Miodec** [comment]
Is it good now?

**Comment by qixils** [comment]
Unfortunately no, still getting blocked by CF

**Comment by Miodec** [comment]
Hmm, just updated the rule, maybe i misconfigured it. Try again in a couple hours.

**Comment by qixils** [comment]
Unfortunately still happening 😔

**Comment by Miodec** [comment]
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/8ed1539b-8c5f-492d-94e6-89c4b9364cbf)
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/b1290d79-4c5f-48d2-b68b-3b72879da480)

Idk then, either im stupid or CF is.

**Comment by relative** [comment]
[it is impossible to disable WAF in Cloudflare unless you are a paying customer on the Enterprise plan](https://developers.cloudflare.com/support/firewall/settings/understanding-the-cloudflare-security-level/#overview)

**Comment by Miodec** [comment]
Weird that it allows me to select "essentially off" when its not available to me. I've changed it to "low", hopefully it helps. (i guess there is nothing else i can do)
