### ISSUE TITLE
Bio & Keyboard details on profile overflowing

### ISSUE THREAD

**Issue by CarterBrehm** [monkeytypegame/monkeytype#4255]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Ozrukar

### Current Behavior

On the profile page, my `Keyboard` and `Bio` texts overflow the assigned box, resulting in the text clipping and being unreadable.

### Expected Behavior

The `Keyboard` and `Bio` texts should wrap around instead of clipping, given that they are both within the required character limit.

### Steps To Reproduce

1. Go to a profile in Safari
2. Look at the top bio box

### Environment

- OS: macOS Ventura 13.3.1
- Browser: Safari
- Browser Version: Version 16.4 (18615.1.26.11.23)

### Anything else?

Safari:
<img width="1026" alt="CleanShot 2023-05-03 at 13 54 30@2x" src="https://user-images.githubusercontent.com/26262673/236016658-271f6227-577b-4dcc-9678-a96a318fe45d.png">

Firefox:
<img width="1233" alt="CleanShot 2023-05-03 at 14 00 50@2x" src="https://user-images.githubusercontent.com/26262673/236017222-6c354067-9ea9-4ca8-9594-8e23159652a1.png">

**Comment by Miodec** [comment]
I hate Safari. I hate Safari. I hate Safari. I hate Safari. I hate Safari. I hate Safari. I hate Safari.

**Comment by CarterBrehm** [comment]
Can confirm, this resolves the issue. Thanks for the quick fix!
<img width="966" alt="CleanShot 2023-05-03 at 18 44 00@2x" src="https://user-images.githubusercontent.com/26262673/236074466-6cb0a7af-03ba-4d4f-b0bf-9228513212e8.png">

**Comment by CarterBrehm** [comment]
This bug is back again, even with the CSS fix... running:
- macOS Ventura 13.5.2 (22G91)
- Safari Version 16.6 (18615.3.12.11.2)

I will note that the bug seems to only occur when I'm on my own profile (`/account`):
<img width="1002" alt="CleanShot 2023-09-14 at 12 08 02@2x" src="https://github.com/monkeytypegame/monkeytype/assets/26262673/3a075dbe-7990-4781-ada3-bea8d2da0795">

The bug does not appear when I go incognito and view my profile permalink (`/profile/Ozrukar`):
<img width="1215" alt="CleanShot 2023-09-14 at 12 09 58@2x" src="https://github.com/monkeytypegame/monkeytype/assets/26262673/f98541bc-9bfc-45bf-af03-d49c4a204e9f">

Even manually shrinking the window to try to force line breaks seems to be handled correctly, with the text resizing:
<img width="713" alt="CleanShot 2023-09-14 at 12 11 47@2x" src="https://github.com/monkeytypegame/monkeytype/assets/26262673/af5b1f19-119f-4b88-8a68-440677b0445a">
