### ISSUE TITLE
Automatic tabs in code quotes

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4266]

**Comment by AkashKishore-Mukhia** [comment]
Please provide a description of the problem.

**Comment by Miodec** [comment]
Tabs in code quotes are not automatic. If the next character is a tab character and we are in quote mode and the language begins with `code_` - emulate a tab keypress.

**Comment by arushsharma24** [comment]
Hey, I am interested in working on this issue but am still having trouble understanding what the basic problem is, as in what do we want that is not there. 
From my understanding as of now, we want a tab character to be emulated as a tab keypress. However, would that not be the default case?

> (just like nospace funbox emulates the space keypress)
Also, could you be kind enough to elaborate a little on what is "nospace funbox" or give a link so I can understand it better? I believe it might help me get a better understanding of the issue.

**Comment by Miodec** [comment]
> From my understanding as of now, we want a tab character to be emulated as a tab keypress. However, would that not be the default case?

No. We want to emulate a tab keypress when the next character is a tab character (only in code quotes).

<img width="667" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/2d8a653d-c25c-4d39-a086-4c52daf18a34">



> Also, could you be kind enough to elaborate a little on what is "nospace funbox" or give a link so I can understand it better? I believe it might help me get a better understanding of the issue.

The no space funbox removes spaces from the test (you can try it out in the settings page). When the user inputs the same number of characters as the word, a space keypress is emulated.

<img width="606" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/0b07e39d-9c4c-4476-a546-20bcf72e3764">

**Comment by arushsharma24** [comment]
I see, so basically, for a user to avoid having to press extra tabs in code quotes by having it emulated? 
That is what I have seemed to understand. Do correct me if I am mistaken. If this is indeed the case, I would just want to know why we would want automatic tabs as a default if I may ask.

Also thanks for explaining the nospace funbox, I was actually unaware of the funbox feature and only just now came to understand how it works, and am having fun playing around with it now.

**Comment by xwillq** [comment]
All code editors and IDEs automatically indent code when you start a new line inside of code block. The fact that you have to press `tab` manually makes practicing `code` languages unrealistic. Adding automatic indentation, even if it's off by default, would bring practicing on Monkeytype closer to real code editing.

At least that's how I understood this issue.

**Comment by arushsharma24** [comment]
Yeah thanks, that is what I thought could be the reason behind the approach as well. Having said that, I tried to understand the code for the nospace funbox and for now it seems like I need a better understanding of the codebase to be able to work on it, so I might try to look at some other issues first that I may be able to be useful with. Although I am interested in resolving this, and if there are any resources I could follow to gain a better understanding, I would love to know. Thanks!

**Comment by Miodec** [comment]
I guess diving into the input controller on your first issue is not the greatest of ideas. Review the commit that closed this issue and see if you can understand everything - there willl be plenty more issues for you in the future.

**Comment by arushsharma24** [comment]
Right, I wouldn't have been able to come up with that just yet. I think I do have an understanding of how the changes you have made work, although I don't understand what the "/^\t+/" stands for.

From my understanding, the way the code you have currently kept commented would work to avoid the spaces as it adds the check for automatic tabs in the same way in the handleSpace() function.

**Comment by Miodec** [comment]
> although I don't understand what the "/^\t+/" stands for.

Thats just checking if the word has one or more (`+`) tab characters (`\t`) at the start of the word (`^`)
