### ISSUE TITLE
Cookie concent popup freezes

### ISSUE THREAD

**Issue by KristalAlfred** [monkeytypegame/monkeytype#4302]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Wanted to try Monkeytype for the first time. Browsed to https://monkeytype.com/ and I'm shown a cookie consent pop up. This is what happens when pressing the different alternatives:
* Agree - Nothing happens
* More options - Freeze. After a while, I get an 'out of memory' error from chrome
* The small 'partners' link in the text - Freeze. Same as above.

This happens in Chrome v113.0.5672.94 both in regular and incognito mode. Also tried Edge v113.0.1774.42, same thing.

### Expected Behavior

The app shouldn't freeze when pressing some of the alternatives.

### Steps To Reproduce

1. Enter https://monkeytype.com/
2. Wait for the cookie consent popup
3a. Press 'More Options'
3b. Press 'Partners'

### Environment

- OS: Windows 10
- Browser: Chrome
- Browser Version: 113.0.5672.94 (Official build) (64-bit)

### Anything else?

I saw there are two consent pop ups. This is the one I'm talking about:

![image](https://github.com/monkeytypegame/monkeytype/assets/83819096/6ef45f9e-8f34-4f75-9a76-3d4b273e1b62)

**Comment by NatoNathan** [comment]
This is also affecting Chrome Version 113.0.5672.92 (Official Build) (arm64) and Firefox on MacOS 113.0.1 (64-bit)

I also get this error in the logs 
```
Uncaught (in promise) EncodingError: Unable to encode TCModel tcModel.gvl.readyPromise is not resolved
    at new t (cmp2.js?referer=monkeytype.com/:1:70348)
    at e.process (cmp2.js?referer=monkeytype.com/:1:85170)
    at e.encode (cmp2.js?referer=monkeytype.com/:1:14897)
    at Ct (cmp2.js?referer=monkeytype.com/:1:176980)
    at e.value (cmp2.js?referer=monkeytype.com/:1:145636)
    at e.value (cmp2.js?referer=monkeytype.com/:1:143679)
    at e.value (cmp2.js?referer=monkeytype.com/:1:169807)
    at e.value (cmp2.js?referer=monkeytype.com/:1:156403)
    at Object.setConsentInfo (cmp2.js?referer=monkeytype.com/:1:178614)
    at e.apiCall (cmp2.js?referer=monkeytype.com/:1:31239)
```

**Comment by Miodec** [comment]
Should be all good now, could you both test it?

**Comment by KristalAlfred** [comment]
Works for me too!

**Comment by Miodec** [comment]
> There’s two cookie notifications but it works.

Yeah, it will have to remain like this for now. One is for the website itself and one is for the advertiser.
