### ISSUE TITLE
Greek isn't in Lazy Mode even though Lazy Mode Allows it

### ISSUE THREAD

**Issue by 2Bored4Ever** [monkeytypegame/monkeytype#4327]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

N3rdyF0e

### Account config

This bug always happens, even when I'm not logged onto my account

### Current Behavior

When you click on Greek with lazy mode. It should show Greek with English letters.

### Expected Behavior

When you click on Greek with lazy mode. It instead show Greek with Greek letters.

### Steps To Reproduce

1. Go to Settings and turn Lazy Mode "ON"
2. Go to Languages and press Greek
3. The Greek lazy mode bug should be there

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 111.0.5563.65

I also have Greek lazy mode issue on my iphone 11 using safari (using ios 16.5).

### Anything else?

In [the commit that was supposed to make lazy mode for Greek](https://github.com/monkeytypegame/monkeytype/commit/ff1fc38108fdee11d6b38434fd4422f24e23d5ba), it looks like it replaced the Greek letters with more Greek letters instead of English letters.
(Example: [ά -> α} instead of [ά -> a} )

So based on that commit, I'm assuming that's the reason for the Greek lazy mode issue.

**Comment by Miodec** [comment]
Lazy mode is not meant to just convert to english characters, its only meant to remove the accents while keeping the greek characters.
