### ISSUE TITLE
Persistent Caps Lock Message

### ISSUE THREAD

**Issue by RoyalCoderPRO** [monkeytypegame/monkeytype#4330]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

No

### Account name

RoyalMonkey_PRO

### Current Behavior

Caps lock message seems to stay on screen even after caps lock is off

### Expected Behavior

Caps lock should disappear immediately after caps lock removed

### Steps To Reproduce

1. Use any settings
2. Hit caps lock
3. Start typing
4. Hit tab
5. Press caps lock to turn it off
6. Caps lock retains
Similarly,
1. Hit tab
2. Turn on caps lock
3. Hit tab again

### Environment

- OS: Windows 11
- Browser: Edge

**Comment by Miodec** [comment]
Tested on MacOS Chrome, Windows Chrome, Windows 10 Edge - not happening for me.

**Comment by SlipperyTrout** [comment]
Tried reproducing in edge and firefox. Unable to reproduce the "Caps Lock" message from being stuck. However one thing i did notice is that after tab is pressed the Caps Lock message will not update until the person resumes typing. Maybe this is the issues being described.

**Comment by RoyalCoderPRO** [comment]
> Tried reproducing in edge and firefox. Unable to reproduce the "Caps Lock" message from being stuck. However one thing i did notice is that after tab is pressed the Caps Lock message will not update until the person resumes typing. Maybe this is the issues being described.

Yeah... Exactly that... My apologies for not being specific
