### ISSUE TITLE
Custom Dictionary - unexpected behaviour.

### ISSUE THREAD

**Issue by hazartilirot** [monkeytypegame/monkeytype#4370]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

hazartilirot

### Account config

{"theme":"repose_light","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":30,"mode":"custom","quoteLength":[3],"language":"german","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"150","accountChart":["on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":true,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

Cuts off a piece of text or wipes out text entirely, critical issues when you go to settings having done a couple of typing-rounds.

### Expected Behavior

- It should keep text in a state it's been stored in the dictionary
- Re-writing the existing dictionary provided it's needed

### Steps To Reproduce

Go to **Custom**, save a piece of text (2K words) in German. Then start playing with it, for example, switch from normal to expert, keep typing. Fail intentionally. The system would store the stage of each failure. You will start (as an expert) from the point you've just lost. The issue with it is that it actually removes the text I've stored in the dictionary. For no reason the data which has to be in a long term memory gets into the state of the app (well, obviously it's supposed to be like that, but the state of the app mustn't change the genuine text).

Another thing is, when I place the text all over again, I cannot re-write the the existing dictionary. I have to remove it, and then create a new one (which is inconvenient).

(take the text)

`Darf ich mir dieses Buch ausleihen, um es zu kopieren? Man darf nicht einfach etwas aus dem Internet kopieren! Ich kaufe Hustenbonbons in der Apotheke. Ich frage den Apotheker um Rat. In der Apotheke kann ich auch Pflaster kaufen. Im Kopf ist das Gehirn. Hoffentlich. Der Kopf sitzt auf dem Hals. Sie tippt sich an den Kopf. Ich habe heute Kopfschmerzen. Das Mädchen wird später eine Frau. Ein Mädchen ist ein weibliches Kind. Wird es ein Junge oder ein Mädchen? Hast du die Neuigkeit schon gehört? Es gibt leider keine Neuigkeiten, was den Waldbrand angeht. Haben wir noch Milch zu Hause? Trinkst du deinen Tee mit Milch? An der Ampel musst du links abbiegen. Pass auf, die Ampel ist rot! Deine Wohnung ist in einer sehr zentralen Lage. Wie ist die Lage? Ist die Party schon vorbei? Die Bundeskanzlerin Angela Merkel spricht zur Lage der Nation. Du hast Glück gehabt, dass heute kein Test geschrieben wurde. Um im Lotto zu gewinnen, braucht man eine Menge Glück. Ich brauche noch eine günstige Unterkunft. Die Flüchtlings-Unterkunft ist am Rand der Stadt. Mein Sohn hat eine Unterkunft gefunden. Ich muss noch auf die Toilette, bevor wir gehen. Beeile dich, bevor es zu spät ist. Ich reserviere selbstverständlich einen Platz! Er ist selbstverständlich auch eingeladen! Wir kommen selbstverständlich gerne. Ich brauche abends meine Ruhe. Er möchte in Ruhe lernen. Lass mich jetzt endlich mal in Ruhe. Ich finde, es sollte mehr nette Menschen geben. Er hat viele nette Kollegen. Kinder, seid nett zueinander! Ich habe die Katze überall gesucht. Das Gesetz ist überall gültig. Überall blühen blaue Blumen. Ich suche eine günstige Wohnung. Nimm den grünen Gürtel, der ist günstiger. Du kannst dir nur ein günstiges Auto leisten. Ich habe die Datei gespeichert. Wirst du alles auf dem USB-Stick speichern? Ich habe vergessen, es zu speichern! Ich habe keine Ehefrau. Ich bin ledig. Beim Fragebogen habe ich "ledig" angekreuzt. Bist du ledig oder verheiratet? Carolin war betrunken und konnte nicht mehr Auto fahren. Wer betrunken ist, hat am nächsten Tag einen Kater. Komm, betrinken wir uns. Herr Müller ist im Urlaub. Er ist abwesend. Susanne ist in Gedanken. Sie ist abwesend. Deine Abwesenheit hat uns gestört. `

### Environment

- OS: MacOS 13.4
- Browser: Brave
- Browser Version: [Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (arm64)]

<img width="2056" alt="Screenshot 2023-06-12 at 09 53 20" src="https://github.com/monkeytypegame/monkeytype/assets/1349977/066dc215-808f-4f69-abb0-8fb0ce5296a6">

**Comment by Miodec** [comment]
> The issue with it is that it actually removes the text I've stored in the dictionary.

Thats what book mode is designed to do. When the test ends it saves your position in the custom text, and the next test on that text will continue from the last word typed. You can then reset this progress in the custom text popup:

![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/34dbba7b-208a-4782-8152-a19c63cdf3c8)

I can't reproduce the error in your screenshot, what are the steps for that?

**Comment by hazartilirot** [comment]
Well it's another topic to open a dispute then. I think it's not intuitive. As for the **reset**, why should I reset a progress if I've completed the whole task?

Here's the video, something works incorrectly:
https://fex.net/s/8zf2ybe
https://fex.net/s/4zffysn

**Comment by hazartilirot** [comment]
Now, when I saved my text once again, I had omitted an option to save the process. It works perfectly well as I wanted. 
However, something is wrong with storing the process... Dunno. I hope you figure out what it's exactly. Thanks anyway.

**Comment by Miodec** [comment]
> Well it's another topic to open a dispute then. I think it's not intuitive.

If you don't want it to save progress, just dont save it as a book mode text.

> As for the reset, why should I reset a progress if I've completed the whole task?

Yeah, that was a bug. Just fixed it.

**Comment by hazartilirot** [comment]
Can I open the issue all over again? It relates to the same part. I just don’t want to open a new case.
Today I’ve bought an iPad Gen 6 (hooray!), and logged to my account at Monkeytype website. When I open my Custom dictionary it’s entirely empty. There’s nothing. Then I open the same Custom dictionary from my PC - the text is there.
Is the text stored in the browser’s localStorage? I just want to have an option to practise a vocabulary from my both devices. 
Thanks.

**Comment by Miodec** [comment]
The custom texts are stored only locally by design - they can be very large, so its done this way to save on storage in the DB.
