### ISSUE TITLE
Typing on mobile devices automatically capitilises each word

### ISSUE THREAD

**Issue by aviiciii** [monkeytypegame/monkeytype#4388]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

aviiciii

### Current Behavior

Modern keyboards use auto-capitilisation to captilise every word followed by punctuation and in mobile (android with microsoft swiftkey in my case) capitilises every word when entering space.

### Expected Behavior

It would great if there is a option to capitilise each word in the test to nullify the auto-capitilise

### Environment

- OS: Android 13
- Browser: Chrome
- Browser Version: 114.0.5735.131

**Comment by Miodec** [comment]
Check if it happens on other browsers - iOS seems fine.

**Comment by Miodec** [comment]
Can you test again?

**Comment by aviiciii** [comment]
Yep, it is still the issue with microsoft swiftkey :(

https://github.com/monkeytypegame/monkeytype/assets/88141521/50f9cdd9-d105-423f-aaa1-fb411ccc4455

**Comment by Miodec** [comment]
Can you give me:
 - swiftkey version (and if you are a beta user)
 - device name
 - android version

**Comment by Miodec** [comment]
Alright, sent a support ticket to the SwiftKey team, will see what they say.

**Comment by aviiciii** [comment]
Cool 👍🏻

**Comment by Miodec** [comment]
Still an issue?

**Comment by aviiciii** [comment]
Yep, it's not fixed :(

**Comment by Miodec** [comment]
Yikes. Well, sorry but i think I'll close this one. I am using all html properties i could find to disable auto capitalisation. This seems to be purely an issue with SwiftKey.

**Comment by aviiciii** [comment]
Okkk, lets keep our fingers crossed that it gets fixed by them.
