### ISSUE TITLE
Korean character composition fails for this particular string 

### ISSUE THREAD

**Issue by maxkapur** [monkeytypegame/monkeytype#4389]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

None

### Current Behavior

I was monkeytyping along with a news article that contained the string `자율형사립고(자사고).외국어고.국제고는` in Korean and was unable to type the last character in the string. 

- The periods between the words are intentional. The original text was `자율형사립고(자사고)·외국어고·국제고는`, with vertically centered dots used as a shorthand for "and," and I replaced them with periods to make it easier to type. Monkeytype's "remove fancy typography" option doesn't cover this case, but that's not the point of this issue.

### Expected Behavior

For context, typing in Korean involves composing characters such as `국` by pressing keys corresponding to the individual components (called jamo), i.e. `ㄱㅜㄱ`, and (AFAIK) it is up to the computer's input method (IME) to compose a sequence of these jamo into a Unicode character.

So, to type the last character '는' in the string `자율형사립고(자사고).외국어고.국제고는`, the keypress sequence is `ㄴㅡㄴ` (or `sms` on a USAmerican keyboard with Korean IME) and the IME will resolve this to `는`. 

However, on Monkeytype, in the context of the string/word `자율형사립고(자사고)·외국어고·국제고는`, this particular sequence of jamo fails to resolve. The first 20 characters type correctly, but the last one renders (in the little preview that pops up below the text when you have Korean set as the language) as `ㄴㅡㄴ` instead of composing to `는`.

This is a bit hard to capture in a screenshot, but the image below shows the state of the page after correctly typing the full string. I have pressed `ㄴ` for the second time, but the jamo sequence `ㄴㅡ` has been "eaten," and the preview shows only `ㄴ`. 

![Screenshot_20230619_094558](https://github.com/monkeytypegame/monkeytype/assets/48514405/7df95a11-91ea-44f8-bfa8-5e80f53a6922)

Indeed, at this moment, I can press *any* letter keys I want (Roman or Korean), and they just get eaten in a similar way; the word isn't marked as right or wrong, and Monkeytype just hangs on the last character without proceeding to the test summary. 

### Steps To Reproduce

1. Browse to Monkeytype
2. Choose the `words` option which lets you change the language to Korean
3. Now choose the `custom` option and input `자율형사립고(자사고).외국어고.국제고는` as the custom text
4. Type the string `자율형사립고(자사고).외국어고.국제고는`, correctly
5. Monkeytype hangs without registering the input as correct/incorrect or proceeding to the test summary

### Environment

- OS: Fedora Linux 37 KDE Plasma
- Browser: Firefox
- Browser Version: 114.0
- Input method: fcitx5 v5.0.23

Also occurs in Chromium v113.0.5672.126 on the same machine.

### Anything else?

- I'm guessing this has something to do with the parenthesis and periods, but I couldn't construct another example that fails in the same way.
- I don't think this issue is related to https://github.com/monkeytypegame/monkeytype/issues/3693. In fact, the pace character seems to work just fine for me.

- Might be related to https://github.com/monkeytypegame/monkeytype/issues/3839?
  - But I can type other words that end in `는` just fine (someone would certainly have noticed if all Korean words ending in `는` broke Monkeytype—that would be like if English words ending in `ing` broke it)
  - And unlike in that issue, nothing is logged to the browser console in this case.

**Comment by maxkapur** [comment]
No, it does not.

**Comment by Miodec** [comment]
Yeah, probably related to #3839 then

**Comment by Miodec** [comment]
It all has to be Linux related, because I've got no issues typing `는` as the last character of the test... This is gonna be hard to fix.

**Comment by Miodec** [comment]
Can you test now? I may have fixed it.

**Comment by maxkapur** [comment]
Still have the same issue, unfortunately, after cloning at commit 5d93e2e1ceb5bbacac8df5624316e74a4d5b30d1 and building/running locally according to the instructions in CONTRIBUTING_ADVANCED.md. 

No messages appear in the console.

**Comment by Miodec** [comment]
Is there any change you could guide me through installing this layout on a Linux VM? I tried adding Korean but it doesn't really work.

**Comment by maxkapur** [comment]
Sure thing; there are certainly some gotchas with the process.

This method will use IBus as the input method (the default in Gnome) and is sufficient to reproduce the problem.

Note that lots of people prefer the fcitx5 input method for East Asian languages because it has more features, but the installation is a bit trickier.

## Setting up Korean (Hangul) input on Ubuntu 22.04 LTS

1. Download Ubuntu 22.04 LTS from <https://ubuntu.com/download>.
2. Attach the ISO to a virtual machine and boot into the live environment.
3. Install Ubuntu and choose default options (no need to install Korean language anything at this stage).
4. Log in, open a terminal, and install the `ibus-hangul` input method:

    ```bash 
    sudo apt update && sudo apt upgrade
    sudo apt install ibus-hangul
    ```

5. Reboot.
6. Open **Settings > Keyboard,** and under **Input Sources** click the plus sign to add a new input source.
7. Click **⋮** and search for `hangul`. The only result is **Other.** Click this and then choose **Korean (Hangul).**
8. You should now see a new icon in the systray (top right of the screen) that says `en`. This is the input method switcher.
9. Reboot again (sorry).
10. Open a text editor and test that you can type in Korean by clicking on the input method switcher and choosing Korean.

    *Note:* You have to first select **Korean (Hangul)** as the input method, *then* change the toggle below to enable **Hangul mode.**

    Sometimes, when you switch focus from one text field to another, this glitches out and you have to retoggle the setting (these kinds of nuisances are why many people are moving to fcitx5).

10. Now open Monkeytype and you should be able to reproduce the problem.

**Comment by maxkapur** [comment]
By the way, I found another string that fails:

```
윤봉길.이봉창.안중근.박승환,.홍범도.강우규.이순신.강감찬.을지문덕.김좌진.신돌석.이강년.유인석
```

Again, looks like bizarre typography, but this is straight from a [news article](https://www.hani.co.kr/arti/politics/defense/1105910.html) after replacing ` ·` with `.` for ease of typing.

In this case, you can get as far as

```
윤봉길.이봉창.안중근.박승환,.홍범도.강우규.이순신.강감
```

before it starts wigging out.

**Comment by Miodec** [comment]
After following your instructions and testing by setting the custom mode text to `는` - i was able to type it correctly, with 100% accuracy. 

Does it work for you when you set custom mode to just the single problematic character? Does the issue only show up when the text is longer?

![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/006afd53-3d22-46bd-9e74-5a2893ee139d)

**Comment by maxkapur** [comment]
It has to be in the context of that string.

**Comment by Miodec** [comment]
What the shortest string that is causing issues?

**Comment by maxkapur** [comment]
The shortest one I have found so far is the one in the title, but I will let you know if I find a shorter one. The common denominator is the presence of periods or other punctuation within a single word.

**Comment by Miodec** [comment]
So, if you change custom text from `자율형사립고(자사고).외국어고.국제고는` to `자율형사립고(자사고) 외국어고.국제고는` it works?

**Comment by maxkapur** [comment]
I believe so, but I am not at a computer to test it now.

**Comment by Miodec** [comment]
Alright, let me know when you can.

**Comment by maxkapur** [comment]
Just checked&mdash;`자율형사립고(자사고) 외국어고.국제고는` works just fine. I tried a few other ways of shortening the original text and all of them work fine.

But in the course of typing out articles that include this `foo.bar.baz` pattern, I still encounter this bug on a fairly regular basis. I will keep this issue updated as I find new strings (especially shorter ones).

**Comment by maxkapur** [comment]
OK, here's a good example that shouldn't be as hard to reproduce 😂. On a USAmerican keyboard with a Hangul input method enabled, type `dhl.dhl.dhl.dhl. ...` over and over again to produce:

```
외.외.외.외.외.외.외.외.외.외.외.외.외.외.외.외.외
```

In Monkeytype, I can get as far as 

```
외.외.외.외.외.외.외.외.외.외.외.외.외.
```

before it hangs.

**Comment by Miodec** [comment]
> But in the course of typing out articles that include this `foo.bar.baz` pattern, I still encounter this bug on a fairly regular basis. I will keep this issue updated as I find new strings (especially shorter ones).

Even in english?

**Comment by Miodec** [comment]
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/69168b2a-a5c1-4dd2-9acf-9675aab84cbe)
Ok, i got it.

Weirdly enough, if i type a random key in place for that broken character, i can then continue as normal:

![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/b61aca93-6d03-4ed3-96ba-be783a5bad80)


Do you see this behavior too?

**Comment by maxkapur** [comment]
> Even in english?

Only in Korean for me (although I seldom use Monkeytype in English).

>  if i type a random key in place for that broken character, i can then continue as normal

>  Do you see this behavior too?

For me, it continues to hang even if I press another character (doesn't matter if it's Korean, English, or punctuation). The only escape is to press space, which just marks the word wrong and moves onto the end of the test.

**Comment by Miodec** [comment]
I may have fixed it which should be live later today.

**Comment by maxkapur** [comment]
Link is down&mdash;I was too slow.

**Comment by Miodec** [comment]
Should be up again (damn timezones :D)

**Comment by maxkapur** [comment]
This fixed it!

**Comment by Miodec** [comment]
Perfect, deploying to live later today.
