### ISSUE TITLE
Language list is not alphabetic sorted

### ISSUE THREAD

**Issue by Jonadabe** [monkeytypegame/monkeytype#4390]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

I don't have any account with you yet.

### Current Behavior

The language list is not sorted alpabetically (nor descendent or ascendent).

### Expected Behavior

I think that the default behavior should be sorted.

### Steps To Reproduce

1 . Open monkeytype.com site and select other language, like portuguese in the unsorted pulldown list.

### Environment

- OS: Ubuntu 20.04
- Browser: Chrome
- Browser Version: 114

**Comment by Miodec** [comment]
Not a bug. Langauges are sorted roughly by popularity.
