### ISSUE TITLE
Notify users if they are trying to use an .edu email account

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4393]
Educational email addresses very often don't allow for receiving emails from outside the school network. Notify the user that they might not receive emails from monkeytype if they continue

**Comment by aviiciii** [comment]
With a little hint on where/how to catch the email and notify, I am interested to solve this issue.

**Comment by aviiciii** [comment]
Okay, let me try :)

**Comment by sanidhyas3s** [comment]
> `login.ts:171` creates a `new InputIndicator`. You have to add a new option for it, which users a new icon (something like `exclamation-triangle`). Then everytime the input field gets updated, check if it includes `.edu` after the `@` symbol and update the input indicator accordingly.

@Miodec There are quite a lot of institute email id's which do not contain `.edu`, though don't think there's anything common in them to be able to detect it though.

**Comment by aviiciii** [comment]
I think the majority of the institutions use .edu or .ac.xx across the globe
Do you know any other domains that institutions use? If so do mention them.

**Comment by sanidhyas3s** [comment]
Yeah, including `.ac` as well does cover most of them.

[This](https://raw.githubusercontent.com/Hipo/university-domains-list/master/world_universities_and_domains.json) might be helpful.

**Comment by aviiciii** [comment]
That is a cool list. But ig `.edu` and `.ac.xx` is the more general way to handle here. 
Some universities just go with their country-level domain which might not be ideal to warn.
