### ISSUE TITLE
Japanese words test gets stuck if last character is typed using three letters

### ISSUE THREAD

**Issue by Kuuuube** [monkeytypegame/monkeytype#4407]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

When a japanese words test ends in a character that can be typed with two or three letters it will only accept the two letter combination and gets stuck if the three letter combination is used. The test will not end and the last character cannot be backspaced or fixed.

Here's a few examples of characters that can be typed with two or three letters:
つ: "tu" or "tsu"
し: "si" or "shi"
ち: "chi" or "ti"

This is only an issue with typing single characters not digraphs (eg. にゃ: "nya" has no issue).

### Expected Behavior

The last character of a test should be accepted regardless of how it is typed.

### Steps To Reproduce

The easiest way to do this is to make a custom test, enter any of the characters I mentioned above, and try to type it using the three letter combination.

### Environment

- OS: Windows 10
- Browser: Firefox
- Browser Version: 114.0.2 (64-bit)

- IME: Microsoft Japanese IME

**Comment by Miodec** [comment]
Probably related to #3839. Does it happen with characters requiring 2 letters?

**Comment by Miodec** [comment]
Can you test now?

**Comment by Kuuuube** [comment]
Yep, it works now. Thank you!
