### ISSUE TITLE
Make sure to hide the cookie popup when taking a screenshot (user might be blocking it, but it remains in the dom)

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4414]
This is what was reported by a user

![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/26732083-004f-48d3-b913-87b04eed0e18)

**Comment by sanidhyas3s** [comment]
@Miodec More explanation on the issue? 

Is it about this pop-up? How do you take a screenshot with this, the website can't used without completing this pop-up?
![image](https://github.com/monkeytypegame/monkeytype/assets/92792319/fc219a03-ba46-4322-b48a-9bc6ee9a31fc)

**Comment by Miodec** [comment]
Some cookie popup blocking extensions will leave the element in the DOM but keep it invisible, which means in will show up in the screenshot. 

The user claims its caused by the Brave browser but I can't reproduce this...

**Comment by Miodec** [comment]
And also, we already have a check for this...

![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/f4b3d278-7456-4ced-a269-8e5e409dba28)

**Comment by sanidhyas3s** [comment]
Ok, was able to recreate it using [this extension](https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche/related). Let me look into it and try to fix it.

![image](https://github.com/monkeytypegame/monkeytype/assets/92792319/166937b8-ffb0-4b69-b1ad-7c0c566878b7)
