### ISSUE TITLE
Send min speed in daily lb response and display it to the user if they are not qualified

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4424]

**Comment by HyperDanisH** [comment]
Hi, I am very curious to work on such issues in open source field. I would love if you elaborate this topic to me.

**Comment by Miodec** [comment]
> Hi, I am very curious to work on such issues in open source field. I would love if you elaborate this topic to me.

Currently the endpoint only returns the lb entries. Modify the response to include the min speed of the leaderboard. Then, if the user is currently not qualified for the daily leaderboard, display that min speed here: 
<img width="629" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/a5767c24-bfa3-4ca9-ac89-0190f2ffa0cd">

**Comment by HyperDanisH** [comment]
I would really love to work on this issue and would appericiate if it is assigned to me. I can implement this feature in the leaderboard in no time.

Best,

**Comment by ademirkan** [comment]
> I would really love to work on this issue and would appericiate if it is assigned to me. I can implement this feature in the leaderboard in no time.
> 
> Best,

Any update?

**Comment by HyperDanisH** [comment]
> > I would really love to work on this issue and would appericiate if it is assigned to me. I can implement this feature in the leaderboard in no time.
> > Best,
> 
> Any update?

Yea, I have an update and I need some info too. 

First of all the update is that I have created a design change (I have talked about it in disscussion tab) but the original developer of Monkeytype said not to it and I have started work on backend which you can check on my fork of monkeytype (Not on master branch, you'll find another branch).

Secondly, I need some data to populate leaderboard section (In localhost), I have connected application to both redis and mongodb but cant get it. Another one is, does it use redis for storing leaderboard data. The OG of the project told me that they use redis in disscussion tab, but when I see **getRank**  function, It have used mongodb.

Best,
