### ISSUE TITLE
Error Pop-ups don't clear themselves and cover huge portion of the screen.

### ISSUE THREAD

**Issue by sanidhyas3s** [monkeytypegame/monkeytype#4444]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No (this particular error occurs when saving any test results, but I guess some error can still be generated which would generate a similar pop-up and have the same behavior)

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No (same as above)

### Account name

sanidhyas3s

### Current Behavior

The pop-ups accumulate and don't get cleared with time, unless removed manually.

![image](https://github.com/monkeytypegame/monkeytype/assets/92792319/33797f80-3f39-4d56-8426-059021605042)

### Expected Behavior

Possibly it would be better if they disappear after few seconds automatically so that they don't accumulate and cover a huge portion of the screen. 

### Steps To Reproduce

Open monkeytype, turn off your internet, finish a test, when trying to save the result the error pop-ups and multiple errors would accumulate.

### Environment

- OS: Windows 11
- Browser: Google Chrome 
- Browser Version: 114.0.5735.199

### Anything else?

-

**Comment by Miodec** [comment]
Errors dont dissapear by themselves because they are errors and the user needs to know something wrong has happened. They need to be dismissed manually by design.

**Comment by sanidhyas3s** [comment]
> Errors dont dissapear by themselves because they are errors and the user needs to know something wrong has happened. They need to be dismissed manually by design.

Okay, they do not need to be automatically cleared. But should they duplicate every time the user clicks retry, hence eventually covering the entire screen? I know this is not really a big concern either way but still.
