### ISSUE TITLE
Unable to find the place to update email

### ISSUE THREAD

**Issue by dpthegrey** [monkeytypegame/monkeytype#4445]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Current Behavior

I want to change the email address but I am having a hard time locating the button to update email due to font and reading problem. I wish there was a more easy way to get to that place.

### Expected Behavior

easy way to update email.

**Comment by Miodec** [comment]
You can do it from the settings page.
