### ISSUE TITLE
Remember language choice before switching to quote mode

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4455]
If you are using english 1k and then switch to quote mode, it will automatically switch to english. But when going back to words or time mode, the website will not switch back to english 1k.

**Comment by ridemountainpig** [comment]
Hi, I want to ask is the language between time mode and quote mode should save with different language ?

**Comment by Miodec** [comment]
No, only save the selection if its within the same language group.

**Comment by ridemountainpig** [comment]
I would like to work on this issue and would appericiate if it is assigned to me.

**Comment by Miodec** [comment]
Alright
