### ISSUE TITLE
Inability to select common words within same language specific frequency ranges in quote mode

### ISSUE THREAD

**Issue by ridemountainpig** [monkeytypegame/monkeytype#4457]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

ridemountainpig

### Current Behavior
https://github.com/monkeytypegame/monkeytype/assets/92412722/a4394378-2ec7-4045-8cba-cae5712ef62b

### Expected Behavior

It should be ability to select common words within same language specific frequency ranges in quote mode

### Steps To Reproduce

1. Go to quote mode
2. Choose language

### Environment

- OS: macOS 13
- Browser: Google Chrome
- Browser Version: 114.0.5735.198 (official version) (arm64)

**Comment by Miodec** [comment]
This is not a bug. There is only one quote file per language group.
