### ISSUE TITLE
Using Arc Browser the webpage is always offline

### ISSUE THREAD

**Issue by amorino** [monkeytypegame/monkeytype#4487]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

amorino

### Current Behavior

Using Arc Browser I appear always offline, I tried clearing caché, cookies and reseting local storage, the issue continue. On the same computer, using Safari or Chrome, the webpage functions correctly. 

The issue appeared 2 days ago.

### Expected Behavior

Be able to log in.

### Steps To Reproduce

1. Open webpage, I appear offline.
2. Clear cookies, cache, etc.
3. Issue continue.

### Environment

- OS: macOS 13.4.1
- Browser: Arc Browser
- Browser Version: Version 1.1.1 (40415)

**Comment by Miodec** [comment]
Just tested Arc 1.1.1 on MacOS 13.4 - no issues here.

**Comment by Miodec** [comment]
Either way seems like an Arc issue since it works in other browsers?

**Comment by amorino** [comment]
It is resolved now. I didn't do anything, just refreshed today in the morning.

**Comment by pbansal-godaddy** [comment]
I also, got this issue, restarting the browser fixed it for me.
