### ISSUE TITLE
Add an option to revoke all access tokens to the danger zone

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4489]
In case the user wants to deauth all sessions, make a request to the backend and use the admin api to revoke all tokens

**Comment by Warrobot10** [comment]
I would be interested in doing this.

**Comment by Ferotiq** [comment]
@Warrobot10 you still interested in doing this or can I take over?

**Comment by Warrobot10** [comment]
You can take over. Something weird is happening, and I can't commit to my fork. I just don't really understand the backend systems either. Thanks!
