### ISSUE TITLE
Mobile: Monkeytype crashes in both safari and chrome just after crt mode is put on.

### ISSUE THREAD

**Issue by Warrobot10** [monkeytypegame/monkeytype#4496]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Warrobot10

### Account config

{"theme":"paper","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"fast","quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":120,"mode":"words","quoteLength":[0],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"zipf","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When I open monkeytype, whether I’m signed in or out, and turn crt mode on in the fun box, monkeytype crashes. 

### Expected Behavior

When I turn crt on in the fun box, I should be able to use monkeytype with a crt filter on.

### Steps To Reproduce

1. Open monkeytype on safari or chrome on iOS
2. Go into funbox
3. Click on crt mode
4. Monkeytype crashes, and will continue to crash until you clear your cache.

### Environment

- OS: iOS 16.5.1
- Browser: safari + chrome for iOS 
- Browser Version: Chrome v115.0.5790.130 safari 16

### Anything else?

https://github.com/monkeytypegame/monkeytype/assets/132307750/f0d94818-bc11-48f7-9674-7496b14e6909

**Comment by Miodec** [comment]
Looks like something in WebKit doesnt like crt. Let me check android.

**Comment by Miodec** [comment]
Android is fine.

**Comment by Warrobot10** [comment]
What do you think it is?

**Comment by Miodec** [comment]
Absolutely zero clue

**Comment by Warrobot10** [comment]
I can confirm that this issue is no longer present, maybe something to do with something on apples end.
