### ISSUE TITLE
Indicate typos does not work with the option to stop on letter when an error happens

### ISSUE THREAD

**Issue by userrand** [monkeytypegame/monkeytype#4525]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Indicate typos does not work when the option "stop on error">"letters" is on.

### Environment

- OS:
- Browser:edge
- Browser Version:

**Comment by Miodec** [comment]
Working as expected. Input handling is completely stopped when using stop on letter, so indicate typos code is never actually ran.

**Comment by userrand** [comment]
I thank you for your quick response but you could consider suggesting to direct me to the feature suggestion section or to discuss on discord or something rather than stating the behavior is as intended and closing. I understand that you probably have a lot of tasks in a busy day and would like to do them quickly and directly but I am not sure users feedback should be considered as a quick task whose difficulty should be minimized without much further consideration. I imagine that the purpose of having a discord and a Github was to have feedback from users.

**Comment by Miodec** [comment]
Yeah sorry, had a bad day yesterday. Ill see what i can do.

**Comment by userrand** [comment]
> Yeah sorry, had a bad day yesterday. Ill see what i can do.

It's fine (: . It just felt a bit expeditive and I did not want to ignore it if it was something more systematic beyond this particular conversation. It would be fine for me if you said " yeah I am not sure if or when this will be implemented" as I would still feel considered even it was for 0.2 seconds. Hope things were better today or will be a bit more peaceful or easier tomorrow. Thank you again for all of your replies.

**Comment by userrand** [comment]
Quite pleasantly surprised to see the feature has already been added! :partying_face:  

Thank you it looks great!

**Comment by userrand** [comment]
Quite pleasantly surprised to see the feature has already been added! :partying_face:  

Thank you it looks great !

Just that it is a bit hard to see with a black theme.
