### ISSUE TITLE
Allow partial presets

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4532]

**Comment by Miodec** [comment]
When creating a preset, add a popup which asks which settings should be saved (grouped by setting groups, so behavior, input, sound) and so on. Then only apply those settings when applying the preset, leaving the rest unchanged.

**Comment by BurhanP110** [comment]
This sounds really cool,
Why aren't you using the new feature tag ?

**Comment by amarnathsama** [comment]
Hi, can i try this one, is this still valid?

**Comment by Miodec** [comment]
Yeah
