### ISSUE TITLE
Monkeytype about page not working.

### ISSUE THREAD

**Issue by Warrobot10** [monkeytypegame/monkeytype#4547]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Warrobot10

### Current Behavior

When I open the about page, I expect to see the total number of tests taken, how many hours spent type ect. but they never load.

### Expected Behavior

I expected to see the different counts to load.

### Steps To Reproduce

Open about page.
Bug reproduced.

### Environment

- OS: Windows 11
- Browser: Microsoft edge
- Browser Version: 115.0.1901.203

### Anything else?

https://github.com/monkeytypegame/monkeytype/assets/132307750/55d2837c-3a3d-4313-a142-5d7a1dc62cec

**Comment by sleeepstorm** [comment]
I'm getting the issue too, just noticed it right now.
![Screenshot 2023-08-16 15 36 51](https://github.com/monkeytypegame/monkeytype/assets/103459068/1c3b2b1d-d199-44f6-9bce-065018bd4e01)
