### ISSUE TITLE
Issue in leaderboard view while zooming into the browser

### ISSUE THREAD

**Issue by bhanuprakashbahoju** [monkeytypegame/monkeytype#4552]
### Did you clear cache before opening an issue?

- [x] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

kushi6

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":15,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

**Leader board doesn't work well when tried zoom it**

### Expected Behavior

website need to work well for every zooming rate

### Steps To Reproduce

1. Go to https://monkeytype.com
2. Take a quick test so you can get to the results page
3. Open leader board 
4.  Zoom into the browser around 150% minimum( it started at 150% for my 16 inch screen)

### Environment

- OS: Windows 11
- Browser: Brave
- Browser Version: 1.57.47

### Anything else?

Screenshot :  https://drive.google.com/file/d/1rAtpeZ7sn6d3KGNuBVgWUI7WP_SpY86m/view?usp=sharing

**Comment by Miodec** [comment]
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/f5f49b15-e8bf-4a90-98b2-c69220c394ff)

Here's 150%, whats wrong?

**Comment by Miodec** [comment]
Nevermind i missed the screenshot

**Comment by Miodec** [comment]
Im not sure if i can do much about this. Every website will become pretty much unusable if you combine zooming in with a low screen resolution
