### ISSUE TITLE
Escaping characters not being treated as raw string literals in custom mode

### ISSUE THREAD

**Issue by afoalb** [monkeytypegame/monkeytype#4558]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["terminal","serika_dark"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"off","quickRestart":"esc","punctuation":false,"numbers":false,"words":100,"time":30,"mode":"custom","quoteLength":[1],"language":"code_c","fontSize":1.5,"freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"word","showAllLines":true,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

when a custom text contains escaping characters, monkeytype considers it as escaping characters and not as raw strings._

### Expected Behavior

I expect monkeytype to treat the text in custom text as a raw string.

### Steps To Reproduce

1. go to custom and enter the following text: "this \n gives a new line and this \t a tab"
2. press enter. 
3. The text displayed by monkeytype will be: 
      "this
        gives a new line and this       a tab"

### Environment

- OS: windows
- Browser: firefox
- Browser Version: 116.0.2

**Comment by codingmickey** [comment]
Hi @Miodec can I look into this?

**Comment by Miodec** [comment]
Im not sure if this one is doable since newlines and tabs are encoded to \n and \r anyway, but you can give it a shot.
