### ISSUE TITLE
"Failed to save result: Result data doesn't make sense" for japanese hiragana

### ISSUE THREAD

**Issue by ElnuDev** [monkeytypegame/monkeytype#4566]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

Elnu

### Account config

{"theme":"dino","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#272e33","#a7c080","#dbbc7f","#d3c6aa","#1e2326","#f2efdf","#e67e80","#f85552","#e67e80","#f85552"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":30,"mode":"time","quoteLength":[1],"language":"japanese_hiragana","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When logged in, completing tests with the `japanese hiragana` set always gives an error saying "Failed to save result: Result data doesn't make sense"

![image](https://github.com/monkeytypegame/monkeytype/assets/9874955/b9a7e56b-c7e4-4560-a5d7-ff5fef8b722d)

If I switch back to another set and try a test again, the error goes away.

### Expected Behavior

The test result saves without errors.

### Steps To Reproduce

1. Log in
2. Switch set to `japanese hiragana`
3. Complete test

### Environment

- OS: Linux (NixOS)
- Browser: Firefox
- Browser Version: 116.0.1

### Anything else?

The following output is in console after the error appears:

![image](https://github.com/monkeytypegame/monkeytype/assets/9874955/e9bacec9-d264-411d-96c1-41652b661888)

The test result data object is as follows:

```JSON
{
  "wpm": 26.4,
  "rawWpm": 26.4,
  "charStats": [
    66,
    0,
    0,
    0
  ],
  "charTotal": 66,
  "acc": 98.53,
  "mode": "time",
  "mode2": "30",
  "punctuation": false,
  "numbers": false,
  "lazyMode": false,
  "timestamp": 1692598142922,
  "language": "japanese_hiragana",
  "restartCount": 0,
  "incompleteTests": [],
  "incompleteTestSeconds": 0,
  "difficulty": "normal",
  "blindMode": false,
  "tags": [],
  "keySpacing": [
    707,
    408,
    2109,
    1127,
    923,
    1632,
    1385,
    1,
    822,
    361,
    233,
    3103,
    2188,
    1916,
    1229,
    709,
    1286,
    1872,
    2878,
    1015,
    1423
  ],
  "keyDuration": [
    156,
    146,
    138,
    194,
    183,
    106,
    153,
    177,
    131,
    132,
    150,
    157,
    159,
    62,
    157,
    158,
    208,
    184,
    159,
    173,
    178,
    142
  ],
  "keyOverlap": 131,
  "lastKeyToEnd": 2201,
  "startToFirstKey": 474,
  "consistency": 50.53,
  "keyConsistency": 36.65,
  "funbox": "none",
  "bailedOut": false,
  "chartData": {
    "wpm": [
      36,
      30,
      28,
      30,
      31,
      32,
      33,
      30,
      29,
      30,
      31,
      27,
      28,
      29,
      30,
      30,
      30,
      29,
      28,
      27,
      28,
      28,
      28,
      27,
      26,
      26,
      27,
      27,
      27,
      26
    ],
    "raw": [
      48,
      24,
      24,
      36,
      36,
      36,
      36,
      12,
      24,
      36,
      36,
      12,
      24,
      48,
      48,
      24,
      24,
      12,
      36,
      0,
      36,
      24,
      36,
      0,
      0,
      36,
      36,
      36,
      24,
      12
    ],
    "err": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  },
  "testDuration": 30,
  "afkDuration": 0,
  "wpmConsistency": 92.38,
  "uid": "vX87lvqsaAfhasxsJdehgGBAV373",
  "hash": "81e1c5a263ed06e56934e873156dee8bda1576d3"
}
```

**Comment by Miodec** [comment]
Looking at the logs and the result object, youre reporting 22 keypresses, while typing 66 characters. Do you know whats up with that?

**Comment by ElnuDev** [comment]
I'm using the [thumb shift Japanese keyboard layout](https://en.wikipedia.org/wiki/Thumb-shift_keyboard), which uses chording to output characters (a space shift key and a character key are pressed simultaneously to output a single character). That being said, it doesn't explain why the number of keypresses that are being reported is substantially *less* than the characters produced, one would have thought it'd be the opposite. 

This probably should be put under a separate issue, but I wanted to see how monkeytype responds to Japanese typed with normal romaji input (typing Latin characters to output Japanese), but that has problems as well, for a different reason. For example, to type か you have to press `k` then `a`, and then `ka` gets converted by the IME. monkeytype registers the first input of `k` as a mistype, and then breaks the conversion process:

![monkeytype-romaji-fail](https://github.com/monkeytypegame/monkeytype/assets/9874955/24d2c429-2ce9-4ceb-8869-0ee4718dd07a)

**Comment by Miodec** [comment]
Could you go to the browser console, enable debug logs, complete a test, then save the console to a file and send it to me?

Right click > inspect element > console tab > `toggleDebugLogs()` > right click > save as...
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/a09439fc-5fbb-48b2-863d-2de3cbfd2113)

**Comment by ElnuDev** [comment]
https://gist.github.com/ElnuDev/72810db862a271a1166691b643675295

**Comment by ElnuDev** [comment]
> This probably should be put under a separate issue, but I wanted to see how monkeytype responds to Japanese typed with normal romaji input (typing Latin characters to output Japanese), but that has problems as well, for a different reason. For example, to type か you have to press `k` then `a`, and then `ka` gets converted by the IME. monkeytype registers the first input of `k` as a mistype, and then breaks the conversion process:

Regarding the aforementioned issue with romaji input, it's the same issue as #4230. (Separate issue.)

**Comment by Miodec** [comment]
> https://gist.github.com/ElnuDev/72810db862a271a1166691b643675295

Looks like the input handler is completely not reporting keypresses. It doesn't even trigger the `on keyup`, `on keydown` events. This will probably not be fixable, since its not a problem on the website side.

**Comment by Miodec** [comment]
As for the Romanji input, it looks fine on MacOS: 
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/48c58ce3-3b0f-4a87-be0f-546de11feb65)

![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/006c991b-a2b9-464d-a5d3-c1514b0ef401)


So, this looks to be a linux issue (as always)

**Comment by ElnuDev** [comment]
> > https://gist.github.com/ElnuDev/72810db862a271a1166691b643675295
> 
> Looks like the input handler is completely not reporting keypresses. It doesn't even trigger the `on keyup`, `on keydown` events. This will probably not be fixable, since its not a problem on the website side.

Alright, so I just [did a quick test](https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event#examples) with the thumb shift layout and it is registering the `keydown` event for all keystrokes *except* the first character of the composition, for some reason. A better way of detecting keypresses in this context would probably be the [`compositionupdate` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionupdate_event#examples), since it yields only one event per character input (which is nice since chording keypresses aren't registered).

> So, this looks to be a linux issue (as always)

Can't say for romaji input (it's possible that macOS's IME works differently, I'll test on Windows later today), but I don't think it's a Linux issue because at least for the thumb shift layout. From my testing outside of monkeytype, all of the events that are being produced are reasonable. I think the culprit is that monkeytype isn't listening for composition events at all(? I might be wrong about this), and `compositionupdate` should take precedence over `keydown` if one is currently in a composition.

Thanks for the help on this. I haven't worked with TypeScript before but I could try and write a PR to fix this using composition events, and that may or may not close some of the open Chinese input-related issues as well, I'm not sure.

**Comment by RiceKrisBs** [comment]
Just wanted to add because I've started encountering this "Failed to save result: Result data doesn't make sense" error as well, that I don't think it's isolated to `japanese hiragana`. For example, I can reproduce this when typing a short `code python` quote or a short `code go` quote. It doesn't happen with every `code *` quote, but it seems to happen with a decent number of them. At least for these `code *` examples, it almost feels like it could be related to when there are multiple newline or tab characters adjacent to each other within the quote. [Here's](https://gist.github.com/RiceKrisBs/2443a8eeacc6215fa56627dc26de56ec) the debug logs for a short `code go` quote that also results in the error.

**Comment by Miodec** [comment]
> > > https://gist.github.com/ElnuDev/72810db862a271a1166691b643675295
> > 
> > 
> > Looks like the input handler is completely not reporting keypresses. It doesn't even trigger the `on keyup`, `on keydown` events. This will probably not be fixable, since its not a problem on the website side.
> 
> Alright, so I just [did a quick test](https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event#examples) with the thumb shift layout and it is registering the `keydown` event for all keystrokes _except_ the first character of the composition, for some reason. A better way of detecting keypresses in this context would probably be the [`compositionupdate` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionupdate_event#examples), since it yields only one event per character input (which is nice since chording keypresses aren't registered).
> 
> > So, this looks to be a linux issue (as always)
> 
> Can't say for romaji input (it's possible that macOS's IME works differently, I'll test on Windows later today), but I don't think it's a Linux issue because at least for the thumb shift layout. From my testing outside of monkeytype, all of the events that are being produced are reasonable. I think the culprit is that monkeytype isn't listening for composition events at all(? I might be wrong about this), and `compositionupdate` should take precedence over `keydown` if one is currently in a composition.
> 
> Thanks for the help on this. I haven't worked with TypeScript before but I could try and write a PR to fix this using composition events, and that may or may not close some of the open Chinese input-related issues as well, I'm not sure.

The input system is hell in general, because every operating system, browser and layout does something different. You change one thing, the rest breaks. You fix those, you break what you added. Its really hard to cover all bases and i've been honstly slowly losing hope its even possible to make it work for everyone, without making major sacrifices *somewhere*.

For example, `compositionupdate` cant take priority over `keydown` because on MacOS, the `keydown` event doesnt even know that composition has begun (because the `compositionstart` is fired after it)

![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/3b24506d-d063-484b-9a26-ea4ac026d08a)

**Comment by Miodec** [comment]
> Just wanted to add because I've started encountering this "Failed to save result: Result data doesn't make sense" error as well, that I don't think it's isolated to `japanese hiragana`. For example, I can reproduce this when typing a short `code python` quote or a short `code go` quote. It doesn't happen with every `code *` quote, but it seems to happen with a decent number of them. At least for these `code *` examples, it almost feels like it could be related to when there are multiple newline or tab characters adjacent to each other within the quote. [Here's](https://gist.github.com/RiceKrisBs/2443a8eeacc6215fa56627dc26de56ec) the debug logs for a short `code go` quote that also results in the error.

Whats the account name? This could be something else, that error is not always refering to key data.

**Comment by RiceKrisBs** [comment]
> > Just wanted to add because I've started encountering this "Failed to save result: Result data doesn't make sense" error as well, that I don't think it's isolated to `japanese hiragana`. For example, I can reproduce this when typing a short `code python` quote or a short `code go` quote. It doesn't happen with every `code *` quote, but it seems to happen with a decent number of them. At least for these `code *` examples, it almost feels like it could be related to when there are multiple newline or tab characters adjacent to each other within the quote. [Here's](https://gist.github.com/RiceKrisBs/2443a8eeacc6215fa56627dc26de56ec) the debug logs for a short `code go` quote that also results in the error.
> 
> Whats the account name? This could be something else, that error is not always refering to key data.

My account name on Monkeytype is ricekrisbs.

**Comment by Miodec** [comment]
@RiceKrisBs  Any chance you could join the Discord and message the #bugs-and-support channel? We could do some testing

discord.gg/monkeytype

**Comment by ElnuDev** [comment]
> > > > https://gist.github.com/ElnuDev/72810db862a271a1166691b643675295
> > > 
> > > 
> > > Looks like the input handler is completely not reporting keypresses. It doesn't even trigger the `on keyup`, `on keydown` events. This will probably not be fixable, since its not a problem on the website side.
> > 
> > 
> > Alright, so I just [did a quick test](https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event#examples) with the thumb shift layout and it is registering the `keydown` event for all keystrokes _except_ the first character of the composition, for some reason. A better way of detecting keypresses in this context would probably be the [`compositionupdate` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionupdate_event#examples), since it yields only one event per character input (which is nice since chording keypresses aren't registered).
> > > So, this looks to be a linux issue (as always)
> > 
> > 
> > Can't say for romaji input (it's possible that macOS's IME works differently, I'll test on Windows later today), but I don't think it's a Linux issue because at least for the thumb shift layout. From my testing outside of monkeytype, all of the events that are being produced are reasonable. I think the culprit is that monkeytype isn't listening for composition events at all(? I might be wrong about this), and `compositionupdate` should take precedence over `keydown` if one is currently in a composition.
> > Thanks for the help on this. I haven't worked with TypeScript before but I could try and write a PR to fix this using composition events, and that may or may not close some of the open Chinese input-related issues as well, I'm not sure.
> 
> The input system is hell in general, because every operating system, browser and layout does something different. You change one thing, the rest breaks. You fix those, you break what you added. Its really hard to cover all bases and i've been honstly slowly losing hope its even possible to make it work for everyone, without making major sacrifices _somewhere_.
> 
> For example, `compositionupdate` cant take priority over `keydown` because on MacOS, the `keydown` event doesnt even know that composition has begun (because the `compositionstart` is fired after it)
> 
> ![image](https://user-images.githubusercontent.com/13181393/262953984-3b24506d-d063-484b-9a26-ea4ac026d08a.png)
> 
> Edit: And Safari does something completely different:
> 
> ![image](https://user-images.githubusercontent.com/13181393/262955749-ae69f305-011a-44a8-8f9b-df0d0bfc8962.png)

Man, that really sucks. It really would be nice if things were more standardized, because trying to handle every OS/IME/browser combination sounds like a nightmare.

What about having a "composition mode" that's possible to enable in the settings where standard keypress events are ignored completely, then?

I might try to make a userscript at some point that intercepts events and fixes them to be in a format the monkeytype is okay with, at least for my setup.

**Comment by Miodec** [comment]
> What about having a "composition mode" that's possible to enable in the settings where standard keypress events are ignored completely, then?

This would mean part of the result data validation would be omitted, meaning people could just always enable this special mode, and have less hoops to have to jump through (when trying to cheat)

**Comment by Miodec** [comment]
Alright, in the end i decided to disable that one problematic check for japanese (and other languages) - results should save now.

**Comment by ElnuDev** [comment]
Seems to be working now! Thanks for all the help.
