### ISSUE TITLE
Characters are treated incorrectly in custom mode

### ISSUE THREAD

**Issue by Reyuki-san** [monkeytypegame/monkeytype#4568]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

ReYuki

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":30,"mode":"custom","quoteLength":[0],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

The weird behavior occurs on these section:
![image](https://github.com/monkeytypegame/monkeytype/assets/126035476/a74c66a3-0977-4ee6-b3d2-a106915f6ee5)
![image](https://github.com/monkeytypegame/monkeytype/assets/126035476/90fd104b-6baa-4695-bf61-99b8293c28b1)
![image](https://github.com/monkeytypegame/monkeytype/assets/126035476/e0e8d4c2-7d5f-4575-b942-d6aa29c6b082)

### Expected Behavior

Character treated correctly.

### Steps To Reproduce

1. Go to Monkeytype site
2. Set text to custom mode
3. Paste the custom text
4. Save it
5. Load it
6. Play it
7. Unexpected behavior occurs.

### Environment

- OS: Windows
- Browser: Chrome
- Browser Version: 115.0.5790.173 

### Anything else?

Here are the lyrics I copied from [genius.com](https://genius.com/Amalee-hacking-to-the-gate-from-steins-gate-lyrics) and modified into:

There are billions of beating hearts
And their numbers you'd never count
'Cause to you they are insignificant little lights, flickering, not worth your time
Whether we are stuck in the past or lamenting what's still ahead
Can't miscalculate, there's no room for any mistakes with a delicate fate

Before our eyes are many futures and dreams
Expanding infinitely but the vanity of our privileges
Is it wasted on you and me? Hands of thе clock
They point to answers in sight, the factor only finitе
Toward a brand new fate of a crueler make
But now it's too late, we're hacking to the gate

In this moment, I'm flying and crossing between
A new world, each second I break the seam
And I'll cross the line if it means I'd protect that smile of yours
So now once again, if there's a way we can meet
In a loop devoid of misery, I'm destined to only observe
Loneliness engulfing all of me

Claims of life are all meaningless, nonsensical evidence 'cause to you they're worth
Little more than average delights to amuse and pass the time
Ruling over a foolish realm, a leader crowning themselves
Your conceited ways make your theories crumble away
Like they're child-made

We have been shown the freedom of many things
Expanding infinitely but beyond the sky there's a flow of time
And it beckons to you and me, so merciless
The endless passage of time, the answer only finite
Toward a brand new fate, it's the choice you make
Tomorrow awaits, we're hacking to the gate

I cannot pretend there's not a promise I made
To my friends back in those shining days
I'll never let it fade away, I will fight on for their sake
For that reason I'll use this device as I need
It's the layers of time I will deceive once destined to only observe
But now fate's no power over me

In this moment, I'm flying and crossing between
A new world, each second I break the seam
And I'll cross the line if it means I'd protect that smile of yours
So now once again, if there's a way we can meet
In a loop devoid of misery, I'm destined to only observe
Loneliness engulfing all of me

**Comment by Miodec** [comment]
Looks like this text includes some weird space characters, should be easy fix
https://www.compart.com/en/unicode/U+2005

**Comment by Reyuki-san** [comment]
Thanks for your reference; it cleared up my confusion.

**Comment by Reyuki-san** [comment]
it seems the normal e (U+0065) differs from another е (U+0435)
