### ISSUE TITLE
UI Issue: Twitter logo need to be updated.

### ISSUE THREAD

**Issue by EngHasanSabbir** [monkeytypegame/monkeytype#4572]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

HasanSabbir

### Account config

On April 2023 Twitter has been updated their new logo. They remove their old tropical bird logo, and they update it with a new 'X' logo. MonkeyType Used Twitter old bird logo. I feel it's important to mention it to monekytype and aware them about it. So it's not an actual bug, but it's important to keep UI updated.

### Current Behavior

![image](https://github.com/monkeytypegame/monkeytype/assets/60088050/e6e5d02d-0733-4430-ae7c-3d15bb093178)

### Expected Behavior

![image](https://github.com/monkeytypegame/monkeytype/assets/60088050/e34c74aa-e36c-4cf5-8136-f17a1b896feb)

### Steps To Reproduce

1. Go to the 'https://monkeytype.com/'
2. Scroll to footer
3. On the bottom-left there are some social media icon 
4.  there is twitter old bird logo which can be updated as new 'X' logo.
![image](https://github.com/monkeytypegame/monkeytype/assets/60088050/f9f74bdf-e423-4377-b0ed-bcd4a4af9fc4)

### Environment

- OS:
- Browser:
- Browser Version:

### Anything else?

You can check this out and labels it or ignore it. But I feel it's important to be aware about this.

**Comment by Miodec** [comment]
We are using font awesome, and so far they havent updated the logo.

Plus, i prefer the bird :)
