### ISSUE TITLE
The "rAnDoM cAsE" feature is not functioning as expected. It appears that the character casing is changing with every other character, which is not consistent with the intended behavior.

### ISSUE THREAD

**Issue by visheshrwl** [monkeytypegame/monkeytype#4583]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

visheshrwl

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
Please actually fill out the issue template. The title itself is not enough to describe what the bug is.
