### ISSUE TITLE
Failing Discord CDN causes extremely long account icon, profile, and leaderboard loading times

### ISSUE THREAD

**Issue by cubedhuang** [monkeytypegame/monkeytype#4599]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

dnaiel

### Current Behavior

The Discord CDN is blocked at my school, and because the response to fetch a user's avatar fails, anything that needs to request the Discord CDN takes an extremely long time (>10s) to load.

When loading profiles, loading the account button, or loading the leaderboard, the code uses [`Misc.getDiscordAvatarUrl`](https://github.com/monkeytypegame/monkeytype/blob/4d335e24ee46c90e0b67b360a2713f229430b425/frontend/src/ts/utils/misc.ts#L1357-L1358) to determine whether the avatar is still a valid Discord profile picture [to display placeholder images and whatnot properly](https://github.com/monkeytypegame/monkeytype/blob/4d335e24ee46c90e0b67b360a2713f229430b425/frontend/src/ts/elements/account-button.ts#L116-L123). However, while the request to Discord's CDN is being made, it **completely blocks** anything from loading until the request fails or succeeds. In my case, because the blocked request takes a very long time to fail, anything that requires this needs to wait for that entire time before rendering.

This is also probably bad because your frontend rendering waterfalls since it relies on _Discord's_ response time, which you have no control over.

### Expected Behavior

The easiest solution is probably to always use the URL whether or not the image exists on Discord's CDN (don't make the fetch before displaying the account button or other people's profile information), and provide a different way to fall back. I'm not familiar enough with the codebase to make that change, so I'm making this issue.

### Steps To Reproduce

There's not really an easy way to reproduce this since it relies on the network being unable to make a request to Discord's CDN yet also the request not failing immediately.

### Environment

- OS: Windows 10
- Browser: Edge
- Browser Version: 116

**Comment by Miodec** [comment]
Good find, big boo boo on our part. Gonna make them async now.
