### ISSUE TITLE
Filter preset cannot be saved

### ISSUE THREAD

**Issue by weensy** [monkeytypegame/monkeytype#4612]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

weensy

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":25,"time":15,"mode":"words","quoteLength":[0,1,2,3],"language":"korean","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","accountChart":["on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

After setting the filter on the account page, save the filter preset.
Then a filter preset is added. But, if I refresh the page, all presets disappear.

### Expected Behavior

Whether we move the page, refresh, or log out and log in, the added presets must remain.

### Steps To Reproduce

1. Go to account page
2. Set any filter
3. Click "save as preset"
4. Click "add"
5. Refresh page

### Environment

- OS: MacOS 13.5.1
- Browser: Google Chrome
- Browser Version:  116.0.5845.110 (Official Build) (arm64)

**Comment by theabhayprajapati** [comment]
Hey i am interested in solving but can i know which filter are you taking about like here i cannot find any filter (named) option
[Screencast from 2023-09-10 09-52-37.webm](https://github.com/monkeytypegame/monkeytype/assets/88815641/f4669671-6b1b-4652-9cec-ca615145997b)

let me if I tried to reproduce in the wrong manner, also if you can update a video of it where is getting reproduced that would be helpful.

**Comment by MrFootwork** [comment]
I experience the same issue. You can save filter presets in the filter section of your account settings.

<img width="826" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/66787998/bb32d159-8c23-4009-917e-034d069d38ee">

In fact, after I saved my presets and realised they were gone the other day I just recreated the presets. Only to find out, that they wouldn't be displayed after a page refresh. Now I cannot create presets anymore because I exceeded the maximal amount of presets per user...

![image](https://github.com/monkeytypegame/monkeytype/assets/66787998/f9c5d03d-d718-40d5-adfc-cfba94a6899b)

So my presets seem to be hidden somewhere but a page reload wouldn't fetch/display them correctly.
