### ISSUE TITLE
Persistent Caps Lock message while not typing

### ISSUE THREAD

**Issue by MuriloUnten** [monkeytypegame/monkeytype#4628]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Kenj1

### Current Behavior

The caps lock message does not disappear upon turning off caps lock. 

### Expected Behavior

The caps lock message should disappear upon turning off caps lock.

### Steps To Reproduce

1. Focus the typing section.
2. Press Caps Lock (the caps lock message appears.)
3. Press Caps Lock again (the message blinks but stays active until you type something.)

### Environment

- OS: Linux
- Browser: Brave Browser
- Browser Version: 1.57.57 - Chromium 116.0.5845.163.

### Anything else?

This bug was successfully reproduced on Arch, Fedora, Mint and Lubuntu.
This bug was NOT successfully reproduced on other browsers on Linux nor on Windows in any browser.

The bug described in the issue [Persistent Caps Lock Message #4330](https://github.com/monkeytypegame/monkeytype/issues/4330) seems to not have been solved in these conditions.

**Comment by Warrobot10** [comment]
Does the bug appear on plain chromium on Linux, or only on brave? Sounds like it may be browser specific.

**Comment by MuriloUnten** [comment]
Just tried it on Chromium and managed to reproduce it.

I did some more testing and noticed that when I turn caps lock on and off, the message shows up and doesn't go away, then if you press it again but hold the key, the message disappears until you release caps lock.
Also, the message only pops up when you RELEASE the caps lock key, though caps lock is turned on the moment you press it.
Maybe the bug has something to do

**Comment by MuriloUnten** [comment]
Just tried it on Chromium and managed to reproduce it.

I did some more testing and noticed that when I turn caps lock on and off, the message shows up and doesn't go away, then if you press it again but hold the key, the message disappears until you release caps lock.
Also, the message only pops up when you RELEASE the caps lock key, though caps lock is turned on the moment you press it.
On the other hand, caps lock is turned off when you release the key.

Maybe the bug has something to do with that, but I'm not sure.

**Comment by Warrobot10** [comment]
I will test on my Linux machine when I have time to confirm, thanks for the info!

**Comment by Warrobot10** [comment]
I was able to test it on my linux machine, windows machine and mac, and can confirm that the issue is confined to chromium-based browsers on linux. I am going to look through the code and hopefully find a fix.
Thanks for the help!

**Comment by Warrobot10** [comment]
8000585 was meant to fix the issue, but it isn't working anymore. I think this means that older versions of the distros that have the bug today, worked 3 months ago. @Miodec? Any suggestions?

**Comment by fehmer** [comment]
Test: 
```html
<html>
<script>
    function testCapsLock(event, name) {
    if(event.code === "CapsLock"){
        let isCapsLockOn = event.getModifierState("CapsLock");
        if(isCapsLockOn) {
            console.log("Caps Lock turned on @", name);
        } else {
            console.log("Caps Lock turned off @", name);
        }
        }
    }

    document.addEventListener("keydown", e=> testCapsLock(e, "keydown"));
    document.addEventListener("keyup", e=> testCapsLock(e, "keyup"));
</script>
</html>
```

Pressing caps-lock tree times, initial state is capslock=off.

Chrome/Windows
```
Caps Lock turned on @ keydown
Caps Lock turned on @ keyup
Caps Lock turned off @ keydown
Caps Lock turned off @ keyup
Caps Lock turned on @ keydown
Caps Lock turned on @ keyup
```

Chrome/Linux
```
Caps Lock turned off @ keydown
Caps Lock turned on @ keyup
Caps Lock turned on @ keydown
Caps Lock turned on @ keyup
Caps Lock turned off @ keydown
Caps Lock turned on @ keyup
```
