### ISSUE TITLE
Bio & Keyboard details on profile overflowing

### ISSUE THREAD

**Issue by CarterBrehm** [monkeytypegame/monkeytype#4635]
Related to [#4255](https://github.com/monkeytypegame/monkeytype/issues/4255)
 This bug is back again, even with the CSS fix... running:
- macOS Ventura 13.5.2 (22G91)
- Safari Version 16.6 (18615.3.12.11.2)

I will note that the bug seems to only occur when I'm on my own profile (`/account`):
<img width="1002" alt="CleanShot 2023-09-14 at 12 08 02@2x" src="https://github.com/monkeytypegame/monkeytype/assets/26262673/3a075dbe-7990-4781-ada3-bea8d2da0795">

The bug does not appear when I go incognito and view my profile permalink (`/profile/Ozrukar`):
<img width="1215" alt="CleanShot 2023-09-14 at 12 09 58@2x" src="https://github.com/monkeytypegame/monkeytype/assets/26262673/f98541bc-9bfc-45bf-af03-d49c4a204e9f">

Even manually shrinking the window to try to force line breaks seems to be handled correctly, with the text resizing:
<img width="713" alt="CleanShot 2023-09-14 at 12 11 47@2x" src="https://github.com/monkeytypegame/monkeytype/assets/26262673/af5b1f19-119f-4b88-8a68-440677b0445a">

**Comment by yashnirmal** [comment]
on it

**Comment by yashnirmal** [comment]
It seems to be a safari specific issue, bcz its working correctly on other browsers

**Comment by Warrobot10** [comment]
> It seems to be a safari specific issue, bcz its working correctly on other browsers

False, issue is present on windows and Linux or different browsers, such as edge, brave etc.

**Comment by Miodec** [comment]
Not happening on MacOS 13.4 and Safari 16.5

**Comment by Miodec** [comment]
Nevermind, i got it. Account page and profile page seem to be using different css.
