### ISSUE TITLE
Bug: Able to type out words before test begins

### ISSUE THREAD

**Issue by rsashank** [monkeytypegame/monkeytype#4641]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Allows users to pre-type words while the cookies popup is active, and upon closing the popup and starting the test, provides a head start by showing and calculating the pre-typed words as completed.

### Expected Behavior

Disallow typing while cookies popup is shown.

### Steps To Reproduce

1. Launch an Incognito window.
2. Allow the cookies popup to appear.
3. Type the visible words.
4. Close the cookies popup.
5. Start typing again, it'll show that the words typed while the cookie popup appeared are already typed.

### Environment

- OS: 
- Browser:
- Browser Version:

**Comment by charlielidstone** [comment]
Can I please work on this?

**Comment by Miodec** [comment]
@charlielidstone sorry, i've decided to quickly fix it as it was a one line fix
