### ISSUE TITLE
Validate edit profile requests for length before sending to the server

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4653]

**Comment by sanidhyas3s** [comment]
Details for this and where should I look in the code for this?

**Comment by rajeshias** [comment]
There is only server validation as of now. I tested and found out for each fields

Bio  <= 250 Chars
Keyboard <= 75 Chars
Github <= 39 Chars
Twitter <= 20 Chars
Website <= passes through a URI regex check 

Having an extra layer of validation in frontend is always time saving and good practice

@Miodec Any form validation practices that you guys are interested in?

**Comment by Miodec** [comment]
@rajeshias would you like to open a PR or should i make this change?

**Comment by rajeshias** [comment]
I would love to. Can you assign this to me?

**Comment by sanidhyas3s** [comment]
if no work is done on this yet, I can get this done and try to put a PR quickly
