### ISSUE TITLE
Commandline: Scroll selected element into view when opening

### ISSUE THREAD

**Issue by JayTailor45** [monkeytypegame/monkeytype#4662]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

JayTailor45

### Current Behavior

While clicking on language selector, the selected language doesn't scroll into the view.

https://github.com/monkeytypegame/monkeytype/assets/30929568/e63e90a8-4285-4da9-bd2a-94bd2687ca25

### Expected Behavior

While clicking on language selector, the selected language should scroll into the view. It seems like a good quality of life improvement.

### Steps To Reproduce

1. Go to [monkeytype](https://monkeytype.com) site
2. Click on language selector
3. Select `russian` language
4. Click on language selector once again
5. Notice selected language doesn't scroll into view

### Environment

- OS: Ubuntu 22.04.3 LTS
- Browser: Google Chrome
- Browser Version: 117.0.5938.88 (Official Build) (64-bit)

**Comment by Miodec** [comment]
Not really a bug, it was never meant to scroll into view - I've converted the bug into an improvement issue.

**Comment by JayTailor45** [comment]
@Miodec Thank you for the info. I have already made changes. Please review my [changes](https://github.com/monkeytypegame/monkeytype/pull/4663) and let me know if any changes requires.
