### ISSUE TITLE
Escaping characters not being treated as raw string literals in quote mode

### ISSUE THREAD

**Issue by LamberlainMuli** [monkeytypegame/monkeytype#4674]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

rebmal_proper

### Current Behavior

![image](https://github.com/monkeytypegame/monkeytype/assets/109662687/7f583ce3-fd50-4df9-b879-f3d48950e42e)

I infer that the character that needs to be typed is "\n". However, a literal new line is instead shown. This also happens with tab "\t". In general the bug happens when the data for quotes contains special characters (those who are an escape sequence).

### Expected Behavior

The expected behavior is that the "\n" in the data should be typed character by character as '\'+ 'n' and not a literal new line. In general, escape sequences in quotes must be typed character by character and not executed as their representation. 

### Steps To Reproduce

1. Change language to any coding language ( in my case c++)
2. Select mode as quote
3. Type/reset a lot until you see an  escape sequence in the quote  (reset until you see my example which is a new line) 

![image](https://github.com/monkeytypegame/monkeytype/assets/109662687/400a4c0e-8538-4008-9905-788af0947f9b)
![image](https://github.com/monkeytypegame/monkeytype/assets/109662687/d8e781b1-5766-4c1e-b452-a7ef3a44ba52)

### Environment

- OS: Windows 10
- Browser: Google Chrome 
- Browser Version: 117.0.5938.92 (Official Build) (64-bit)

### Anything else?

https://en.cppreference.com/w/cpp/language/escape

**Comment by aikooo7** [comment]
Hello @LamberlainMuli , you expect it to be like this?

void print(const Student &s) {
    cout << s.name << "   " << s.address << "  " << s.rollNo << \n
}

I'm not really understand how you want it to be "printed" on the website.

Regards,
aikoo7.

**Comment by LamberlainMuli** [comment]
> Hello @LamberlainMuli , you expect it to be like this?
> 
> void print(const Student &s) {
>     cout << s.name << "   " << s.address << "  " << s.rollNo << \n
> }
> 
> I'm not really understand how you want it to be "printed" on the website.
> 
> Regards,
> aikoo7.

I expect it to be printed as:

> void print(const Student &s) {
>     cout << s.name << "   " << s.address << "  " << s.rollNo << '\n';
> }

**Comment by aikooo7** [comment]
Hello @LamberlainMuli thanks a lot for your help full answer, I will fix it shortly

**Comment by aikooo7** [comment]
Hey @LamberlainMuli I'm going to update in this situation:

I was able to make it be like so:

```
void print(const Student &s) {
cout << s.name << " " << s.address << " " << s.rollNo << \
n ; }
```

But for some reason any try to print a new line character doesn't work and no other c++ quotes is showing any, maybe some contributor can help? (@Miodec)

My take is that when it sees a new line character it goes to a new line no matter what.

Let me know if you like this way:

```
cout << s.name << " " << s.address << " " << s.rollNo; }
```

**Comment by LamberlainMuli** [comment]
Is it not possible to turn "\n" to "\\n"?

**Comment by aikooo7** [comment]
> Is it not possible to turn "\n" to "\n"(with double backlash)?

Nope, if I do \\n it does the same, the unique way of display it is doing ///n but then it does something like this:

```
std::cout << "We love placeholders"
/n;
```
