### ISSUE TITLE
Input history displayed the wrong one / Keymap resets to off after a game

### ISSUE THREAD

**Issue by Waterdragen** [monkeytypegame/monkeytype#4676]
### Did you clear cache before opening an issue?

- [x] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

waterdragen
https://monkeytype.com/profile/Waterdragen

### Current Behavior

Input history
- displaying a previous input instead of the current one
- that particular input does not change
- (affected in both normal and incognito)

Keymap (?)
- does not display keymap after a match even though keymap is set to `react`
- set keymap to `off` then to `react` restores the keymap for the next game
- after that game is finished, keymap does appear in the new game
- (worked fine in incognito, but sometimes not in normal)

(both not affected by logging in/out)

### Steps To Reproduce

Input history
- finish 2 games

Keymap
- go to `settings` > `appearances` > `keymap`
- set `keymap` to `react`
- (set to `colemak-dh-matrix`)
- finish a game
- start a new game

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 117.0.5938.132 (Official Build) (64-bit)

### Anything else?

![Screenshot (17)](https://github.com/monkeytypegame/monkeytype/assets/96000090/0f2ed0c7-4f02-47c6-a404-6fa91c9cfe71)
the input history doesn't match the replay

**Comment by aikooo7** [comment]
Hello @Waterdragen I was able to reproduce your bug but what a change bug, in html it shows one thing but when you click to copy the history it copies the right one.

Note to my self: Mostly html problem
