### ISSUE TITLE
There is an scroll bar without having scrolling content

### ISSUE THREAD

**Issue by Miltonbhowmick** [monkeytypegame/monkeytype#4690]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

No

### Account name

This issue does not depend on any account related.

### Current Behavior

![monkeytype issues](https://github.com/monkeytypegame/monkeytype/assets/16919385/ed21458f-ea7e-498f-aaea-900127c37172)

In the home page, there is an extra scroll bar having initially without any scrolling content in the page.

### Expected Behavior

It should be auto scroll bar.

### Steps To Reproduce

1. Go to "Homepage"
2. Look on the right top to bottom of the page
3. You will see a space.

### Environment

- OS: Windows
- Browser: Google Chrome
- Browser Version: Version 117.0.5938.132 (Official Build) (64-bit)

### Anything else?

Nothing else. If i find any issue, i will drop in this amazing project.

**Comment by Miodec** [comment]
Intended. This is there to make sure the content doesn't jump when the scrollbar appears or disappears.
