### ISSUE TITLE
Funbox Nausea

### ISSUE THREAD

**Issue by ElsdonC** [monkeytypegame/monkeytype#4719]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

SPACESHIP

### Current Behavior

nav and footer are rotated by 5 degrees.

### Expected Behavior

Expected nav and footer to be non-rotated.

### Steps To Reproduce

1. Go to https://monkeytype.com/settings
2. Scroll down to funbox
3. Select nausea
4. Go back to https://monkeytype.com

### Environment

- OS: Windows 11
- Browser: Google Chrome
- Browser Version: Version 117.0.5938.150 (Official Build) (64-bit)

### Anything else?

<img width="790" alt="funbox nausea issue" src="https://github.com/monkeytypegame/monkeytype/assets/67447710/36fcab7c-e176-49d0-95da-824229df9c56">

**Comment by Miodec** [comment]
Thats the point of the nausea funbox - this is not a bug.
