### ISSUE TITLE
Latency in the sound of typing

### ISSUE THREAD

**Issue by aniketsharmaa** [monkeytypegame/monkeytype#4725]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

No

### Account name

aniket__sharma_

### Current Behavior

The sound of typing usually comes after I’ve typed 2-3 words. 
latency in sound

![image](https://github.com/monkeytypegame/monkeytype/assets/70125144/800ba490-2b96-410c-8d64-203120309d45)
![image](https://github.com/monkeytypegame/monkeytype/assets/70125144/7b979e56-5170-4511-92a3-cec3d22c8319)

### Expected Behavior

sound should start as typing started.

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Hattorius** [comment]
I'm unable to replicate the issue on Chromium version 118.0.5993.70, and I've also tested it on Safari version 18615.3.12.11.2, but the problem doesn't seem to occur on either browser.

**Comment by Miodec** [comment]
@aniketsharmaa are you using bluetooth headphones / speakers?

**Comment by aniketsharmaa** [comment]
@Miodec Yes. oppo enco buds 2

**Comment by sanidhyas3s** [comment]
> @Miodec Yes. oppo enco buds 2

Wireless earphones have unavoidable delay, please ensure they aren't the reason for the latency which made you create the issue.

**Comment by Miodec** [comment]
Yes, im afraid this is not an issue with the website.

**Comment by Miodec** [comment]
@aniketsharmaa It only happens when logged in?
