### ISSUE TITLE
"Watch video ad" does nothing on Firefox 118

### ISSUE THREAD

**Issue by ItsCryptic** [monkeytypegame/monkeytype#4727]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

itscryptic1

### Current Behavior

In the support tab, clicking on "Video Ad" does nothing but will close the model

### Expected Behavior

Video ad should play a video

### Steps To Reproduce

1. Go to the 'i'
2. Click on 'Support'
3. Click "Watch Video Ad

This should close the model, but play no video 

### Environment

- OS: Windows 11 
- Browser: Firefox
- Browser Version: 118

**Comment by ItsCryptic** [comment]
I can reproduce this on Google Chrome 118.0.5993.71

**Comment by Hattorius** [comment]
I've just investigated this matter. It appears that Brave, which also uses the same Chromium version, is experiencing the same issue. Additionally, Safari failed to load an ad video as well. Notably, Brave displays an HTTP 451 error related to kargo.com, which I presume is the video provider.

Can reproduce
