### ISSUE TITLE
Advertising Privacy Settings link/button doesn't do anything

### ISSUE THREAD

**Issue by Wrestor** [monkeytypegame/monkeytype#4738]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Hermes

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":false,"smoothCaret":"medium","quickRestart":"tab","punctuation":false,"numbers":false,"words":50,"time":15,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

In the Privacy Policy of Monkey type > Advertisements Part 2 > Advertising Privacy Settings, one is unable to revisit or change consent-choices by clicking the appropriate URL/Button

### Expected Behavior

To be able to revisit or change consent-choices by clicking the appropriate URL/Button

### Steps To Reproduce

1. Go to https://monkeytype.com/privacy-policy#Advertisements2
2. Under _Advertising Privacy Settings_, for EU Users only, click on "[here](https://monkeytype.com/privacy-policy#tcfapi)"

### Environment

- OS: macOS Sonoma Version 14.0 (23A344)
- Browser: Google Chrome
- Browser Version: Version 118.0.5993.96 (Offizieller Build) (arm64)

### Anything else?

<img width="977" alt="Bildschirmfoto 2023-10-24 um 01 09 12" src="https://github.com/monkeytypegame/monkeytype/assets/54822494/58623d92-46fa-42be-b274-63abfdb25196">

**Comment by Warrobot10** [comment]
Can confirm this issue,

**Comment by Hattorius** [comment]
Can reproduce as well

**Comment by Miodec** [comment]
Just waiting on the response from the advertising partner about how to fix, thanks for the report.

**Comment by ayush02dev** [comment]
can you tell me more about this issue that issus @Miodec

**Comment by ayush02dev** [comment]
should we remove [Advertisements Part 2] or add description for it @RevENGE-code

**Comment by RevENGE-code** [comment]
> should we remove [Advertisements Part 2] or add description for it @RevENGE-code 

What?

**Comment by Warrobot10** [comment]
> can you tell me more about this issue that issus @Miodec

This issue is not fixable on “our” end, but miodec has gotten in contact with the company that serves the ads.

> should we remove [Advertisements Part 2] or add description for it @RevENGE-code

No.
