### ISSUE TITLE
Issues with UK English mode for quotes

### ISSUE THREAD

**Issue by Ontonator** [monkeytypegame/monkeytype#4747]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Ontonator

### Current Behavior

The current method of replacing US spellings with UK ones doesn't (and fundamentally can't) work properly for quotes due to fact that for some words US English has a single spelling where in UK English there are two. One example (which comes up in quote 4763) is "practice". In UK English, when used as a verb it is spelled "practise", but when used as a noun it is spelled "practice".

### Expected Behavior

Quotes should have an optional `britishText` attribute (or something similar) to override the automatic conversion to British English. This could be omitted for most quotes so as to not require any extra effort in most cases and to avoid bloating the quotes file.

### Steps To Reproduce

1. Set the language to English with British English set to true.
2. Go to quote 4763.

### Environment

- OS: Linux
- Browser: Firefox
- Browser Version: 119.0 (64-bit)

### Anything else?

https://en.wiktionary.org/wiki/practice (see Usage Notes section)

**Comment by Miodec** [comment]
Is this the correct British english version?
```
We often believe the more we practise a skill or technique - over and over again, many times - the better we'll get. This is not necessarily true. In fact, every time you practise a technique incorrectly, you're increasing your chances of doing it wrong again. It's easy to become very experienced at repeating the same mistakes. Practice doesn't make perfect; only perfect practice makes perfect.
```

**Comment by Ontonator** [comment]
Yes, that looks right.
