### ISSUE TITLE
Replace sound volume settings with a slider

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4764]

**Comment by sanidhyas3s** [comment]
I am interested in solving this. As far as I can see, there doesn't exist a slider template yet for any setting, so I am working on creating one. Will update once done!

**Comment by Miodec** [comment]
Sliders already exist for the custom background filters @sanidhyas3s

**Comment by Miodec** [comment]
Make sure to add a custom background image url and the sliders will appear.

**Comment by sanidhyas3s** [comment]
Ok, on it!

**Comment by sanidhyas3s** [comment]
Unassigning myself as I am not able to give this time and also not able to solve it within the time I am able to give, so making it free for anyone else to solve while I can't. If I am attempting this later in the future I'll let know.

**Comment by ryantang35** [comment]
Can I try this one?

**Comment by joaorodrs** [comment]
Seems like @ryantang35 couldn't find time to finish the review adjustments, can I finish this one?
@Miodec

**Comment by Miodec** [comment]
> It seems like @ryantang35 couldn't find time to finish the review adjustments, can I finish this one?
> 
> @Miodec 

Sure

**Comment by amarnathsama** [comment]
Hi, look like @joaorodrs is not working on this anymore, is it ok if i give it a try?
