### ISSUE TITLE
 Lazy mode should be enabled by default for Arabic

### ISSUE THREAD

**Issue by larrasket** [monkeytypegame/monkeytype#4765]
@Miodec Lazy mode should be enabled by default for Arabic, the current default makes it impossible to use the site to practice Arabic, also this setting should be in the top row of the main page if has to exist at all

_Originally posted by @mshwf in https://github.com/monkeytypegame/monkeytype/issues/3648#issuecomment-1332583096_

**Comment by Miodec** [comment]
..fine
