### ISSUE TITLE
Add API response types to the frontend

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4786]
This is quite a big issue, if you wish to work on it, lets split it into parts:

 - [ ] users
 - [x] configs
 - [x] results 
 - [x] psas
 - [x] quotes [zaitsev-oleksii](https://github.com/zaitsev-oleksii)
 - [x] leaderboards
 - [x] presets
 - [x] publicStats
 - [x] apeKeys
 - [x] configuration

**Comment by Amanshenoy008** [comment]
Hey, can I  work on results part

**Comment by akash942** [comment]
hey @monkeytypegeorge can you elaborate more about the issue what do you mean by API response types or maybe point me to the right resources I am new here and trying to make my first open source contribution quite familiar with node

**Comment by Miodec** [comment]
> hey @monkeytypegeorge can you elaborate more about the issue what do you mean by API response types or maybe point me to the right resources I am new here and trying to make my first open source contribution quite familiar with node

The frontend functions currently are not typed, meaning that there is no type safety when using these functions.

<img width="883" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/4d59bd18-c320-4eeb-8d79-41f0630dee46">


As you can see here, data is `any`.

<img width="422" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/8e0ec511-71b8-424b-ab91-47b3636faeb0">
<img width="337" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/c88747b2-c993-4c4b-afa1-f8487fea0f42">

**Comment by zaitsev-oleksii** [comment]
Hey, can I take `quotes` part?

**Comment by Miodec** [comment]
@Amanshenoy008 unassigning you from the results section due to inactivity
