### ISSUE TITLE
Ellipsis input detected as 3 dots in custom mode

### ISSUE THREAD

**Issue by Fred-Vatin** [monkeytypegame/monkeytype#4792]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

FredDF

### Steps To Reproduce

1. custom > change
2. use this sample
```
l’agriculture HVE… en cours d’élaboration par les ministères de l’Agriculture et de… l’Écologie, qui englobera les démarches officielles existantes (agriculture raisonnée et biologique) et les démarches p…
```
3. with these settings
![Monkeytype ¦ A minimalistic, customizable typing test](https://github.com/monkeytypegame/monkeytype/assets/22337329/c6d5554f-508f-4085-944b-f5bb94425329)
4. Type the ellipsis char `…` if your layout is able to
5. It is detected as `...` (3 dots) and doesn’t match the text, triggering a false error.

## result
![image](https://github.com/monkeytypegame/monkeytype/assets/22337329/ca5234ce-0644-48e6-ba04-22130dbf7cd2)

### Environment

- OS: Windows 10 22H2
- Browser: tested with all browsers (firefox, edge, chromimum like)
- Browser Version: last

### Anything else?

In https://monkeytype.com/settings > input, lazy mode is OFF.

Previous issue #2218 has been closed as completed.

I guess an option is required to disable this “feature”.

**Comment by Miodec** [comment]
99% of users wont be able to type the ellipsis, so it was replaced with three dots. Custom mode should automatically replace the ellipsis with 3 dots if you enable "remove fancy typgraphy".

**Comment by Fred-Vatin** [comment]
`remove fancy typography` only fix `…` but create more problems removing chars I need to be output and detected as is.
![image](https://github.com/monkeytypegame/monkeytype/assets/22337329/b8ca28b7-2f87-467d-a2c6-0b6934f7b343)

**Comment by Fred-Vatin** [comment]
Is this fix online ? I emptied the cache and reload the app and even tried in another browser and the issue is the same.
![image](https://github.com/monkeytypegame/monkeytype/assets/22337329/3c881d74-9825-442a-b83a-c7e4673ad259)

**Comment by Miodec** [comment]
Not yet sorry, will be later today.
