### ISSUE TITLE
Missing a space in the privacy policy page

### ISSUE THREAD

**Issue by DLSdufer** [monkeytypegame/monkeytype#4797]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

DLSdufer

### Current Behavior

![image](https://github.com/monkeytypegame/monkeytype/assets/106004072/c03f26ab-417f-498e-9d9c-92f902aac63a)
Really simple fix, idk how to just fix it directly in the code.

### Steps To Reproduce

1. Go to https://monkeytype.com/privacy-policy
2. scroll to "What are cookies"
3. Typo

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Leonabcd123** [comment]
Still happening, solution was reverted in f3fa9646d939d04ad13d53d2ab50ac7bfed61163.
