### ISSUE TITLE
Getting offline even though i have internet

### ISSUE THREAD

**Issue by bassem97** [monkeytypegame/monkeytype#4820]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

bassem97

### Current Behavior

I'm getting offline no offline always with the top gray div showing " No internet connection " i tried chrome incognito, clear browser data& cache, no luck.
However when i open it in edge everything works fine

![image](https://github.com/monkeytypegame/monkeytype/assets/36534106/c1cfc069-feb8-4d4c-b49e-e3302dc520b7)

### Environment

- OS: Windows
- Browser: Chrome
- Browser Version:

**Comment by Miodec** [comment]
The website is simply reading whatever state the browser has at that moment. As you have mentioned, other browsers work fine - it has to be an issue with your Chrome then.

**Comment by kissu** [comment]
Got it today too with Brave. Tried in a private window, all extensions disabled, all shields down, no cache, no SW but some endpoints were still down. I'll report here again if it happens.
Would be nice to have it fixed down the road rather than being stuck with another browser.

**Comment by pbansal-godaddy** [comment]
Facing the same issue with Vivaldi. Browser API to check internet might not so reliable.
I also tried with incognito. It works fine in my other computer with the same Vivaldi browser. Not sure how this is persisting even tho all of the application local storage was cleared.

**Comment by pbansal-godaddy** [comment]
I also, got this issue, restarting the browser fixed it for me.
