### ISSUE TITLE
Personal record category not different when numbers selected

### ISSUE THREAD

**Issue by predkambrij** [monkeytypegame/monkeytype#4823]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

predkambrij

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":true,"numbers":true,"words":25,"time":60,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When typing, at the end we see what's our personal record (PB). That PB is shared if words and numbers are selected - with tests, where words only are selected. When we do a test where also punctuations are enabled, then it is tracking PB separately. I think that for tests with numbers, it should also track PB separately - because it's a different test, than words only.

![Screenshot_2023-11-30_10-57-45](https://github.com/monkeytypegame/monkeytype/assets/1273258/9b2a602e-7635-4955-80fa-3091c556c3cf)
![Screenshot_2023-11-30_11-04-16](https://github.com/monkeytypegame/monkeytype/assets/1273258/d9adcfec-f84b-4d29-84df-dbb07888a491)

![Screenshot_2023-11-30_10-59-15](https://github.com/monkeytypegame/monkeytype/assets/1273258/2a692957-ce8d-4530-b6ff-00ea3ab264ed)
![Screenshot_2023-11-30_11-02-14](https://github.com/monkeytypegame/monkeytype/assets/1273258/b0b38766-1f62-4166-9f11-dec11118a4e4)

### Expected Behavior

wrote above

### Environment

- OS: Ubuntu
- Browser: Chromium
- Browser Version:Version 119.0.6045.159 (Official Build) snap (64-bit)

**Comment by ArielCorte** [comment]
I don't think it may be a bug, maybe it's a decision. But I think it should be as you say, different tests, different bests. Maybe add an option to show global and current config bests?

**Comment by notreallystatic** [comment]
Hey, can I pick this up?

**Comment by Miodec** [comment]
Yeah, we can split the pbs. 

Assigning @notreallystatic

**Comment by notreallystatic** [comment]
@Miodec I have raised a PR for this
https://github.com/monkeytypegame/monkeytype/pull/4946
