### ISSUE TITLE
Support ~ and ` in matrix layout

### ISSUE THREAD

**Issue by unional** [monkeytypegame/monkeytype#4833]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

unional

### Current Behavior

I use the colemak DH matrix layout and it does not support the "`" | "~" key.
Is there a way to fix that? Should it / can it be deprecated and keep only colemah DH instead?

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
Where is this key located on the original layout?

**Comment by Miodec** [comment]
Wait im not sure what you're saying, the key is there:

<img width="692" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/9ca4076c-dec3-4dbd-b47a-c80f6ffda5ba">

**Comment by unional** [comment]
That's weird. It doesn't work. Let me check again. It is working on MacOS.

**Comment by unional** [comment]
Seems like it is working now. I also noticed that the layout description is gone:
![image](https://github.com/monkeytypegame/monkeytype/assets/3254987/22e5d51c-05e7-46f4-b26b-dbcc1066776b)

(in the past it shows `colemak dh matrix` next to `english`).
May be the app is updated?

**Comment by Miodec** [comment]
That will only show if you set your layout emulator to anything other than default.

**Comment by unional** [comment]
I see. That's what I was using and that key is missing.
