### ISSUE TITLE
Can see the navbar when hovering on the notificatoin

### ISSUE THREAD

**Issue by bhanuprakashbahoju** [monkeytypegame/monkeytype#4839]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

when hovering on the recent notification, the change in opacity make navbar elements visible.

### Environment

- OS:
- Browser:
- Browser Version:

### Anything else?

![Screenshot 2023-12-05 143359](https://github.com/monkeytypegame/monkeytype/assets/119474223/793ab195-8448-492e-9658-9e6dcffbb5d5)

**Comment by Miodec** [comment]
This is fine. Just an indication that you can click to dismiss the message.

**Comment by bhanuprakashbahoju** [comment]
then it should display some kind of close button while hovering on the notification
