### ISSUE TITLE
Time is adding up while result saving is disabled 

### ISSUE THREAD

**Issue by OmkarS25** [monkeytypegame/monkeytype#4867]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Orange0

### Current Behavior

Whenever I finish a test the time is added on the test page and in account , but when I turn disable result saving then also time is added on test page and not in account time. If refreshed the test time count gets corrected. For eg- I have typed 5 mins so 5mins are added to account and test time count but when result saving is disabled then time is being added in on the test page time count. 
In real I have typed 5 mins and disabled result saving and i have added a photo for reference.
![image](https://github.com/monkeytypegame/monkeytype/assets/143240322/2c9d4891-bb3d-49c5-b2e4-a77a5c16cb60)
As you can see in this photo 15 seconds are added but result saving is disabled at the 5 min mark. 

### Expected Behavior

Whenever result saving is disabled the time count should not increase on the test page.

### Steps To Reproduce

1. Result saving - off.
2. Give a test of any time options. 
3. The time count will increase on the test page and not in account time count.

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
I think I'll leave it as is, in case people want to track how much they've been typing today regardless of if the results have been saving to their account or not.
