### ISSUE TITLE
The screen timeout time has become really irritating. Just a second or two of inactivity results in screen timeout.

### ISSUE THREAD

**Issue by KPkm25** [monkeytypegame/monkeytype#4876]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

kpm

### Account config

{"theme":"joker","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":100,"time":1,"mode":"time","quoteLength":[0],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"1","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When I open MonkeyType, the typing page times out in less than a second and becomes hidden and prompts me to click or start typing to focus. This is really disturbing as I'm not even able to see the text before it gets blurred. Similarly, if I submit a test and then reopen the typing page, the same thing happens, not even giving the user the time to read the text before timing out
![Screenshot (1)](https://github.com/monkeytypegame/monkeytype/assets/101052237/2283a1aa-4b39-44a6-9d8a-7da3e0edb235)

### Expected Behavior

I expected the system to wait a relevant amount of time before timing out and going blur and asking met to focus the screen. I believe the expected time for blurring should be at least 2-3 seconds rather than immediately timing out.

### Steps To Reproduce

->Go to https://monkeytype.com/
->Don't start typing immediately
-> Within a second the screen will timeout and prompt you to click or start typing to focus

### Environment

- OS: Windows 11
- Browser: Brave
- Browser Version:Version 1.61.104

**Comment by VaibhavK03** [comment]
My device is not experiencing any such timeouts. To see if this also happened to me, I tried waiting a minute, but it didn't. I believe the problem is with your own device.

**Comment by Miodec** [comment]
I am also not seeing such issue on my end, I also suspect is an issue with your setup. Try testing in incognito or other browsers to confirm that. You could also try disabling "out of focus warning" in monkeytype settings as a workaround.
