### ISSUE TITLE
Roboto Mono and Helvetica are the same font

### ISSUE THREAD

**Issue by noisyBrain** [monkeytypegame/monkeytype#4889]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

noisyBrain

### Current Behavior

`Roboto Mono` and `Helvetica` fonts look identical

### Expected Behavior

I'm pretty sure they are different under normal circumstances.

### Steps To Reproduce

1. Go to `config`
2. Click on `appearance`
3. Search for `fonts`
4. Change between `Roboto Mono` and `Helvetica`

### Environment

- OS: Arch Linux
- Browser: Brave, Firefox
- Browser Version: 
  - **Brave**: Versión 1.58.127 Chromium: 117.0.5938.88 (Build oficial) (64 bits)
  - **Firefox**: 121.0 (64-bit)

### Anything else?

![monkeytype_helvetica](https://github.com/monkeytypegame/monkeytype/assets/95882962/aaf5fa6e-9959-4378-946c-6e97fcec6da5)
![monkeytype_roboto-mono](https://github.com/monkeytypegame/monkeytype/assets/95882962/8d4001d4-e940-4ea8-8be2-33c528ca904d)

**Comment by fehmer** [comment]
"Roboto Mono" is the fallback font if the selected font is not available in your browser.

**Comment by noisyBrain** [comment]
Oh, okay, my bad. So, I close this issue

**Comment by noisyBrain** [comment]
Oh okay, my bad so. I close this issue
