### ISSUE TITLE
Caps lock detection is inconsistent 

### ISSUE THREAD

**Issue by SlavBoi420** [monkeytypegame/monkeytype#4897]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

Slav_Boii

### Account config

{"theme":"matrix","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#323437","#1da6af","#1da6af","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":true,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":30,"mode":"custom","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"qwerty","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":true,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"react","keymapStyle":"matrix","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"1.0","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":true,"showLiveBurst":true,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"https://www.wallpaperflare.com/static/908/683/702/abstract-dark-black-background-digital-art-wallpaper-preview.jpg","customBackgroundSize":"cover","customBackgroundFilter":[2.6,0.9,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":true,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

When capitalised words are typed, I see that the caps lock key is quite inconsistent to trigger, usually not triggering at all, or triggering for the second letter instead of the first. This has not happened with any other website or Monkeytype previously.

When I log out of my account in the main browser window, the problem still persists. When I open monkeytype.com in an incognito window (without logging in), this problem does not exist. But when I log in and then try typing capitals, the problem springs back. After logging in, the problem still persists when I log out (in the same incognito window). 

Browser used is Microsoft Edge. I have not tried doing this on other browsers as of now

### Expected Behavior

Capital letters are expected to be typed out properly

### Steps To Reproduce

The steps I used to reproduce this issue are: 
1. Go to the custom page and set the quote to any word with a capitalised letter.
2. Upon typing the word out (though I tried with other words too, the word "The" is used in this case), the result is incorrect, usually appearing as "tHe" instead of "The". There was a clear delay given between the pressing of the caps lock key and the "T" key

### Environment

- OS: Windows 11
- Browser: Microsoft Edge
- Browser Version: 120.0.2210.91

**Comment by Miodec** [comment]
I can't reproduce this issue on MacOS.

**Comment by SlavBoi420** [comment]
I tried it on a second PC that I had, running Windows 11, this time running on both Edge and Chrome to see if it was the browser. It seemed to work fine when I didn't login to my account. I thought maybe it was the custom theme I used, so I changed the default theme to a custom one using monkethemes.com (without logging in), and everything seemed to work fine. 

However, when I logged in to my account, things started acting weird again. The caps lock was inconsistent again. I tried changing through different custom themes again and it was present over all of them. What's weirder is that the issue persists when I log out too, on incognito window, and the caps lock key is inconsistent until I close all of them out and relaunch a new incognito window.

**Comment by farkon00** [comment]
Have you tried clearing the cache AFTER you log out?

**Comment by SlavBoi420** [comment]
Yep, I tried that just now, it still refuses to register properly.
It's weird, when I use the shift key to capitalise letters, it works, but it is the caps lock key that doesn't respond properly

**Comment by SlavBoi420** [comment]
Yeah that's how I usually type

**Comment by Miodec** [comment]
Looking back at this issue, because you're not experiencing this issue in incognito means its probably one of your extensions - please disable them one by one to find which one is causing this.
