### ISSUE TITLE
ligatures broken for arabic language on dark note theme

### ISSUE THREAD

**Issue by AhmadFudl** [monkeytypegame/monkeytype#4913]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Fudl

### Account config

{"theme":"dark_note","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["dark_note"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":25,"time":120,"mode":"time","quoteLength":[1],"language":"arabic","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"below","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"word","showAllLines":false,"keymapMode":"off","keymapStyle":"split_matrix","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"4","soundVolume":"0.1","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":90,"repeatedPace":true,"pageWidth":"100","accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":90,"burstHeatmap":true,"britishEnglish":true,"lazyMode":true,"showAverage":"off","tapeMode":"off"}

### Current Behavior

Ligatures support for Arabic breaks when dark note theme is in use and multiple other themes.
dark note theme highlighting the problem:
<img width="1335" alt="Screenshot 2024-01-11 at 1 02 48 AM" src="https://github.com/monkeytypegame/monkeytype/assets/57303112/7e5e472b-0f47-46e2-8ca8-3fe796206eb1">

### Expected Behavior

dark theme where the problem doesn't exist
<img width="1418" alt="Screenshot 2024-01-11 at 1 03 41 AM" src="https://github.com/monkeytypegame/monkeytype/assets/57303112/cb298be8-5969-4110-bbb6-b5f33cb0f1e1">

### Steps To Reproduce

1. set language to Arabic
2. change theme to dark note
3. words now are cut into letters
4. change the theme to dark
5. the letters now are connected as the language should be displayed

### Environment

- OS: Mac OS Sonoma
- Browser: Firefox
- Browser Version: 121.0

### Anything else?

thanks for your hard work

**Comment by fehmer** [comment]
Same issue for e.g.  hindi.

theme dark:
![image](https://github.com/monkeytypegame/monkeytype/assets/3728838/a4d9a4fc-6bb1-40ba-92ad-08fcfaab00b4)


theme dark_note:
![image](https://github.com/monkeytypegame/monkeytype/assets/3728838/a6d51bfb-df5b-4106-ba8a-ae5c009f0f61)
