### ISSUE TITLE
Arabic: when lazy mode is manually disabled, dont automatically reenable it in that session

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4948]

**Comment by NadAlaba** [comment]
Better yet, save users' preferences with their account settings (if a user changed a setting to a non-default option such as, disabling lazy mode in Arabic), so that whenever they log back in (even in other sessions), lazy mode will still be disabled.

**Comment by Miodec** [comment]
> Better yet, save users' preferences with their account settings (if a user changed a setting to a non-default option such as, disabling lazy mode in Arabic), so that whenever they log back in (even in other sessions), lazy mode will still be disabled.

Hmm, i could save it in local storage.
