### ISSUE TITLE
Cannot login: `Failed to get user data: Cannot read properties of null (reading 'config')`

### ISSUE THREAD

**Issue by Lenochxd** [monkeytypegame/monkeytype#5011]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Lenoch

### Account config

Default one

### Current Behavior

When logging into my account (created on February 4), I got the following error: `Failed to get user data: Cannot read properties of null (reading 'config')`

### Expected Behavior

a login to my account

### Steps To Reproduce

1. Go to https://monkeytype.com/login
2. login to my account

### Environment

- OS: Windows 11
- Browser: Chrome
- Browser Version: 121.0

### Anything else?

My account is brand new, no configurations saved on it or anything else.

**Comment by Miodec** [comment]
Fixed in 0309fc32681abf9f259cdbd9918508c748aea408
