### ISSUE TITLE
Can not verify email | Stuck at Email handler page

### ISSUE THREAD

**Issue by oksaksham** [monkeytypegame/monkeytype#5040]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

oksaksham

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":30,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

I've tried to verify on 4 different browsers with and without incognito and I'm still unable to verify my mail id, it is always stuck at the page- " Email Handler | Monkeytype " 
![Screenshot 2024-02-11 172222](https://github.com/monkeytypegame/monkeytype/assets/153251658/077845f8-3ae9-4ece-bfdb-071f57fe3877)

### Expected Behavior

I suppose it should've been verified??  

### Environment

- OS: Windows 11
- Browser: Brave, Chrome, Safari, Firefox
- Browser Version: All browsers up to date

**Comment by ummahusla** [comment]
Same here. 


![SCR-20240211-mkuo](https://github.com/monkeytypegame/monkeytype/assets/2536096/ca8f00ae-f3a0-4908-89ab-e8260dcf61d0)

**Comment by nsmaciej** [comment]
It seems the jQuery file the Email Handler was using no longer exists. I've tracked the problem down #4880 which switched from vendored jQuery files to Webpack.

**Comment by Miodec** [comment]
Should be all good now.

**Comment by ummahusla** [comment]
Can confirm, was able to verify my email. Thanks.
