### ISSUE TITLE
Font selection does not work

### ISSUE THREAD

**Issue by fehmer** [monkeytypegame/monkeytype#5061]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Steps To Reproduce

go to setting, change font

**Comment by nyutie** [comment]
specifically the font selector in the settings. Selector always shows the `Custom` option and clicking font buttons does not do anything
