### ISSUE TITLE
Replay doesn't correct letters when deleted with CTRL + Backspace

### ISSUE THREAD

**Issue by cethemaco** [monkeytypegame/monkeytype#5075]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

After doing a typing test and clicking the "Watch replay" button, it appears some misspelled letters are still marked as not corrected, even though they were deleted and corrected while typing. I deduced that this happens whenever multiple letters were deleted at once via CTRL + Backspace. Deleting single letters still worked.
![delete](https://github.com/monkeytypegame/monkeytype/assets/77849536/cda6f267-c066-43f7-b95d-e857cbd0f394)

### Expected Behavior

Letters should be marked correctly, regardless whether or not they were deleted via CTRL + Backspace or not.

### Steps To Reproduce

1. Start any typing test
2. Make mistakes and delete the mispelled letters via CTRL + Backspace
3. Type the correct letters
4. Complete the test
5. Watch the replay

### Environment

- OS: Windows 10
- Browser: Mozilla Firefox
- Browser Version: 122.0.1

**Comment by prince-patel23** [comment]
I got the same problem.

**Comment by prince-patel23** [comment]
Documenting efforts made to resolve the replay bug in the application.

Efforts:

-  Identified replay.js file as primary code handling replay feature.-
-  Analyzed code, focusing on timing calculations and event handling.
-  Debugged using console logs, pinpointing discrepancies in recording user actions.
-  Attempted corrective measures, refining logic and timing calculations.

### **need guidance**.
