### ISSUE TITLE
Infinite WPM with opposite shift and master difficulty

### ISSUE THREAD

**Issue by padril** [monkeytypegame/monkeytype#5081]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

kedi

### Account config

{"theme":"iceberg_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#151e1d","#a48aa5","#914058","#576057","#0e1413","#bdc7bd","#772424","#5c1b1b","#772424","#5c1b1b"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"fast","quickRestart":"tab","punctuation":true,"numbers":false,"words":25,"time":60,"mode":"time","quoteLength":[1],"language":"english_1k","fontSize":2,"freedomMode":false,"difficulty":"master","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"read_ahead_easy","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":true,"keymapMode":"static","keymapStyle":"staggered","keymapLegendStyle":"dynamic","keymapLayout":"prog_dvorak","keymapShowTopRow":"always","fontFamily":"APL386_Unicode","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.1","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"on","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":true,"lazyMode":false,"showAverage":"both","tapeMode":"off"}

### Current Behavior

WPM shows up as infinite

### Expected Behavior

WPM shows up as 0 wpm

### Steps To Reproduce

1. Enable master difficulty (fail on wrong keypress)
2. Enable opposite shifts (errors when a capital is typed with the shift on the same side)
3. Go into a mode with capitals
4. Intentionally fail on the first character, specifically by entering the capital with the wrong shift key

### Environment

- OS: Debian (latest stable, I think)
- Browser: Firefox
- Browser Version: Extended support release 115.7.0esr (64-bit)

### Anything else?

This is probably very low priority, and doesn't actually matter since the attempt is counted as failed anyways, but I think it's funny. I'm not familiar with the codebase but I assume opposite shifts produces a fail that's somehow different from just typing the wrong character.
![image](https://github.com/monkeytypegame/monkeytype/assets/120127198/c49d46e1-d87e-496e-b15f-d71670cd73ba)

**Comment by padril** [comment]
Oh, additionally, the raw WPM seems to show up as a different multiple of 1000 each time, which is sorta funny.

**Comment by Miodec** [comment]
Thats fine, thats just what happens when you fail on the first keypress.
