### ISSUE TITLE
Space bug when the theme is changed

### ISSUE THREAD

**Issue by Dvorak2op** [monkeytypegame/monkeytype#5087]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Dvorak2op

### Account config

{"theme":"rgb","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#1e1e1e","#fa923b","#fa923b","#d4d3d8","#222126","#ffffff","#f77172","#f77172","#f77172","#f77172"],"favThemes":["serika_dark","sweden","sewing_tin","rgb"],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":"medium","quickRestart":"tab","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"time","quoteLength":[0],"language":"english","fontSize":2.8,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"react","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,0.4,2,0.6],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"both","tapeMode":"off"}

### Current Behavior

There is a bug in the site when the theme is changed, the space key does not work until the page is refreshed. It does work after refreshing  the page.However, when. the theme is changed again the space continues to remain unresponsive.

### Expected Behavior

The space button should be responsive even the theme is changed

### Steps To Reproduce

1.Go to the settings
2.Change the theme(it should be different than the current one)
3.Start typing and the space bar won work

### Environment

- OS: MacOS
- Browser:Googe Chrome
- Browser Version:121.0.6167.184

**Comment by Miodec** [comment]
The original issue should be fixed.

@mokshsinghji as for your issue - you can't backspace to a previous word if its typed correctly. (you can change that by enabling freedom mode)

**Comment by mokshsinghji** [comment]
> The original issue should be fixed.
> 
> @mokshsinghji as for your issue - you can't backspace to a previous word if its typed correctly. (you can change that by enabling freedom mode)

oops 🙈
