### ISSUE TITLE
Clicking the theme name in the footer causes the 8008 theme to be previewed

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#5103]
This only happens with single list mode off. It should remain previewing the current theme.

**Comment by sanidhyas3s** [comment]
After a bit of digging found the code where the change to 8008 is triggered. (line 56 at `..commandline\lists\themes.ts`)

```ts
hover: (): void => {
  // previewTheme(theme.name);
  ThemeController.preview(theme.name);
},
```

Can't really figure out why because this should only be triggered on hover of an item of the list.

**Comment by penguin-teal** [comment]
Line 161 of `commandline/index.ts` is calling hover when the element is `found`:
```typescript
if (obj.hover) obj.hover();
```
which is causing the bug (I'm not sure why this line is needed but I assume it serves a purpose?)

**Comment by underscoore** [comment]
I figured it out, Will be working on it in weeks ends

**Comment by sanidhyas3s** [comment]
Sorry @underscoore, made the fix myself as it was only a single line, as mentioned by @penguin-teal.
