### ISSUE TITLE
Typing Bug on the main page !

### ISSUE THREAD

**Issue by ReallyAnkit** [monkeytypegame/monkeytype#5171]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

It happens on Brave Browser (didn't got any  issue on Firefox) , it wasn't registering the inputs when i start to type as soon as i am on the main page !
It happens becuase of the **banner** of **monkeytype store** on the page as I visit the page , which if we don't close it doesn't register the keyboard strokes .

### Expected Behavior

It should be able to register the key strokes without closing the **banner**.

### Steps To Reproduce

Go to the main page using Brave and don't close the banner and start typing the paragraph , it won't register it .

### Environment

- OS: Ubuntu 22.04
- Browser: Brave
- Browser Version: 122.1.63.165

**Comment by KathanShah6503** [comment]
I faced the same issue but on Windows 11, Brave Browser. But for me, it is not showing any banner or pop-up to close on the landing page. It responds to the mouse clicks but not the keystrokes.

**Comment by Miodec** [comment]
Fixed in latest release.
