### ISSUE TITLE
Caps lock pop-up appears incorrectly

### ISSUE THREAD

**Issue by jxdv** [monkeytypegame/monkeytype#5181]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Not using an account.

### Account config

Not using an account.

### Current Behavior

When you start writing and turn on caps-lock and refresh afterwards, there's no caps-lock pop-up, but when you turn off the caps-lock then the pop-up appears, so basically the exact opposite happens.

### Expected Behavior

The pop-up appears correctly.

### Steps To Reproduce

1. Open monkeytype
2. Start typing out words
3. Enable Caps-lock
4. Hit F5
5. Turn off Caps-lock

### Environment

- OS: Ubuntu 22.04.3 LTS
- Browser: Firefox (snap)
- Browser Version: Firefox version 123.0 (64-bit)

**Comment by fehmer** [comment]
Hi, it should fix itself when you start typing.

**Comment by Miodec** [comment]
Browsers have no ability to detect the current state of caps lock - they only get this information when a key is pressed.
