### ISSUE TITLE
Session time isn't updated after failed tests

### ISSUE THREAD

**Issue by gretaSamsa** [monkeytypegame/monkeytype#5183]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

greta_samsa

### Current Behavior

The session time does not increase after a failed test. The time spent during failed tests is tracked, but is only updated after a successful test.

### Expected Behavior

Session time should accurately reflect the amount of time spent at the end of each test, even if you failed the test.

### Steps To Reproduce

1. Change settings to allow test failure (for example, set difficulty to master).
2. Fail several tests. Note that the session time field never appears.
3. Complete a test successfully. Note that the session time field now shows the total time spent, including during the failed tests.

### Environment

- OS: Windows 11
- Browser: Firefox
- Browser Version: 123.0

**Comment by gretaSamsa** [comment]
This also causes the "time spent typing" tracker to be inaccurate, for example if you spend several hours attempting long tests on master only the time spent up to your last completed test will be tracked.

**Comment by sanidhyas3s** [comment]
I think this is more of a decision than a bug. @Miodec What's your opinion on this?

**Comment by Miodec** [comment]
This is by design. The time spent typing on failed tests is attached to the next successful test submission - this is done to avoid sending a request to the server everytime a test is failed, and provide some data validation.
