### ISSUE TITLE
Split misc.ts into smaller util files

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#5187]

**Comment by sanidhyas3s** [comment]
On it!
(assuming the `misc.ts` in `frontend`)

**Comment by sanidhyas3s** [comment]
Oh, this is gonna take some time.

I have mostly separated the functions out into different categories (strings, date and time, numbers etc.), but refactoring where they are used and the corresponding imports would take a good amount of labor. Will try to get it done in the next few days anyways!

**Comment by sanidhyas3s** [comment]
Update: still working on this, wasn't able to find much time this weekend, hence no updates, will get back and add more commits asap.
