### ISSUE TITLE
`Toggle Monkey` setting causes the monkey to cover the live speed when `Live progress style` is set to `bar` and `Live speed` is `on`.

### ISSUE THREAD

**Issue by tthn0** [monkeytypegame/monkeytype#5192]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

tthn0

### Current Behavior

`Toggle Monkey` setting causes the monkey to cover the live speed when `Live progress style` is set to `bar` and `Live speed` is `on`.

### Expected Behavior

The monkey shouldn't be covering my speed. Screenshots are provided below:

![Screenshot 2024-03-07 at 03 08 06](https://github.com/monkeytypegame/monkeytype/assets/53582981/9e56ee95-1f11-422f-80f0-b043b573074e)
![Screenshot 2024-03-07 at 03 09 46](https://github.com/monkeytypegame/monkeytype/assets/53582981/6d89b0d2-73db-4c14-9ad0-22f15e8252ff)

### Steps To Reproduce

1. Make sure `Toggle Monkey` on.
2. Set `Live progress style` to `bar`.
3. Set `Live speed` to `on`.
4. Start a typing test.

### Environment

- OS: `macOS 14.3.1`
- Browser: `Safari`
- Browser Version: `17.3.1`

**Comment by tthn0** [comment]
Can I try contributing? I think I may be able to fix this

**Comment by Miodec** [comment]
This is intended. Having them go underneath eachother would push the content apart too much causing scrolling / text going way to the top of the screen. I recommend changing live wpm style to mini to move it above the text.

**Comment by tthn0** [comment]
@Miodec I'm aware that you already closed the issue but wouldn't it be a lot better if the WPM/accuracy can be moved up when `Live progress style` is in`bar` mode since there's nothing up there?

![Screenshot 2024-03-09 at 20 08 42 2](https://github.com/monkeytypegame/monkeytype/assets/53582981/377dc96e-28f9-4c08-a31c-d3f8c8966bca)

**Comment by Miodec** [comment]
The large text tyle timer already occupies that space.
