### ISSUE TITLE
Not responding Not able to click or start anything in Brave Browser

### ISSUE THREAD

**Issue by pantharshit007** [monkeytypegame/monkeytype#5207]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

OP_Harshit

### Current Behavior

So, It happened last night but after some time the site started working normally since the afternoon I am not able to start any tests.

I only experienced this in Brave Browser its working fine in Chrome and Edge
**What's Happening:**

-  I am not able to type
- I am not able to click any clickable elements
- Not able to start the typing test
- the screen is practically frozen but you can go to the inspect menu and other stuff.

The same problem occurs in Incognito Mode also.

I am attaching a video:

### Expected Behavior

To be able to start and interact with website's UI.the 

### Steps To Reproduce

Don't if this is a system specific problem or something else.system-specific

### Environment

- OS: Windows 11
- Browser: Brave
- Browser Version: 64 Bit version

### Anything else?

https://github.com/monkeytypegame/monkeytype/assets/97608579/a052d419-d1d7-463b-a463-889150fc65e5

**Comment by pantharshit007** [comment]
**Steps To Reproduce**
Don't know if this is a system specific problem or something else. 

so no idea how to reproduce it.

**Comment by fehmer** [comment]
as a workaround please deactivate "shields" for monkeytype.com
![image](https://github.com/monkeytypegame/monkeytype/assets/3728838/968d9d26-1d43-44e9-b3bb-3a02bc167fb4)

**Comment by pantharshit007** [comment]
thanks, it did work but then why it start to work in Incognito mode now any idea?

**Comment by FFUV** [comment]
idk but maybe **CLOSE THIS ISSUE** , if you encounter any other problems simply make another issue.

**Comment by pantharshit007** [comment]
Sure.
