### ISSUE TITLE
Linux key modifier not recognized on tip text

### ISSUE THREAD

**Issue by pasanflo** [monkeytypegame/monkeytype#5233]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

pasanflo

### Account config

`
{
  "theme": "sonokai",
  "themeLight": "serika",
  "themeDark": "serika_dark",
  "autoSwitchTheme": false,
  "customTheme": false,
  "customThemeColors": [
    "#323437",
    "#e2b714",
    "#e2b714",
    "#646669",
    "#2c2e31",
    "#d1d0c5",
    "#ca4754",
    "#7e2a33",
    "#ca4754",
    "#7e2a33"
  ],
  "favThemes": ["sonokai", "cheesecake", "moonlight", "vscode"],
  "showKeyTips": true,
  "showLiveWpm": false,
  "showTimerProgress": true,
  "smoothCaret": "fast",
  "quickRestart": "esc",
  "punctuation": false,
  "numbers": false,
  "words": 1,
  "time": 30,
  "mode": "custom",
  "quoteLength": [1],
  "language": "spanish",
  "fontSize": 2,
  "freedomMode": false,
  "difficulty": "normal",
  "blindMode": false,
  "quickEnd": false,
  "caretStyle": "default",
  "paceCaretStyle": "default",
  "flipTestColors": false,
  "layout": "default",
  "funbox": "none",
  "confidenceMode": "off",
  "indicateTypos": "off",
  "timerStyle": "bar",
  "colorfulMode": true,
  "randomTheme": "off",
  "timerColor": "main",
  "timerOpacity": "1",
  "stopOnError": "off",
  "showAllLines": false,
  "keymapMode": "off",
  "keymapStyle": "staggered",
  "keymapLegendStyle": "lowercase",
  "keymapLayout": "qwerty",
  "keymapShowTopRow": "layout",
  "fontFamily": "JetBrains_Mono",
  "smoothLineScroll": true,
  "alwaysShowDecimalPlaces": true,
  "alwaysShowWordsHistory": false,
  "singleListCommandLine": "manual",
  "capsLockWarning": true,
  "playSoundOnError": "2",
  "playSoundOnClick": "off",
  "soundVolume": "0.5",
  "startGraphsAtZero": true,
  "showOutOfFocusWarning": true,
  "paceCaret": "off",
  "paceCaretCustomSpeed": 100,
  "repeatedPace": true,
  "pageWidth": "100",
  "accountChart": ["on", "on", "on", "on"],
  "minWpm": "off",
  "minWpmCustomSpeed": 100,
  "highlightMode": "letter",
  "typingSpeedUnit": "wpm",
  "ads": "result",
  "hideExtraLetters": false,
  "strictSpace": false,
  "minAcc": "off",
  "minAccCustom": 90,
  "showLiveAcc": false,
  "showLiveBurst": false,
  "monkey": false,
  "repeatQuotes": "off",
  "oppositeShiftMode": "off",
  "customBackground": "",
  "customBackgroundSize": "cover",
  "customBackgroundFilter": [0, 1, 1, 1, 1],
  "customLayoutfluid": "qwerty#dvorak#colemak",
  "monkeyPowerLevel": "off",
  "minBurst": "off",
  "minBurstCustomSpeed": 100,
  "burstHeatmap": false,
  "britishEnglish": true,
  "lazyMode": false,
  "showAverage": "off",
  "tapeMode": "off"
}
`

### Current Behavior

The hint text on the settings page doesn't recognize I'm a Linux user and shows me a shortcut that is not working. It is showing me the Windows shortcut (With Ctrl) and it doesn't work on Firefox Linux.

This is because of how the modifier key is being checked ([Link to the checker](https://github.com/monkeytypegame/monkeytype/blob/b4259b7b4db0316c07ca3c16f36b1a4b8797a132/frontend/src/ts/ui.ts#L27))

### Expected Behavior

For Linux users on Gecko-based browsers, the correct tipped shortcut should be <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>

For Linux users on Chromium-based browsers, the tipped shortcut should be typed <kbd>Ctrl</kbd>/<kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>, since it works both ways.

### Steps To Reproduce

1. On a Gecko-based web browser (Firefox, e.g.) go to https://monkeytype.com/settings
2. It is shown that you can access to the settings by typing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> 
![image](https://github.com/monkeytypegame/monkeytype/assets/3006784/1d5011a6-e1cc-4dbb-890d-1c9f06440e8d)

3. Type <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>
4. Nothing happens. (It happens when you do <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

### Environment

- OS: Manjaro Linux 23.1.3
- Browser: Mozilla Firefox
- Browser Version: 123.0.1 (64-bit)

### Anything else?

I was checking on how they do it on different typescript-based projects so I can fix it myself, this is how Visual Studio Code does it just in case someone finds it useful:

https://github.com/microsoft/vscode/blob/7674d5634504300a295f0b177c3dd54053680181/src/vs/base/common/platform.ts

**Comment by fehmer** [comment]
`ctrl+shift+p`  opens private window in firefox on linux and windows. `super-shift-p` is already assigned to another action on windows. 

Maybe we can use a unused shortcut in firefox like
`ctrl+shift+n` or `ctrl+shift+space`

**Comment by pasanflo** [comment]
I think adding different shortcuts depending on browser could be misleading to some users that use different browsers. May I suggest overriding the native <kbd>Ctrl</kbd>+<kbd>K</kbd> as is widely used over the internet to show this kind of command line tool on the web?
(It overrides the native web search)

Examples on websites using this shortcut in similar command lines:

[Vue docs](https://vuejs.org/) - [React docs](https://react.dev/) - [MDN web docs](https://developer.mozilla.org/en-US/)

**Comment by unrealapex** [comment]
I implemented this shortcut. In hindsight, I should have tested this on Firefox before making the the change. I think using <kbd>Ctrl</kbd>/<kbd>Cmd</kbd>+<kbd>k</kbd> instead would be a good idea.

**Comment by pasanflo** [comment]
The main developer has rejected the <kbd>Ctrl</kbd>/<kbd>Cmd</kbd>+<kbd>K</kbd> in the pull request.
