### ISSUE TITLE
A lot of keyboard layouts are missing `-` required for words like 

### ISSUE THREAD

**Issue by kbilsted** [monkeytypegame/monkeytype#5264]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

looking in `tree/frontend/static/layouts)/_list.json` a lot of keyboard layouts are missing `-` which means there are words in the dictionary that cannot be completed without error. 

E.g. this quotes test i took  ![image](https://github.com/monkeytypegame/monkeytype/assets/1616338/42d7c6dd-d187-4cca-b217-6fcae5913795)  with a non-qwerty keyboard (using website emulation)
 
perhaps in those cases the `-` could be removed from the worlds that needs be typed? 

### Expected Behavior

I want to be able to complete without errors

### Steps To Reproduce

Take a test where a word contains a `-`

### Environment

- OS: All
- Browser: Chrome
- Browser Version: 17

**Comment by sanidhyas3s** [comment]
@Miodec Plans for this?

**Comment by Miodec** [comment]
What do you mean by "a-lot"? I checked and so far they all seem to have one.

**Comment by kbilsted** [comment]
Here is an example of the missing `-` 

![image](https://github.com/monkeytypegame/monkeytype/assets/1616338/4773ebf7-449f-457c-8df4-1d32cc875c3d)

**Comment by Miodec** [comment]
Thats because (as on most layouts) the `-` is on the number row, which is hidden by default. You can force it visible in the settings.
