### ISSUE TITLE
"Yeserday" leaderboard not loading on Docker deployment

### ISSUE THREAD

**Issue by mikesellt** [monkeytypegame/monkeytype#5275]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

I don't have an official account name as this environment is self-hosted. 

### Current Behavior

When on the daily leaderboard screen, if I click "show yesterday" in the top middle, it doesn't show any scores.  If I click "show today" it goes back to the daily board and shows properly.

### Expected Behavior

I should see yesterday's scores. 

### Steps To Reproduce

1. View daily leaderboard
2. click "show yesterday"
3. should see yesterday's scores, but it shows nothing in the tables

### Environment

- OS: Windows
- Browser: Google Chrome
- Browser Version:

### Anything else?

Environment is running in Docker.  I'm not sure if the problem occurs in non-docker deployments.

**Comment by mikesellt** [comment]
I just checked the main monkeytype.com site, and "show yesterday" works properly there.

**Comment by Miodec** [comment]
Can you check your daily lb expiration time in days in the configuration? 
![image](https://github.com/monkeytypegame/monkeytype/assets/13181393/e4eeb3c7-ccdb-4917-bc4a-a4f103375d27)

**Comment by mikesellt** [comment]
Okay, thanks.  I had mine set to 1.  I changed it to 14 and we'll see what happens.  Closing issue.
