### ISSUE TITLE
Add option to practice missed biwords

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#5316]
meaning pairs of words, the word before the failed one and the failed one

**Comment by bit8mayank** [comment]
hey can I work on this issue?
Could you also let me know the ui changes you have in mind ?

**Comment by Miodec** [comment]
> hey can I work on this issue? Could you also let me know the ui changes you have in mind ?
> 
> should it be something like it is below ? ![Screenshot 2024-06-13 190940](https://private-user-images.githubusercontent.com/92306676/339384475-2da66eb6-0bc5-451a-907a-d6531c0df82f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NDU2MTEsIm5iZiI6MTcxODU0NTMxMSwicGF0aCI6Ii85MjMwNjY3Ni8zMzkzODQ0NzUtMmRhNjZlYjYtMGJjNS00NTFhLTkwN2EtZDY1MzFjMGRmODJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDEzNDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMGY4NjhmNjViZWM4OGY5ZGZmMjNlYmY1MzY2YTI4ZjI4MGYwNjNiMjg0ZmM3NjVmZTc5NmU0YzgyODZkYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GD_MVrbHogw-TZntznM4JzsrZDUNBoUknLD1edLejdM)

Yeah this is good.

**Comment by bit8mayank** [comment]
what about the both button ?
it will not be clear to the user what it is referring to as there are 3 options now instead of  2 .

**Comment by Miodec** [comment]
Change `both` to `slow and missed`. Move `missed biwords` to the end of the list.

**Comment by sanidhyas3s** [comment]
@Miodec Since Mayank hasn't responded with the change for a month, may I take this up? Think I would be able to get it done relatively quick.

**Comment by Miodec** [comment]
@bit8mayank Any update?

**Comment by sanidhyas3s** [comment]
@Miodec Since he hasn't replied, I am starting to work on it. 

Just to get the task clear, the practice mode would contain the missed words and the words before them(obviously if there is a word before it), right?

**Comment by Miodec** [comment]
> @Miodec Since he hasn't replied, I am starting to work on it.
> 
> Just to get the task clear, the practice mode would contain the missed words and the words before them(obviously only if there is a word before it), right?

Correct

**Comment by sanidhyas3s** [comment]
Done, only got time now since last week. @Miodec Let me know if it is implemented the way you wanted.
