### ISSUE TITLE
Quotes over 100 words getting cut off when using repeat quotes

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#5326]

**Comment by Ethanqg0** [comment]
It worked for a handful of quotes I tried. Perhaps the quotes stored in the json file have an incorrect value for the 'length' key?

**Comment by Miodec** [comment]
> It worked for a handful of quotes I tried. Perhaps the quotes stored in the json file have an incorrect value for the 'length' key?

Not possible. There is a script that verifies the lengths.
