### ISSUE TITLE
Tab does not focus on the reset button on Safari m3 Mac.

### ISSUE THREAD

**Issue by davidroot8** [monkeytypegame/monkeytype#5328]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

iceflower700

### Current Behavior

At any point of any test, pressing tab has no effect, and does not focus on the restart button, resulting in not being able to reset the test using tab+enter. 

### Expected Behavior

Pressing Tab should focus on the reset button below the test, such that pressing enter would reset the test.

### Steps To Reproduce

1. Load up Monkeytype on an Arm based Mac on the safari browser
2. Start any test where the expected behavior of pressing tab + enter should restart the test
3. Press tab

### Environment

- OS: Mac OS Sonoma 14.3
- Browser: Safari 
- Browser Version: version 17.3 (19617.2.4.11.8) 
- Device: Mac M3 Max

**Comment by Miodec** [comment]
Make sure to enable tab navigation in your safari advanced settings.

**Comment by taesungh** [comment]
Want to point out for any future readers that there's also a separate system-wide setting in System Preferences > Keyboard > Shortcuts for **Use keyboard navigation to move focus between controls** which provides a less extreme level that focuses on buttons but not every link compared to the Safari setting (and also in case you were confused while comparing Safari settings across machines as I was.)
