### ISSUE TITLE
Pressing escape no longer auto populates command line

### ISSUE THREAD

**Issue by devmeat** [monkeytypegame/monkeytype#5339]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Pressing escape no longer auto populates command line view. It Just shows a search field.

### Expected Behavior

Command line should show frequently used/default functions. I used to quickly press Esc + Enter to start a new test since 'new test' is the first entry. Sad panda, because it's muscle memory.

### Environment

- OS: WIn11
- Browser: Firefox Dev Ed
- Browser Version: 126.0b5 (64-bit)

**Comment by devmeat** [comment]
Theme selection is also broken. Looks like the issue is related to the cmdline control itself. It populates when I start typing, so could just be the initial values it is not populating.

**Comment by devmeat** [comment]
Issue is back

**Comment by Miodec** [comment]
> Issue is back

Set your single list commandline mode to manual in the settings

**Comment by devmeat** [comment]
Thank you :)
