### ISSUE TITLE
Live progress bar doesn't work properly

### ISSUE THREAD

**Issue by Dvorak2op** [monkeytypegame/monkeytype#5354]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Dvorak2op

### Account config

{"theme":"sewing_tin","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#1e1e1e","#fa923b","#fa923b","#d4d3d8","#222126","#ffffff","#f77172","#f77172","#f77172","#f77172"],"favThemes":["serika_dark","sweden","sewing_tin","rgb","aurora","pulse","sewing_tin_light"],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"tab","punctuation":false,"numbers":false,"words":25,"time":15,"mode":"time","quoteLength":[-2],"language":"english","fontSize":2.8,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"off","flipTestColors":false,"layout":"dvorak","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"bar","liveSpeedStyle":"text","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"react","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"pb","paceCaretCustomSpeed":120,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,0.4,2,0.6],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"both","tapeMode":"off","maxLineWidth":0}

### Current Behavior

The live bar progress does not start from the start it stays at the same place for 1 second

### Expected Behavior

the live bar should be moving until the test is over

### Steps To Reproduce

1.Go the settings
2.change the live progress to bar
3.The bar should be doing the current behaviour

### Environment

- OS:MacOS
- Browser:Google Chrome
- Browser Version:124.0.6367.91

**Comment by sanidhyas3s** [comment]
The way it is stuck in the beginning is what you are referring to right?

https://github.com/monkeytypegame/monkeytype/assets/92792319/1d25586f-78fb-458a-b0f6-9094cdda9b6d

Will look into it asap!

**Comment by shahnewaz-labib** [comment]
The problem seems to be in the percentage calculation [here](https://github.com/monkeytypegame/monkeytype/blob/1a0e9ecfc6a235b6af217dd13dec4da98f60dce1/frontend/src/ts/test/timer-progress.ts#L108)

I don't think it is ever being set to 100%

**Comment by Dvorak2op** [comment]
> The way it is stuck in the beginning is what you are referring to, right?
> 
>  Video.mp4 
> Will look into it asap!

Yes thats what happens.

**Comment by Miodec** [comment]
Closed in 7fd31dcc7230eb6ab6bb6490c4a26f6ab8813745
