### ISSUE TITLE
Git option flag words do not appear unless punctuation is enabled

### ISSUE THREAD

**Issue by tjkuson** [monkeytypegame/monkeytype#5372]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

`-f`, `--force-if-includes`, and `--force-with-lease` do not appear whilst using git words unless punctuation is enabled. Those option flags were added in #5348.

### Expected Behavior

The option flags should appear without enabling punctuation.

### Steps To Reproduce

1. Go to [monkeytype.com](monkeytype.com)
2. Select git from the list of languages
3. Repeatedly restart the test and the option flag words do not appear
4. Enable punctuation and see that they do appear (with other punctuation, like capitalised words). 

### Environment

- OS: GNU/Linux
- Browser: Firefox
- Browser Version: 125.0.3

### Anything else?

Other code languages display words with leading punctuation without having punctuation enabled. For example, Elixir will show `%Version{}` and C will show `#pragma`.

**Comment by Miodec** [comment]
Some people might not want to type the special characters in their tests. I think requiring punctuation is a good middle ground.
