### ISSUE TITLE
Login & Password Reset Flow Broken For User

### ISSUE THREAD

**Issue by danhalliday** [monkeytypegame/monkeytype#5414]
### Did you clear cache before opening an issue?

- [x] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

ffgj585

### Current Behavior

- Can’t sign in to an account, see the following error:
- Password is provided by password manager and was previously used to sign in successfully.

```Email/password is incorrect or your account does not have password authentication enabled.```

- Following the password reset flow results in the following error:

```Failed to send password reset email: Server is down for maintenance```.

- The issue started a few days after signing up, when a sign out was forced after some `server is down for maintenance` errors while signed in and using the app normally.

### Expected Behavior

- Can log in to account using known-good password.
- Can reset password if desired.

### Steps To Reproduce

- I don’t have a good general reproduction except the above with my account `ffgj585`.

### Environment

- OS: `macOS`
- Browser: `Safari`
- Browser Version: `17.4 (18618.1.15.111.5, 18618)`

**Comment by fehmer** [comment]
please try again

**Comment by Miodec** [comment]
Quite possible you made a typo in your email when signing up. Email me at `support@monkeytype.com` with the details and we will sort this out.
