### ISSUE TITLE
Unable to type test when Logged in - Firefox

### ISSUE THREAD

**Issue by IkelAtomig** [monkeytypegame/monkeytype#5426]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account config

{
    "theme": "serika_dark",
    "themeLight": "serika",
    "themeDark": "serika_dark",
    "autoSwitchTheme": false,
    "customTheme": false,
    "customThemeColors": [
        "#6c7789",
        "#e2b714",
        "#e2b714",
        "#646669",
        "#b3a2a2",
        "#ffffff",
        "#ca4754",
        "#7e2a33",
        "#ca4754",
        "#7e2a33"
    ],
    "favThemes": [],
    "showKeyTips": true,
    "smoothCaret": "medium",
    "quickRestart": "tab",
    "punctuation": true,
    "numbers": true,
    "words": 350,
    "time": 900,
    "mode": "words",
    "quoteLength": [
        1
    ],
    "language": "english",
    "fontSize": 1.25,
    "freedomMode": false,
    "difficulty": "normal",
    "blindMode": false,
    "quickEnd": false,
    "caretStyle": "default",
    "paceCaretStyle": "default",
    "flipTestColors": false,
    "layout": "qwerty",
    "funbox": "weakspot",
    "confidenceMode": "off",
    "indicateTypos": "off",
    "timerStyle": "bar",
    "liveSpeedStyle": "off",
    "liveAccStyle": "off",
    "liveBurstStyle": "off",
    "colorfulMode": false,
    "randomTheme": "off",
    "timerColor": "main",
    "timerOpacity": "1",
    "stopOnError": "off",
    "showAllLines": true,
    "keymapMode": "off",
    "keymapStyle": "staggered",
    "keymapLegendStyle": "uppercase",
    "keymapLayout": "dvorak",
    "keymapShowTopRow": "layout",
    "fontFamily": "Roboto_Mono",
    "smoothLineScroll": true,
    "alwaysShowDecimalPlaces": true,
    "alwaysShowWordsHistory": true,
    "singleListCommandLine": "manual",
    "capsLockWarning": true,
    "playSoundOnError": "off",
    "playSoundOnClick": "off",
    "soundVolume": "0.1",
    "startGraphsAtZero": true,
    "showOutOfFocusWarning": true,
    "paceCaret": "off",
    "paceCaretCustomSpeed": 100,
    "repeatedPace": true,
    "accountChart": [
        "on",
        "on",
        "on",
        "on"
    ],
    "minWpm": "custom",
    "minWpmCustomSpeed": 35,
    "highlightMode": "letter",
    "typingSpeedUnit": "wpm",
    "ads": "off",
    "hideExtraLetters": false,
    "strictSpace": false,
    "minAcc": "custom",
    "minAccCustom": 90,
    "monkey": false,
    "repeatQuotes": "off",
    "oppositeShiftMode": "off",
    "customBackground": "",
    "customBackgroundSize": "cover",
    "customBackgroundFilter": [
        0,
        0.8,
        1,
        0.8
    ],
    "customLayoutfluid": "qwerty#dvorak#colemak",
    "monkeyPowerLevel": "off",
    "minBurst": "off",
    "minBurstCustomSpeed": 100,
    "burstHeatmap": false,
    "britishEnglish": true,
    "lazyMode": false,
    "showAverage": "off",
    "tapeMode": "off",
    "maxLineWidth": 0
}

### Current Behavior

I am unable to type test after logging into my account. I can do it when logged out.

### Expected Behavior

I should be able to type while logged in.

### Steps To Reproduce

Just Login and Type

### Environment

- OS: Fedora Linux 40
- Browser: Firefox
- Browser Version: 126.0

### Anything else?

I can type during Login in Brave Browser (based on chromium) though. I checked if Firefox tracking protection and uBlock Origin is blocking anything. But they aren't.

**Comment by IkelAtomig** [comment]
![image](https://github.com/monkeytypegame/monkeytype/assets/101938856/23a2d935-824d-4d75-9e5c-d82c5f81335e)

From the Console of the browser. I think it might be because of this. I am unable to type.

**Comment by Miodec** [comment]
What if you stay logged out, then import your settings JSON? Does it break then too?

**Comment by IkelAtomig** [comment]
@Miodec You are right, even after logout with the same settings, I cannot type. Possibly something with it.

**Comment by Miodec** [comment]
Works fine for me. Can you send a screen recording?

**Comment by IkelAtomig** [comment]
https://github.com/monkeytypegame/monkeytype/assets/101938856/265733b7-d261-4446-8023-3d912b941441

**Comment by Miodec** [comment]
Can you try disabling the qwerty emulation? Settings > layout emulator > off

**Comment by IkelAtomig** [comment]
What's the reason, Qwerty made problems. Just curious.
