### ISSUE TITLE
Loading freezes when we exit Google/Github login without finishing

### ISSUE THREAD

**Issue by sanidhyas3s** [monkeytypegame/monkeytype#5430]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

The loading animation and the options on the page freeze when we exit login without completion

### Account config

-

### Current Behavior

The loading animation stays and also the options on the page stay inaccessible.

### Expected Behavior

The page should realize the login failed and get back to normal.

### Steps To Reproduce

(logged out)
1. Open login page
2. Click on Google or Github login
3. Close the login pop-up window

### Environment

- OS: Windows (also tested on ChromeOS)
- Browser: Google Chrome
- Browser Version: 124.0.6367.208 (Official Build) (64-bit)

**Comment by Miodec** [comment]
The catch block is not called immediatelly after the popup is closed but I can't do much about that (since its a Firebase function). Either way, it will reset the inputs now.
