### ISSUE TITLE
Switch to Zod for schema validation, pass types to the endpoint handlers.

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#5440]
Currently, we use JOI for endpoint schema validation which does not support Typescript. Because of this, the controllers don't know whats inside query or body. We should switch to ZOD and then provide the types to the async handlers.

**Comment by fehmer** [comment]
Maybe checkout https://typia.io/docs/ ?

**Comment by Miodec** [comment]
Or https://valibot.dev/ 🙄

**Comment by fehmer** [comment]
or https://www.npmjs.com/package/ts-to-zod ?
