### ISSUE TITLE
Misaligned tooltip at the bottom of the privacy policy

### ISSUE THREAD

**Issue by unrealapex** [monkeytypegame/monkeytype#5443]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

unrealapex

### Current Behavior

When hovering over the tooltip, it is center aligned away from the the text being hovered over.

### Expected Behavior

The tooltip would appear right above Miodec's username.

### Steps To Reproduce

1. Go to the [contact info section of the privacy policy](https://monkeytype.com/privacy-policy#Contact_Info)
2. Hover over `@miodec`
3. See bug

### Environment

- OS:  `6.8.9-gentoo-dist`(Gentoo)
- Browser: Firefox
- Browser Version: Mozilla Firefox 125.0.3

### Anything else?

![misaligned tooltip](https://github.com/monkeytypegame/monkeytype/assets/79121360/6a1f748b-02b7-4141-b7b0-e64157f7473d)

**Comment by extoplasm** [comment]
yea, this is because the <span> element for the element _(document.querySelector("#app > main > span"))_  has the ruleset 
```
.content-grid {
    --content-max-width: 640px;
}
```
making this the width of the document

this is easily fixed, just make another ruleset to make this smaller

**Comment by extoplasm** [comment]
#5446 might fix this, but it looks a bit wonky aswell because the balloon is not in the centre of the text. 

pretty sure it might be better to make the element less wide

also, with this, you can add extra styling, as it looks like a normal text right now

**Comment by Miodec** [comment]
Thanks for the PR @extoplasm, however the fix here was to simply add a missing wrapping `p` tag.

**Comment by extoplasm** [comment]
this is also seen in the terms of service

i made a PR :)
