### ISSUE TITLE
Remove auto logout

### ISSUE THREAD

**Issue by Whydidthechickencrosstheroad** [monkeytypegame/monkeytype#5455]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

ScratchCat

### Current Behavior

So, when I log in. It did let me in. But I exited Monkeytype for a few minutes to like 2-3 hours, it logs me off. And this started a few days ago. I did press "Remember me" when I sign in

### Expected Behavior

It is supposed to stay to log me in until I press the sign out button. 

### Steps To Reproduce

This is when I log in (the issue):
1. Click on the person icon (top right corner).
2. Press the "remember me" button but sign in with GitHub or Google. Or sign up with your email and password
3. Wait a few minutes or a few hours
4. You get logged out

### Environment

- OS: ChromeOS
- Browser: Google Chrome
- Browser Version: 121.0.6167.212 (Official Build) (64-bit) 
- Note: Browser cannot be updated anymore on my ChromeOS device

**Comment by Miodec** [comment]
Are you using some sort of enchanced privacy thing that clears your local data?

**Comment by Whydidthechickencrosstheroad** [comment]
No

**Comment by Miodec** [comment]
Does it happen in incogntio with no extensions enabled?

**Comment by Whydidthechickencrosstheroad** [comment]
Yes. But I do not use Incognito mode

**Comment by Miodec** [comment]
Try a different browser

**Comment by Whydidthechickencrosstheroad** [comment]
I cannot install other browsers because I'm on a school Chromebook

**Comment by Miodec** [comment]
100% chance its some school policy that is clearing your data and logging you out then. Sorry but I can't do much in this case

**Comment by Whydidthechickencrosstheroad** [comment]
It is not clearing my data
