### ISSUE TITLE
Regarding cursor not goind backward if one correct word is found after an incorrect word

### ISSUE THREAD

**Issue by RuchitJagodara** [monkeytypegame/monkeytype#5469]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Doesn't matter

### Account config

NA

### Current Behavior

![Screenshot from 2024-06-02 23-05-57](https://github.com/monkeytypegame/monkeytype/assets/137716667/cdd197c5-fba9-4ce1-9618-eb2a653b24a9)
At this stage, I am not able to go back to the word where I just missed a character.

### Expected Behavior

If there is any wrong word or missing place, then we should be able to go back to that point.

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
This is not a bug. If you want to be able to go back to correct words, enable freedom mode.
