### ISSUE TITLE
Korean results failing to save

### ISSUE THREAD

**Issue by heuristics222** [monkeytypegame/monkeytype#5470]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

heuristics

### Account config

{"theme":"repose_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":15,"mode":"time","quoteLength":[1],"language":"korean","fontSize":1.75,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","liveSpeedStyle":"mini","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":75}

### Current Behavior

Results for any Korean test fail to save with the message `Failed to save result: Result data doesn't make sense`

I pulled one example payload from my network tab in case it helps (error 463)

```
{"result":{"wpm":62.4,"rawWpm":62.4,"charStats":[78,0,0,0],"charTotal":78,"acc":93.94,"mode":"time","mode2":"15","punctuation":false,"numbers":false,"lazyMode":false,"timestamp":1717386650847,"language":"korean","restartCount":4,"incompleteTests":[{"acc":80,"seconds":2.38},{"acc":90.91,"seconds":6.96},{"acc":83.33,"seconds":1.92},{"acc":83.33,"seconds":1.24}],"incompleteTestSeconds":12.5,"difficulty":"normal","blindMode":false,"tags":[],"keySpacing":[951.8,1919.9,1016.2,1095.8,704,712,576.1,871.8,1716.3,1838.6,1104.2],"keyDuration":[118.70000000018626,103,103.1000000005588,102.79999999981374,103.1000000005588,87.40000000037253,111,114.8999999994412,123.09999999962747,102.90000000037253,831.1000000005588,111],"keyOverlap":0,"lastKeyToEnd":1569.6,"startToFirstKey":924.3,"consistency":65.55,"wpmConsistency":86.97,"keyConsistency":58.48,"funbox":"none","bailedOut":false,"chartData":{"wpm":[96,84,64,63,62,66,70,75,73,66,68,63,66,66,62],"raw":[120,84,48,60,72,108,96,132,72,60,84,60,96,72,24],"err":[0,0,1,0,0,0,0,0,0,3,0,2,0,0,0]},"testDuration":15,"afkDuration":0,"stopOnLetter":false,"uid":"tcADooA9rNauRHzXupBHfjBvKSR2","hash":"de438907a0539e9d31c653811050a81dd3cb3091"}}
```

```
{
    "message": "Result data doesn't make sense",
    "data": {
        "uid": "tcADooA9rNauRHzXupBHfjBvKSR2"
    }
}
```

Tried a few different test types, Korean, Korean 1K, Korean 5K, different times, etc.

Also failed for brand new account in incognito window.

### Expected Behavior

Test results save successfully

### Steps To Reproduce

1. Log in
2. Switch to Korean
3. Run a test

### Environment

- OS: Windows 10
- Browser: Chrome
- Browser Version: 125.0.6422.141

**Comment by Miodec** [comment]
The results are failing to save because the number of reported keypresses is less than the characters typed. Your input method seems to be not sending all keypresses to the browser and they cant be verified.

**Comment by heuristics222** [comment]
Interesting, I did just run a Windows update so that must have changed something.  It looks like it's reporting the whole syllables rather than the individual characters.

**Comment by extoplasm** [comment]
> The results are failing to save because the number of reported keypresses is less than the characters typed. Your input method seems to be not sending all keypresses to the browser and they cant be verified.

btw this failed to save result happens in chinese as well, seems like the windows input method is eating up keypress events??

not sure how monkeytype detects events but if it uses [keydown](https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event) it does NOT detect keypresses when typing in chinese

basically its not sending any keypress events to the browser.....

**Comment by heuristics222** [comment]
I've been spending some time looking into this today and have been finding some really strange behavior.  This morning I was reproducing it regularly and debugging the code a bit to see what was happening and I saw that this [keydown event](https://github.com/monkeytypegame/monkeytype/blob/master/frontend/src/ts/controllers/input-controller.ts#L1165) would stop triggering after the typing the first space of the test.

Just now, I've been trying to narrow down whether the issue is with Chrome or Windows and I've found that I can't reproduce the issue in Firefox.  However, after running a test in Firefox, Chrome seems to work as well for a brief time.  I haven't been able to find exactly what is triggering the broken/fixed IME yet.

**Comment by extoplasm** [comment]
my hypothesis is it’s the windows IME, i’ll test it on my linux vm later today

**Comment by extoplasm** [comment]
ok so using ibus ime via ubuntu, this onkeypress event still doesnt fire as seen below

![image](https://github.com/monkeytypegame/monkeytype/assets/71046175/0c559c2d-0015-4880-ad43-249328d092e0)
its events get eaten up by the ime for some reason

**Comment by extoplasm** [comment]
doing some digging, this is what i've found

this is mentioned here [vscode-chatgpt/issues/191](https://github.com/gencay/vscode-chatgpt/issues/191) in which the author suggests a [iscomposing flag](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing) and links to an article [here](https://www.stum.de/2016/06/24/handling-ime-events-in-javascript/) which confirms that the ime eats up the keydown events.

pretty sure all we have to do is have
```
if (!event.isComposing) {
  // do something
```
as stated in the above issue

**Comment by heuristics222** [comment]
I still haven't been able to reproduce this in firefox, so suspect this is a chrome issue.  Found a similar [chromium bug report](https://issues.chromium.org/issues/341846848)

**Comment by extoplasm** [comment]
i don’t think it’s supposed to fire when using ime

keydown didn’t fire when i tested using ubuntu on firefox

**Comment by extoplasm** [comment]
ok i found the issue:
- when using keydown in chrome with an ime
  - expected output: nothing
  - actual output: keydown fired
- when using keydown in firefox with an ime
  - expected output: nothing
  - actual output: nothing

**therefore**: monkeytype's compositionend and compositionstart flags *work* but only in **firefox** as chrome sends keydown events for ime

**Comment by heuristics222** [comment]
I can't reproduce this issue anymore after updating to chrome 126.0.6478.57
