### ISSUE TITLE
Pressing space key opens up "saved personal info" suggestions !

### ISSUE THREAD

**Issue by Ahmed-Amamou** [monkeytypegame/monkeytype#5472]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Hamooood

### Account config

{"theme":"everblush","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":30,"mode":"time","quoteLength":[0],"language":"english","fontSize":2,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","off","off","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":0}

### Current Behavior

Essentially what happens is that, each time I press space between words when I'm typing any typing test (or moving to the next word), I get this suggestion pop-up of "saved personal info" between each word, which is very distracting.
This issue started today, I never had it before.
--

### Environment

- OS: Winodws 10
- Browser: Microsoft Edge
- Browser Version:  125.0.2535.67 (Official build) (64-bit)

### Anything else?

ps: this is my first ever issue, so I hope I'm not breaking any rules. Thank you.

![image](https://github.com/monkeytypegame/monkeytype/assets/115194376/cc00903b-dd74-4daf-8c94-b7e7d37f253a)
![image](https://github.com/monkeytypegame/monkeytype/assets/115194376/1f9ad86f-20eb-49f2-8090-a126757cd030)

**Comment by extoplasm** [comment]
monkeytype, for the input method, has a `<input>` tag, this probably affects bing's rendering because it thinks the input method is a input for lets say your credit card details.

try turning these off in microsoft edge settings? go to *manage personal info in wallet* and delete these? unless they are important

**Comment by Miodec** [comment]
Ive done all that is possible here - I used all the possible input properties that SHOULD disable autocompletion but the browser just ignores them. I even tried getting in touch with the Edge team, with no response. 

The only thing you can do here is disable this in Edge setings or switch browsers im afraid.

**Comment by Ahmed-Amamou** [comment]
Yea, Disabling Auto-completion works! But, I was hoping there's another way to fix this issue. Since I won't be able to have completions for other forms.
What's really bugging me is why did It only happen this last update?

Thanks anyway.

**Comment by extoplasm** [comment]
it seems like bing ignores the `autocomplete="off"` and proceeds with giving autocomplete suggestions anyways

switching browsers seems like the best option
