### ISSUE TITLE
The website is making me logout

### ISSUE THREAD

**Issue by Whydidthechickencrosstheroad** [monkeytypegame/monkeytype#5484]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

ScratchCat

### Current Behavior

Right now, it is randomly logging me out every few hours to a few days but I changed my password and didn't work and I was wondering that if there could be a feature that there is someone who was logged in from a device

### Expected Behavior

It shouldn't be logging me out

### Steps To Reproduce

1. I logged in with my email and password and sometimes I use Google account login
2. I was doing some typing but I mostly do not go on that website so I didn't go on a long time and it didn't log me out but when I checked back after a few hours, I was logged out
3. But I login but I changed the current password into something else but it did work for the first few days but doesn't work anymore. 
4. Same process I have done but I'm not sure what to do next

### Environment

- OS: ChromeOS
- Browser: Chrome
- Browser Version: Version 121.0.6167.212 (Official Build) (64-bit)
Note: It cannot be updated anymore because of the software itself or something

**Comment by Miodec** [comment]
Is this perhaps a school laptop?

**Comment by Whydidthechickencrosstheroad** [comment]
Yes

**Comment by Miodec** [comment]
Because your laptop is handled by your school, its very likely that its forcing the browser to clear local data which is making you logout. Other users also reported that they are being logged out on school devices - everyone else is not having this issue.

Sorry, but I can't to much in this case.

**Comment by Whydidthechickencrosstheroad** [comment]
I checked with the school and they said that is not true

**Comment by Miodec** [comment]
> I checked with the school and they said that is not true

Does it happen on non school machines?

**Comment by Whydidthechickencrosstheroad** [comment]
You mean non school devices?

**Comment by Miodec** [comment]
Yes

**Comment by Whydidthechickencrosstheroad** [comment]
Oh, that happens the same thing with non school devices

**Comment by Miodec** [comment]
Are you sure? Because if thousands of people would be logged out daily, people would complain fast - but so far its just you and another user, both on school laptops.

**Comment by Whydidthechickencrosstheroad** [comment]
Yes
