### ISSUE TITLE
Login Issues 

### ISSUE THREAD

**Issue by rajneesh-18** [monkeytypegame/monkeytype#5494]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

No

### Account name

cooldevdojo

### Current Behavior

Suddenly, automatically the account got logout.

### Expected Behavior

Nothing happen like this again with my account

### Steps To Reproduce

After doing multiple typing test. And If I'm not doing the test and anymore it will automatically logged out.

### Environment

- OS: Windows 11
- Browser: Chrome
- Browser Version: 124

### Anything else?

Actual problem is whenever the tab is open for a long time. The account will automatically logged out.

**Comment by Miodec** [comment]
> Actual problem is whenever the tab is open for a long time. The account will automatically logged out.

How long?

**Comment by rajneesh-18** [comment]
Around 1 month is happening.

**Comment by Miodec** [comment]
You keep the tab open for a month?

**Comment by rajneesh-18** [comment]
No whenever I open it and do some test and leave the pafe for 1 hour then I faced this issue.

**Comment by Miodec** [comment]
You open the site and an hour after opening it logs you out - this happens once a month?

**Comment by rajneesh-18** [comment]
no it happened everyday whenever i do some test

**Comment by Miodec** [comment]
Do you get logged out when refreshing or when closing the browser.

**Comment by Miodec** [comment]
Again: do you get logged out on refresh or on browser close?

**Comment by rajneesh-18** [comment]
When it refresh.

**Comment by Miodec** [comment]
Open an incognito mode window, make sure no extensions are enabled and test then.

**Comment by rajneesh-18** [comment]
Good idea! I'll test it in incognito mode without any extensions to see if that resolves the issue. Thanks for the tip!
