### ISSUE TITLE
Notification messages are hard to read on hover

### ISSUE THREAD

**Issue by navazjm** [monkeytypegame/monkeytype#5512]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

michaelnavs

### Current Behavior

Very niche, but when user receives a new notification message, once they hover the mouse over it, it becomes hard to read.

### Expected Behavior

Have a way to distinguish which notification is focused/hovered without impacting ability to read said message

### Steps To Reproduce

1. Start frontend only build.
2. Navigate between the settings and about component.
3. Repeat steps 2, about 3-4 times total. Should have a list of error notifications.
4. With about page rendered, scroll down until public stats are no longer visible.
5. Hover mouse over a notification message. Notifications should be difficult to read due to notification text blinding with background text

### Environment

- OS: macOS Sonoma 14.5
- Browser: Brave
- Browser Version: [Version 1.67.116 Chromium: 126.0.6478.71 (Official Build) (arm64)](https://brave.com/latest/)

### Anything else?

**Not hovering any notification:**

<img width="1512" alt="Screenshot 2024-06-19 at 9 53 08 PM" src="https://github.com/monkeytypegame/monkeytype/assets/44414214/8c65c3eb-2a45-4d31-8480-7479f0a1f146">

**Hovering topmost notification:**

<img width="1512" alt="Screenshot 2024-06-19 at 9 54 26 PM" src="https://github.com/monkeytypegame/monkeytype/assets/44414214/3a9e681c-4371-4f82-9cc4-a986b9f58da5">

**Potential Fix:**

Instead of decreasing the opacity when hovering, we can change the alpha value of the background color since the styles use rgba. For example: `.bad` background color is `--notif-background-color: rgba(138, 18, 12, 0.9);` but when hovering background color can be set to `--notif-background-color: rgba(138, 18, 12, 0.5);`. 

**Potential Fix: Not hovering any notifications**

<img width="1512" alt="Screenshot 2024-06-19 at 10 18 52 PM" src="https://github.com/monkeytypegame/monkeytype/assets/44414214/a4dfe9db-eafb-4f98-b73c-c824174d4fb3">

**Potential Fix: hovering topmost notification**

<img width="1512" alt="Screenshot 2024-06-19 at 10 21 25 PM" src="https://github.com/monkeytypegame/monkeytype/assets/44414214/c391ad73-1b25-4ffe-acd2-1a68c0ac8f5d">

**Comment by navazjm** [comment]
If happy with the potential fix, I do not mind contributing the fix to the project. I have been a long time user and would love to start helping out with the project!

**Comment by Miodec** [comment]
What the browser support looking like for the blur approach?

**Comment by navazjm** [comment]
According to [MDN Backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter), backdrop-filter has full support apart from Safari.
According to [MDN Blur](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur), blur has full support.

Which I see the .notif has `backdrop-filter: blur(15px)`, but does not seem to be getting applied like expected.

**Comment by Miodec** [comment]
Lets go with just a background color change then. Remove opacity change and lighten the background a bit on hover.
