### ISSUE TITLE
Can't jump to a test from the settings page with the command line

### ISSUE THREAD

**Issue by wokzhongson** [monkeytypegame/monkeytype#5514]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

`wokzhongson`

### Current Behavior

When selecting a test or mode from the command line while in settings (e.g. search 15, then select `time 15` from list then press enter or click), the command line disappears and nothing happens

### Expected Behavior

When a test or mode is selected from the list, it should jump or go to that test or mode

### Steps To Reproduce

1. go to monkeytype.com
2. navigate to settings (the cog button)
3. press `esc` to reveal the command line
4. search for a test or mode (e.g. time 15, words 25, mode time)
5. select it either by pressing enter or clicking on it

### Environment

- OS: Arch Linux
- Browser: Firefox & Firefox Nightly
- Browser Version: 126.0.1, 129.0a1 on nightly

**Comment by Miodec** [comment]
This is intended. You can use the `View Typing Page` command to navigate
