### ISSUE TITLE
Display on profile page stretches when adding repeated line breaks 

### ISSUE THREAD

**Issue by theiereman** [monkeytypegame/monkeytype#5526]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

reaperinoo

### Account config

{"theme":"mint","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["dark_note","dmg","sonokai"],"showKeyTips":true,"smoothCaret":"fast","quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":60,"mode":"time","quoteLength":[1],"language":"french_2k","fontSize":2.2,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"text","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"black","timerOpacity":"0.25","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"azerty","keymapShowTopRow":"layout","fontFamily":"Lexend_Deca","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":70,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"sellout","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":80,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":50}

### Current Behavior

There's no limitation on the number of `\n` you can put in the profile description / keyboard. 
When you put a lot of it (like 200 in bio for example) you get a layout looking like this : 
![image](https://github.com/monkeytypegame/monkeytype/assets/141121240/bfec0b56-a460-4eae-990f-400a91f62a84)

### Expected Behavior

There should be some kind of backend restriction to filter the number of successive `\n` you can input inside bio / keyboard fields.
Optionnaly, frontend restriction could be nice to reflect more accurately what you'll get once saved.

### Steps To Reproduce

1. Go to Profile edit page 
2. Put lots (200-ish) of backspace in bio or keyboard field

### Environment

- OS: Windows 10
- Browser: Firefox
- Browser Version: 127.0.1

**Comment by theiereman** [comment]
Hi @Miodec ! I can try to fix it if you're ok with it. 

What do you think we should do ? Limit to 1 line of blank space between paragraphs or something like that ? Should it throw an error or simply trim the unnecessary backspaces ?

For exemple, this would be ok : 

![image](https://github.com/monkeytypegame/monkeytype/assets/141121240/6a2c541a-3f7e-409d-9f30-818695557387)

And this would cause an error (or get trimmed) : 

![image](https://github.com/monkeytypegame/monkeytype/assets/141121240/625f4236-8510-4e9a-966a-ba458c9d63c4)

**Comment by Miodec** [comment]
> ![image](https://private-user-images.githubusercontent.com/141121240/342720520-6a2c541a-3f7e-409d-9f30-818695557387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzU2NzIsIm5iZiI6MTcxOTMzNTM3MiwicGF0aCI6Ii8xNDExMjEyNDAvMzQyNzIwNTIwLTZhMmM1NDFhLTNmN2UtNDA5ZC05ZjMwLTgxODY5NTU1NzM4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNzA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjQ2YTBhYzVjNWQwMjdjZDk2NDA5NzI0MzA5NTYyOTczZTU4YjBmMDJlNTFkMWZiODU0ZGVhOWVmZGJiYTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KFI39P3WRZnLv8EfutVFtrRiVTzKK7rilAKP2Cqm4CU)

Yeah, limit to this, so maximum of 2 consecutive newlines.
