### ISSUE TITLE
Caps lock notice reversed when page is loaded with caps lock

### ISSUE THREAD

**Issue by codingjlu** [monkeytypegame/monkeytype#5527]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

When you turn on caps lock, then open the monkeytype page in a browser, there is no caps lock notice. Then when caps lock is turned off, the notice pops up.

### Expected Behavior

When the page is loaded with caps lock, and initial check is made to see if caps lock is already on.

### Steps To Reproduce

1. Turn on caps lock
2. Navigate to monkeytype's website
3. No caps lock notice
4. Turn off caps lock
5. Caps lock notice on

### Environment

- **OS:** Windows 11
- **Browser:** Google Chrome
- **Browser Version:** 126.0.6478.114 (Official Build) (64-bit) (cohort: M126 Rollout)

**Comment by fehmer** [comment]
duplicate #5181
