### ISSUE TITLE
Update URLs and logos with X design (former Twitter)

### ISSUE THREAD

**Issue by unrealapex** [monkeytypegame/monkeytype#5540]
Update URLs and logos with X design (former Twitter). Now that we can use fontawesome-6, this change should be easy.
I can create a fork and work on this if you guys agree.

https://fontawesome.com/icons/x-twitter?f=brands&s=solid

_Originally posted by @aescanes in https://github.com/monkeytypegame/monkeytype/discussions/5478_

**Comment by fehmer** [comment]
Is the official account `twitter.com/monkeytype` or `twitter.com/monkeytypegame` ?

**Comment by unrealapex** [comment]
It's `@monkeytype`.
