### ISSUE TITLE
Disable the access of some key binding browser extensions.

### ISSUE THREAD

**Issue by LittleOddBoy** [monkeytypegame/monkeytype#5578]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Amirhossein-dev

### Current Behavior

As you may know, there are some browser extensions that their job is to bind some shortcuts for some special purposes. For example [Vimium C](https://chromewebstore.google.com/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg?hl=en) in Chrome and Chrome-based browser is an example of key binding extensions that offers some key binding referenced to Vim key binding. 

However, this will annoy the user if the extension is installed because you need to somehow focus on the text sample manually or in some rare and bad moments, when the text is started with a word like *on*, it will cause issue because `o` and `O` are some of the main key bindings of this extension.

### Expected Behavior

This one would be just not happening that. 
For this purpose, I recommend to disable the permission of all the extensions if they have/wanna access to the webpage.

### Steps To Reproduce

1. Go to [this](https://chromewebstore.google.com/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg?hl=en) and install this extension. Please note that if you're on Firefox, you've to go and download something like Vinium actual project.
2. Go to the extensions options (Chrome bro? open Extensions, right-click and then Options. Firefox guy? go through your browser settings, extension and themes, then the specific extension, and do its options.
3. Scroll until Miscellaneous options section, check the "Don't let pages steal the focus in loading" on.
4. Time to type!

### Environment

- OS: Windows 10 
- Browser: Any
- Browser Version: Latest

**Comment by fehmer** [comment]
> Scroll until Miscellaneous options section, check the "Don't let pages steal the focus in loading" on.

Disable this option or add `monkeytype.com` to the excluded URLs list.

**Comment by LittleOddBoy** [comment]
> > Scroll until Miscellaneous options section, check the "Don't let pages steal the focus in loading" on.
> 
> Disable this option or add `monkeytype.com` to the excluded URLs list.

Perfection!
I thought it could be better if the `monkeytype.com` prevent happening this, so I made this issue.
Thanks!
