### ISSUE TITLE
The read ahead, read ahead easy and read ahead hard all these are not working in the funbox 

### ISSUE THREAD

**Issue by roy-abhi-roy** [monkeytypegame/monkeytype#5598]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

![image](https://github.com/monkeytypegame/monkeytype/assets/95222112/467dbd80-878d-46e9-8c59-63ca0b812aa3)

The read-ahead is not working.

### Expected Behavior

The current word should be invisible in this mode, but it is not happening. 
![image](https://github.com/monkeytypegame/monkeytype/assets/95222112/11bc614f-5a2f-4d96-80b8-c1778b7abc9e)

### Environment

- OS: macOS 14.5
- Browser: ARC
- Browser Version: Version 1.49.1 (51495)

**Comment by Miodec** [comment]
Fixed in 215862e6e13c38508292572fbaa9098615e138c6
