### ISSUE TITLE
IPv6 shortens into invalid addresses

### ISSUE THREAD

**Issue by asasine** [monkeytypegame/monkeytype#5622]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The IPv6 shortening used when punctuation is turned on for IPv6 funbox mode produces invalid addresses.

https://github.com/monkeytypegame/monkeytype/blob/8f4d291fcfb47a187b696d1393853c14807050ee/frontend/src/ts/test/funbox/funbox.ts#L483-L490

Some real and pathalogical cases:
- `b70b:ad23:3d4b:23a9:8000:0000:0000:0000` -> `b70b:ad23:3d4b:23a9:8000:::`
- `0000:0000:0000:0000:0001:0000:0000:0000` -> `::1:::`
- `0000:0000:0000:0001:0002:0000:0000:0000` -> `::1:2:::`

### Expected Behavior

These cases should shorten as follows:
- `b70b:ad23:3d4b:23a9:8000:0000:0000:0000` -> `b70b:ad23:3d4b:23a9:8000::` (two `:`, not three)
- `0000:0000:0000:0001:0000:0000:0000:0000` -> `0:0:0:1::` (only longest series of zero groups gets shortened)
- `0000:0000:0000:0001:0002:0000:0000:0000` -> `::1:2:0:0:0` (if there's a tie, the leftmost is shortened)

### Steps To Reproduce

1. Turn on IPv6 funbox mode.
2. Enable punctuation.

### Anything else?

IETF has recommenations in [RFC5952](https://datatracker.ietf.org/doc/html/rfc5952) (also described on [Wikipedia](https://en.wikipedia.org/wiki/IPv6_address#Representation)).

I can work on a fix and test cases. The easiest solution might be to pull in an npm package for IP parsing but I'm not sure on what the feeling is around extra dependencies.

**Comment by rizwanmustafa** [comment]
I will look into it.
