### ISSUE TITLE
Viewing and Customizing Accounts 

### ISSUE THREAD

**Issue by TheeKevin** [monkeytypegame/monkeytype#563]
I would love a feature in which you can view other people's accounts and to make viewing accounts slightly more interesting have it so you can customize your account so maybe when you view someone's account you have to view their account with their theme preference on or you can add something in which people can type out a bio about themselves.

I think this feature would be very versatile if implemented because well it would boost someone's motivation to use the site with other people rather than typing by themselves plus on the leaderboards you can view the fastest typists on Monkeytype, for multiplayer maybe when you hover over someone's name you can see their average wpm and highest, and in general for the future (such as maybe a friending feature?).

An extra feature I think could go with account viewing is if you can view other peoples accounts then that would mean you can track some of their stats. This feature would only work for quote mode in which you can see the leaderboard for that quote or you could see the average wpm of everyone that ever typed on that quote.

**Comment by mrbrianevans** [comment]
Yeah I think this is a good idea. Something like 10fastfingers, which also shows you other people who have viewed your account. 

It also enables people to mention on reddit/youtube a score that they achieved, and other people can verify that score by viewing their profile.

**Comment by shiyanshirani** [comment]
Absolutely, I'm loving this idea.

**Comment by QuickDevV** [comment]
Wonder when this will happen 🤔

**Comment by mii9000** [comment]
+1 for this idea as well. currently having to screenshot, crop and share.

**Comment by Miodec** [comment]
Added profiles

**Comment by Saksham-13** [comment]
hey can i work on this issue
