### ISSUE TITLE
Wikipedia funbox issues for Serbian

### ISSUE THREAD

**Issue by Fooftilly** [monkeytypegame/monkeytype#5630]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

[Peroniko](https://monkeytype.com/profile/Peroniko)

### Current Behavior

When using the Wikipedia funbox, some characters from other languages cannot be typed without changing the keyboard layout (e.g., from Serbian Latin to Cyrillic) or using characters from a different writing system (e.g., Hanzi, Kanji). Additionally, the funbox does not work with Serbian Latin, as it only supports the Cyrillic text versions.

### Expected Behavior

When using the Wikipedia funbox, characters from other languages should be converted when possible (e.g., convert Serbian Latin to Cyrillic or vice versa). Characters that cannot be typed easily, such as Kanji, should be deleted.

### Steps To Reproduce

1. Enable wikipedia funbox
2. Go to main page

### Environment

- OS: Arch Linux
- Browser: Floorp (Firefox fork)
- Browser Version: 11.14.1 (64-bit)

### Anything else?

![image](https://github.com/user-attachments/assets/ae581233-77a2-4316-846a-32e2df67fdce)
![image](https://github.com/user-attachments/assets/83e7b008-92eb-4ef7-a1a7-79aa00c9b7ae)

**Comment by Fooftilly** [comment]
Also, if that is of any use, Wikipedia funbox can also use text from Serbo-Croatian Wikipedia (https://sh.wikipedia.org). Wikipedia also provides both Latin and Cyrillic text version on both Serbian and Serbo-Croatian Wikipedia.

**Comment by Whydidthechickencrosstheroad** [comment]
@Fooftilly, he means the other language (not Latin or Cyrillic) in Serbian glitch
