### ISSUE TITLE
Issue with the practice missed words function after 29 July update

### ISSUE THREAD

**Issue by deadpoet11** [monkeytypegame/monkeytype#5685]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

z1v4um

### Account config

{"theme":"terminal","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":60,"mode":"custom","quoteLength":[1],"language":"english_1k","fontSize":2,"freedomMode":true,"difficulty":"expert","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"off","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"word","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":true,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":0}

### Current Behavior

When repeating a test of the  words i missed or was slow in it shows a bunch of errors and doesn't load any words
![image](https://github.com/user-attachments/assets/ef694852-e6d9-4704-b8e6-d5422350f3ef)

also note that the issue persists even if the newly added biwords option is not selected in the menu.

### Steps To Reproduce

start a test 
practice missed ones
make a mistake
click restart icon

**Comment by vishal-y** [comment]
I can't reproduce the issue :)

![image](https://github.com/user-attachments/assets/ed45ac39-15d5-4573-b570-2d56a8d04fa2)

**Comment by deadpoet11** [comment]
I will add detailed steps:

start a timed test
practice missed or slow or whatever words
now click the repeat icon which restarts the test.

and here is a recording:

https://github.com/user-attachments/assets/7faefe86-7362-4719-a546-8f44d712f6c1

**Comment by Miodec** [comment]
Got it, thanks
