### ISSUE TITLE
Can highlight words

### ISSUE THREAD

**Issue by LilTimmyRules** [monkeytypegame/monkeytype#5709]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

Mr_Typer247

### Current Behavior

I can’t highlight

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by div02-afk** [comment]
Not sure what you want to do
highlight or no highlight?

**Comment by Miodec** [comment]
You didn't provide any details about the issue. Feel free to open another issue but this time provide as much details as possible.
