### ISSUE TITLE
Timezone problem in heatmap

### ISSUE THREAD

**Issue by mecskyverse** [monkeytypegame/monkeytype#5725]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

mecskyverse

### Account config

mecskyverse 
{"theme":"bento","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"tab","punctuation":false,"numbers":false,"words":50,"time":60,"mode":"time","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","keymapSize":1,"fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":0.5,"startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","off","off","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":0}

### Current Behavior

I am in Indian (Asia/Calcutta) TimeZone. Its around 2:40 AM and as per the schreenshots attached I have given two tests around this time.
![image](https://github.com/user-attachments/assets/eec54484-135a-43ee-8f7c-73dd0ce6fecf)

But when I refreshed heatmap is still empty. I don't know if it is expected or if this problem will resolve after some time but I was thinking like github heatmap it should update quickly. 

![image](https://github.com/user-attachments/assets/cce12e00-630a-452a-ae95-7c6f002cd8cb)

### Expected Behavior

The heatmap of current date should be updated after giving test.

### Steps To Reproduce

1. Try in Indian Timezone around 00:00 to 03:00 AM log in.
2.  Take some typing tests.
3. You can see the history in heatmap that it is not updated after even refreshing it. But in normal time (around afternoon or evening) it gets updated instantly. 

### Environment

- OS: Windows 10
- Browser: Brave
- Browser Version: [Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by fehmer** [comment]
Hi, the heatmap is always in UTC

**Comment by mecskyverse** [comment]
Hi, I thought it was a bug so I created an issue. If this is expected behaviour, should I close it?

**Comment by Miodec** [comment]
Yeah this is expected.
