### ISSUE TITLE
If the cursor moves, the timer stops displaying.

### ISSUE THREAD

**Issue by avick-saha** [monkeytypegame/monkeytype#5749]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

avicksaha

### Current Behavior

If I start the game and the cursor moves for any reason, the timer stops displaying, even though it continues running in the background.

### Expected Behavior

It should keep displaying the timer after starting the game, even if I move my cursor; it shouldn't stop displaying the timer.

### Steps To Reproduce

1. Go to monkeytype.com
2. Start the game 
3. Move the cursor 
4. Stops displaying the timer

### Environment

- OS: Windows 11
- Browser: Chrome (I've  tried for other browsers too)
- Browser Version: 127.0.6533.100 (Official Build) (64-bit)

**Comment by Miodec** [comment]
This is intended. Just start typing again it will come back.
