### ISSUE TITLE
Words and caret shift around on Wikipedia funbox

### ISSUE THREAD

**Issue by PVTejas** [monkeytypegame/monkeytype#5797]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

allsparkinfinite

### Account config

```json
{"theme":"dracula","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":50,"time":60,"mode":"time","quoteLength":[0,1,2,3],"language":"english","fontSize":1.5,"freedomMode":true,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"underline","flipTestColors":false,"layout":"default","funbox":"wikipedia","confidenceMode":"off","indicateTypos":"below","timerStyle":"mini","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","keymapSize":1,"fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":0.5,"startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":true,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"keymap","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":true,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":0}
```

### Current Behavior

With Wikipedia funbox active, a few moments into the typing test, the loading bar appears at the top of the screen, presumably to load more sentences. While the loading bar is present, some words vanish, some are duplicated, and the caret jumps around to the duplicated word. The behaviour around the caret returns to normal after the loading bar vanishes, but the "damage" remains. This possibly only happens on slow connections.

Typing as if nothing has occurred seems to be the correct thing to do in this scenario in order to have a good score and accuracy, implying this is only a visual bug and the actual comparison between actual/expected keystrokes is done correctly.

https://github.com/user-attachments/assets/3d33af6d-85ee-4c59-8a10-b081ad85a26b

### Expected Behavior

Words should remain static while I type and only move around when I reach a line break

### Steps To Reproduce

1. Activate wikipedia funbox, leave all other settings as it is
2. Start a typing test
3. Start typing
4. A few seconds in, the error should occur

### Environment

- OS: Ubuntu 22.04, KDE Plasma DE
- Browser: Firefox
- Browser Version: 129.0 (64-bit) Snap

**Comment by avick-saha** [comment]
You're right. When I'm connected to my Wi-Fi, nothing happens, but when connected to my mobile data, the issue occurs.

**Comment by sanidhyas3s** [comment]
I will look into this issue, though I am not particularly able to replicate this but there must some incorrect reloading logic within Wikipedia funbox. Meanwhile, any concrete way of replicating the issues are appreciated.

**Comment by PVTejas** [comment]
@sanidhyas3s it does also occur on poetry funbox.

**Comment by Miodec** [comment]
Should be fixed now.

**Comment by PVTejas** [comment]
Just encountered a situation where I would've expected this bug to occur and it did not, so thanks for the fix!
