### ISSUE TITLE
`max line width` autometic reset to 20

### ISSUE THREAD

**Issue by kaushiksahu18** [monkeytypegame/monkeytype#5818]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Account name

kaushikasahu18

### Account config

{"theme":"anti_hero","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#1e1e2e","#a6e3a1","#f5e0dc","#585b70","#181825","#cdd6f4","#f38ba8","#eba0ac","#f38ba8","#eba0ac"],"favThemes":["incognito","miami_nights","anti_hero","aether","ryujinscales","bushido","rgb","diner","joker","80s_after_dark","luna","purpleish"],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"esc","punctuation":false,"numbers":false,"words":25,"time":60,"mode":"words","quoteLength":[0,1,2,3],"language":"english","fontSize":4,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"outline","paceCaretStyle":"block","flipTestColors":false,"layout":"colemak","funbox":"weakspot","confidenceMode":"off","indicateTypos":"off","timerStyle":"bar","liveSpeedStyle":"text","liveAccStyle":"text","liveBurstStyle":"text","colorfulMode":true,"randomTheme":"dark","timerColor":"text","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"next","keymapStyle":"staggered","keymapLegendStyle":"dynamic","keymapLayout":"colemak","keymapShowTopRow":"layout","keymapSize":1,"fontFamily":"Cascadia_Mono","smoothLineScroll":true,"alwaysShowDecimalPlaces":true,"alwaysShowWordsHistory":false,"singleListCommandLine":"on","capsLockWarning":true,"playSoundOnError":"1","playSoundOnClick":"7","soundVolume":0.5,"startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"average","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"word",`"maxLineWidth":20`}

### Current Behavior

`max line width`
`Change the maximum width of the typing test, measured in characters. Setting this to 0 will align the words to the edges of the content area.`

### Environment

- OS: ArchLinux
- Browser: Brave
- Browser Version: 127.1.68.141

**Comment by Miodec** [comment]
20 is the minimum value. This is not a bug.

**Comment by kaushiksahu18** [comment]
> 20 is the minimum value. This is not a bug.

## so why its left side is hidden, i want it to be stay in center
![modified_image](https://github.com/user-attachments/assets/2a88a22d-9ef0-41cf-aa98-c5c242daf395)

**Comment by Miodec** [comment]
> > 20 is the minimum value. This is not a bug.
> 
> ## so why its left side is hidden, i want it to be stay in center or little right
> ![modified_image](https://private-user-images.githubusercontent.com/113049724/361165290-2a88a22d-9ef0-41cf-aa98-c5c242daf395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTgzNTEsIm5iZiI6MTcyNDc1ODA1MSwicGF0aCI6Ii8xMTMwNDk3MjQvMzYxMTY1MjkwLTJhODhhMjJkLTllZjAtNDFjZi1hYTk4LWM1YzI0MmRhZjM5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxMTI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmU0ZjI0YzU2N2I5MWJjYjFlMWQxNjBkMGRkNTk4MmMxNTY5YWQwNzViNTA1NDNhZDAwMjc3MTBmNGIzYWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gbCZSeosZTIbjF-HtTujWBIHqjEP3CEBe5qcTaybboQ)

Im not sure what you mean. By going below 20 you would see less words. If you want the left side to not be hidden just set it to a higher value.
