### ISSUE TITLE
"blind mode" setting toggle button is empty

### ISSUE THREAD

**Issue by sushant-sinha** [monkeytypegame/monkeytype#5821]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

sushant-sinha

### Current Behavior

I just came across the “blind mode” button in the settings. Below are the snapshots of the scenarios. As you can see that the text is missing for “on”.

<img width="1334" alt="Screenshot 2024-08-25 at 10 04 26" src="https://github.com/user-attachments/assets/52e2ac81-c94f-48ed-8ddd-89ad51d946e0">
<img width="1340" alt="Screenshot 2024-08-25 at 10 04 38" src="https://github.com/user-attachments/assets/52ee2a38-6132-4fa3-84c0-a60e1d3953d0">

### Expected Behavior

There should be a text "on" when the blind mode is enabled in the button.

### Steps To Reproduce

1) Go to settings
2) Scroll down to the "blind mode"
3) Try to toggle the button, it would have missing text

### Environment

- OS: MacOS Sonoma 14.6.1 (23G93)
- Browser: Safari
- Browser Version: Version 17.6 (19618.3.11.11.5)

### Anything else?

In settings.html, I couldn't find any text for the "true" config-value.

<img width="678" alt="image" src="https://github.com/user-attachments/assets/3f2c5d42-5d04-4cde-9991-156062339aee">

**Comment by fehmer** [comment]
![image](https://github.com/user-attachments/assets/5f628332-5f9e-44d8-819e-b316a7541363)

**Comment by sushant-sinha** [comment]
I see it. Is it because we want to emphasize that "blind mode" implies "blind"(cannot see it)?

I'll close the issue. Thanks!

**Comment by fehmer** [comment]
pretty sure this is the most reported easter egg on the site
