### ISSUE TITLE
Typing does not stop when a wrong word is typed at the end

### ISSUE THREAD

**Issue by rohith1222004** [monkeytypegame/monkeytype#5822]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

**The test continues, requiring manual intervention to stop.**

When I type the wrong word at the end of a typing test, the test doesn't stop automatically.

### Expected Behavior

**I expected the test to end when the last word is incorrect.**

This behavior can be confusing for users and may affect the overall user experience. It would be helpful if the test could automatically stop or provide a notification when the last word is incorrect.

### Steps To Reproduce

1. Start a typing test on Monkeytype.
2. On the last word, type an incorrect word or make an error.
3. Observe that the test doesn't stop, even though the last word is wrong.

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
Thats intended by default. You can quickly end the tests on the last character by enabling `quick end` in the settings.
