### ISSUE TITLE
Caps Lock warning stuck on firefox until another key is pressed

### ISSUE THREAD

**Issue by ben-111** [monkeytypegame/monkeytype#5853]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

benl111

### Current Behavior

I am using Firefox on Ubuntu. When the text is in focus and I press the Caps Lock key, a yellow warning appears that says "Caps Lock". When I press the Caps Lock key again, the Caps Lock is released but the warning persists until a different key is pressed.
Note that when the text is not in focus, the "Caps Lock" warning does go away when the Caps Lock is released.

### Expected Behavior

The "Caps Lock" warning shouldn't be showing when the Caps Lock is released. ~The correct behavior can be seen on Chromium browsers.~ My bad, it's the same on chromium on Linux, works correctly on windows though.

### Steps To Reproduce

1. Open the MonkeyType website on firefox.
2. Bring the text into focus.
3. Press on the Caps Lock key to bring the "Caps Lock" warning up.
4. Press the Caps Lock key again to release the Caps Lock, and observe the "Caps Lock" warning stay in place.

### Environment

- OS: Ubuntu 24.04
- Browser: Firefox
- Browser Version: 129.0.2

**Comment by avick-saha** [comment]
I'm using Ubuntu 24.04 as my OS and Firefox for browsing. I tried to reproduce the issue, but everything is working fine as expected. Could you send a screen recording for a better understanding of the issue?

**Comment by Miodec** [comment]
As far as we could tell its only a Linux Chrome issue.

**Comment by ben-111** [comment]
Sure:
[Screencast from 2024-09-06 18-38-21.webm](https://github.com/user-attachments/assets/499f3b26-c797-4a83-9464-d964d7789306)

**Comment by ben-111** [comment]
Also here it is working correctly when the text is out of focus:
[Screencast from 2024-09-06 18-44-39.webm](https://github.com/user-attachments/assets/3390f57f-b44b-45c3-aeb5-3793980a6ca2)

**Comment by ben-111** [comment]
I add some print statements in `caps-warning.ts` to try and understand the problem better:
```typescript
function update(event: JQuery.KeyDownEvent | JQuery.KeyUpEvent): void {
  console.debug(event?.originalEvent?.getModifierState?.("CapsLock"));
  capsState =
    event?.originalEvent?.getModifierState?.("CapsLock") ?? !capsState;

  console.debug(`capsState=${capsState}`);

  try {
    if (Config.capsLockWarning && capsState) {
      show();
    } else {
      hide();
    }
  } catch {}
}

$(document).on("keyup", update);

$(document).on("keydown", (event) => {
  if (isMacOs) update(event);
});
```

After pressing the CapsLock key twice this is the output:
```
DEBG Key not tracked CapsLock [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG true [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG capsState=true [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG Key not tracked CapsLock [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG true [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG capsState=true [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG Key not tracked CapsLock [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG true [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG capsState=true [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
```

So it seems to be an issue with the JQuery event maybe?

When the text is not in focus this is the output:
```
DEBG true [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG capsState=true [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG false [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
DEBG capsState=false [logger.ts:54:2](http://localhost:3000/ts/utils/logger.ts)
```

**Comment by ben-111** [comment]
I managed to boil it down to a simple case:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CapsLock state bug</title>
    <script>
      document.addEventListener("keyup", function (event) {
        console.debug("Key pressed:", event.key);
        console.debug("CapsLock state:", event.getModifierState("CapsLock"));
      });
    </script>
  </head>
  <body>
    <input type="text" />
  </body>
</html>
```

 On firefox, when the input is out of focus, it works as expected, and when the input is in focus, the bug occurs.
On chromium it's even worse - even if the input is out of focus the bug occurs, and that's the same behavior in monkeytype on chromium as well.
[caps-lock-bug-on-chromium.webm](https://github.com/user-attachments/assets/ef79de52-2d30-443b-9527-4008cba65bb3)
[caps-lock-bug-on-firefox.webm](https://github.com/user-attachments/assets/9fae32b6-f974-433f-97e3-bb12bb03d8a3)

So it doesn't appear to be an issue with monkeytype at all, and since @avick-saha says they're not experiencing any issues, I am not sure who to report the problem to.

**Comment by avick-saha** [comment]
I'm not sure what's causing the issue exactly, as I can't reproduce it. However, if it's related to jQuery (as you suggested), please try the code snippet below.
```javascript
function update(event) {
  console.debug(event?.getModifierState?.("CapsLock"));

  // Assuming `capsState` is a global or higher-scoped variable
  capsState = event?.getModifierState?.("CapsLock") ?? !capsState;

  console.debug(`capsState=${capsState}`);

  try {
    if (Config.capsLockWarning && capsState) {
      show();
    } else {
      hide();
    }
  } catch (e) {
    // Handle error silently
  }
}

// Attach event listeners using native JavaScript
document.addEventListener("keyup", update);

document.addEventListener("keydown", (event) => {
  if (isMacOs) update(event);
});

**Comment by ben-111** [comment]
No it's not a problem with JQuery - the simple case I posted is vanilla HTML+Javascript. It seems to be a problem for browsers on my Linux machine. What's odd is that you have a very similar setup to mine and you are not getting the bug. I even made an Ubuntu virtual machine freshly installed and got the same bug, so I wonder what the difference is.

**Comment by avick-saha** [comment]
I also can't understand how it's working on one machine and not on another. You've mentioned that it's not working on the freshly installed Ubuntu virtual machine...

**Comment by RushilJalal** [comment]
@ben-111 I'm using Firefox for windows. Cant seem to reproduce the issue.

**Comment by Miodec** [comment]
After a lot of testing and hair pulling i concluded Linux doesnt make sense. If youre focused on a input field `event?.originalEvent?.getModifierState?.("CapsLock")` is incorrect, but its fine when not focused on an input field. Sometimes it just straight up returns `undefined`, as if it didnt know what caps lock is. Sometimes its flipped to the actual caps lock state. Its super inconsistent. 

If somebody has the patience to work on this, feel free. I just don't know what try anymore, so im blaming Linux on this one. 

Sorry, but the caps lock warning will "stick" like that on Linux, only disappearing once you press an alpha-numeric key.
