### ISSUE TITLE
Failed to save result: Invalid request data schema

### ISSUE THREAD

**Issue by CosmicHazel** [monkeytypegame/monkeytype#5858]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

CosmicHazel

### Account config

{"theme":"8008","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"tab","punctuation":false,"numbers":false,"words":10,"time":60,"mode":"words","quoteLength":[1],"language":"english","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","keymapSize":1,"fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":0.5,"startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":0}

### Current Behavior

<img width="374" alt="image" src="https://github.com/user-attachments/assets/6ca362b7-eb4b-48db-823f-a87d0936af7a">

### Expected Behavior

No error

### Steps To Reproduce

1. Opt out of leaderboards
2. Get an accuracy around 60%

### Environment

- OS: Mac
- Browser: Chrome and Safari
- Browser Version: 128.0.6613.119 and 7.6 (19618.3.11.11.5)

**Comment by Miodec** [comment]
Should be all good now thanks

**Comment by dcousens** [comment]
I too am receiving a "Invalid request data schema" error when my results are POST'ed to https://api.monkeytype.com/results , response code is `422 Unprocessable Content`.

I am opted out of leaderboards.

**Comment by CosmicHazel** [comment]
Not sure why this was closed, still doesn't work @Miodec :(

**Comment by CosmicHazel** [comment]
<img width="369" alt="image" src="https://github.com/user-attachments/assets/713c46a9-9d52-4bd3-a641-284e6c65813a">

**Comment by CosmicHazel** [comment]
Hi @Miodec 
<img width="382" alt="image" src="https://github.com/user-attachments/assets/3bf5fe6b-3a1a-41ff-92e1-91e9d7c48745">

Still not working...

**Comment by dcousens** [comment]
@Miodec I made a copy of a request body JSON that produced this error if that helps

**Comment by Miodec** [comment]
> This error is still impacting me too.
> 
> I made a copy of a problematic request's JSON body if that helps to share



> This error is still impacting me too.
> 
> I made a copy of a problematic request's JSON body if that helps to share

Sure, post the response data.

**Comment by Miodec** [comment]
Nevermind i completely missed the leaderboard opt out part, i know what to do.
