### ISSUE TITLE
Lazy button disappears after turning it off in the Arabic language.

### ISSUE THREAD

**Issue by A7medYa7ia** [monkeytypegame/monkeytype#5864]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The lazy button is turned on by default, but after turning it off it permanently disappears.
and to turn lazy mode on again I have to do to from the settings.

### Expected Behavior

The lazy button should stay and just be active and not active.

### Steps To Reproduce

1-Go to the home page.
2- Choose Arabic language.
3-turn off lazy button.

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
esc > lazy mode > on
