### ISSUE TITLE
Tab to restart test is not working in code assembly. 

### ISSUE THREAD

**Issue by dhruvdabhi101** [monkeytypegame/monkeytype#5885]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

ddhruv101

### Account config

{"theme":"dino","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":true,"customThemeColors":["#101010","#ffc799","#ffc799","#7e7e7e","#1c1c1c","#ffffff","#76eecd","#ff8080","#ff8080","#ff8080"],"favThemes":[],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":10,"time":15,"mode":"quote","quoteLength":[1],"language":"code_assembly","fontSize":2,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"off","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"dynamic","keymapLayout":"overrideSync","keymapShowTopRow":"layout","keymapSize":1,"fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":0.5,"startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":true,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":0}

### Current Behavior

When writing assembly, when pressing on tab, it was getting it as a character and not highlighting the restart test button.

### Expected Behavior

It should let me restart the test, and restart test button should be highlighted.

### Steps To Reproduce

https://github.com/user-attachments/assets/46c0bf79-3196-491d-84b7-0716f6408d5e

### Environment

- OS: MacOS Sonoma
- Browser: Firefox
- Browser Version: 130.0

**Comment by Miodec** [comment]
You say it should let you restart the test, but how do you expect to type the tab character in the quote?

**Comment by dhruvdabhi101** [comment]
> You say it should let you restart the test, but how do you expect to type the tab character in the quote?

Ohh yeah. got it. Thanks for the clarification. Sorry for dumb question. Thanks. I will close this issue. : )
