### ISSUE TITLE
Data Mismatch

### ISSUE THREAD

**Issue by avick-saha** [monkeytypegame/monkeytype#5905]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

avicksaha

### Current Behavior

I've completed 1020 tests in total, but in my Monkeytype account, different places show different numbers. In some places, it shows 1020, which is correct, while in others, it shows 1000. I noticed this strange behavior started after completing 1000 tests. It's like it's stuck at 1000.

###  Right
![r](https://github.com/user-attachments/assets/1c56388a-21e3-4e64-9bfa-6fbc3f15e55b)

### Wrong
![w](https://github.com/user-attachments/assets/5fe21559-64e2-4f5c-b54b-0f8eff58f3d8)

### Expected Behavior

It should show the same data everywhere.

### Environment

- OS: Windows 11
- Browser: Brave
- Browser Version: 1.70.117

**Comment by fehmer** [comment]
You can only access the last 1000 results. It says when you hover over the (?) next to "tests completed":
![image](https://github.com/user-attachments/assets/b1d988ab-9b9c-4f9d-9b63-a1e31ac3e648)
