### ISSUE TITLE
XP Breakdown list is not cleaned before claiming XP reward

### ISSUE THREAD

**Issue by redfp** [monkeytypegame/monkeytype#5915]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

No

### Account name

redfp

### Account config

{"theme":"milkshake","themeLight":"milkshake","themeDark":"80s_after_dark","autoSwitchTheme":true,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#000000","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"smoothCaret":"fast","quickRestart":"esc","punctuation":false,"numbers":false,"words":110,"time":60,"mode":"time","quoteLength":[1],"language":"english","fontSize":2,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"outline","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"below","timerStyle":"off","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"black","timerOpacity":"0.25","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","keymapShowTopRow":"layout","keymapSize":1,"fontFamily":"Fira_Code","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":1,"startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":105,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":80}

### Current Behavior

After recent update, I noticed that XP Breakdown list is not cleared after completing the test and claiming the reward from notification area later. After getting some suspictions yesterday I recorded myself doing similar routine and was able to confirm it. Here are some screenshots:

Collected xp after completing the test (the reward from yesterday's daily leaderboard still not claimed):
![Screenshot from 2024-09-24 17-54-45](https://github.com/user-attachments/assets/3fb802e6-de34-4ec1-b920-76151058ed47)

Collected xp after claiming the reward:
![Screenshot from 2024-09-24 17-44-45](https://github.com/user-attachments/assets/b26192ee-4a7b-4d8b-a232-9678863e66d5)

(It might be worth mentioning that I didn't actually clean my cache; I haven't thought about it when recording this bug, and obviously I can't just give myself more xp gifts to replicate it.)

### Expected Behavior

The XP Breakdown list on the latter screenshot should be empty. Just `+{total_xp}`. Or at least show real incomplete results (I did some extra typing after the test and before claiming reward), not just duplicating previous ones.

### Steps To Reproduce

1. Complete a typing test and get on daily leaderboard.
2. Wait a day.
3. Complete a typing test.
4. [?] Complete another typing test.
5. [?] Do some incomplete tests.
6. Claim the reward for previous day's leaderboard.

I'm not really sure about steps marked with [?], but that's just how I did it.

### Environment

- OS: Linux
- Browser: Chromium
- Browser Version: 128.0.6613.113 (Official Build, ungoogled-chromium) (64-bit)

### Anything else?

It's hard to replicate this on main website. I also went through the diff of the pull request which introduced this behaviour, but couldn't find the culprit, maybe just wasn't looking hard enough.

Again, it didn't cross my mind to clear the browser cache. I will do it the next time I'll get the chance, and will update this issue accordingly.

**Comment by Miodec** [comment]
Just tested it locally and it doesnt happen. I did push a hotfix right after the last version so it might have been already fixed. If it happens again, feel free to let me know and reopen this issue.
