### ISSUE TITLE
Zero-width spaces (ZWSP) in "custom texts" are not preserved and are omitted

### ISSUE THREAD

**Issue by sepsol** [monkeytypegame/monkeytype#5919]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

sepsol

### Current Behavior

When trying to add `custom text`, all the [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) characters are converted to regular space upon saving the text. So a word like "می‌شود" would turn to "میشود" which is undesired.

### Expected Behavior

When something like "می‌شود" is typed for `custom text`, it should stay the same and not change upon save. 

Also, the default examples for Persian in the app could implement the ZWSP character. Currently they replace it with regular space which makes this app not a good place to practice typing in Persian.

### Steps To Reproduce

1. Add a new `custom text`.
2. Copy and paste the text "می‌شود" there.
3. Save your custom text.
4. Now start the practice with that text.

### Environment

- OS: Windows 11
- Browser: Microsoft Edge
- Browser Version: 128.0.2739.67 (Official build) (64-bit)

### Anything else?

| # | Spacing Character | Persian Text |
|--------|--------|--------|
| 1 | None | میشود |
| 2 | Zero-Width Space (ZWSP) | می‌شود |
| 3 | Regular Space | می شود |

<details>
<summary>Why is having ZWSP character important?</summary>
<br>

In Persian (Farsi) typing the ZWSP character is pretty common and having or omitting it can change the meaning of a word in sentence. For example:

| # | Persian Text | English Translation |
|--------|--------|--------|
| 1 | من **خاله مریم** را دیدم | I saw Maryam's aunt. |
| 2 | من **خاله‌مریم** را دیدم | I saw Aunt Maryam. | 

_If there were no ZWSPs the bolded section would look like this:_ **خالهمریم**

</details>

**Comment by Miodec** [comment]
Im almost sure that with the current input handling approach keeping zero width characters will become an issue. I can try to add a setting to the custom text modal to see if its behaving correctly..

https://monkey-type--preview-hri4hjak.web.app (expires in 2 hours)

Go here and in the custom text modal be sure to disable "remove zero-width characters". Let me know how it goes.

**Comment by sepsol** [comment]
@Miodec sorry I was away for a while, could you send me the link again?

**Comment by Miodec** [comment]
> @Miodec sorry I was away for a while, could you send me the link again?

https://monkey-type--preview-xb56jyx1.web.app

**Comment by sepsol** [comment]
@Miodec Yep, it worked as intended, thanks! I didn't test it extensively though.
