### ISSUE TITLE
Languages should have an uppercase letter

### ISSUE THREAD

**Issue by Me24Jeff** [monkeytypegame/monkeytype#5939]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

Right now it says english instead of English (not only for English but for every language)
<img width="529" alt="Screenshot 2024-10-03 at 22 28 41" src="https://github.com/user-attachments/assets/360d0937-55db-45f0-888e-a743178b2d59">
<img width="152" alt="Screenshot 2024-10-03 at 22 31 08" src="https://github.com/user-attachments/assets/9e29478d-23e6-4d3e-885b-97065ef6a282">

### Expected Behavior

It should say English, French, German, etc.

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by janardannn** [comment]
can i attempt?

**Comment by Miodec** [comment]
This is a stylistic choice, not a bug.
