### ISSUE TITLE
Error when trying to emulate some layouts

### ISSUE THREAD

**Issue by snowskwirl** [monkeytypegame/monkeytype#5948]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

snowskwirl

### Current Behavior

Error appears when trying to emulate some layouts. It seems to have something to do with dashes/special characters in the name. 

Layouts affected: 3l, saiga-e, seht-drai.

![Screenshot (825)](https://github.com/user-attachments/assets/ae987dc2-1ade-4774-9938-2b4bc3b90c92)

### Expected Behavior

Expected layout to be emulated just like the other layouts.

### Steps To Reproduce

1. Go to settings.
2. Scroll down to "layout emulator".
3. Attempt to select one of the layouts mentioned above.
4. Error will appear saying "Invalid value for layout. Please try to change this setting again."

### Environment

- OS: Windows 11
- Browser: Edge
- Browser Version: 129.0.2792.79

**Comment by m4dd0c** [comment]
It seems like hyphens (`-`) are not allowed as layout emulator values.
Layout emulator can only have alphanumeric values (`a-z` `A-Z` `0-9`) and underscores (`_`)

**Comment by sarthaknimbalkar** [comment]
Heyy,
I fixed this issue.
Let me open a PR. Please check it out.
