### ISSUE TITLE
move firebase auth domain from monkey-type.firebaseapp.com to auth.monkeytype.com

### ISSUE THREAD

**Issue by winstonDeGreef** [monkeytypegame/monkeytype#5988]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

n/a

### Account config

n/a

### Current Behavior

If someone uses the github or google sign in buttons on the auth page, they would be surprised to see they are actually logging into https://monkey-type.firebaseapp.com
![image](https://github.com/user-attachments/assets/57234266-edd8-48ab-99d2-a25c05668908)

### Expected Behavior

the auth domain should be hosted on monkeytype.com or a subdomain.

### Steps To Reproduce

try to log in with google or github

### Environment

n/a

### Anything else?

Steps to change the authdomain:
1. Add https://auth.monkeytype.com/__/auth/handler as a redirect url in google and github config. For google this is in google cloud console under api & services > credentials > OAuth 2.0 Client IDs > Web client (auto created by Google Service). 
2. Setup firebase hosting for auth.monkeytype.com
3. modify firebaseConfig to include `authDomain: https://auth.monkeytype.com`
4. (optional) make a simple index.html and 404 page for firebase hsoting on auth.monkeytype.com explaining its purpose so that users don't see this when navigating to auth.monkeytype.com 
![image](https://github.com/user-attachments/assets/59dd06ad-5ad4-4883-9772-1996aef087e0)

**Comment by Miodec** [comment]
Should be setup now, thanks.

**Comment by winstonDeGreef** [comment]
![image](https://github.com/user-attachments/assets/fa8c9f8b-3e90-402a-8d22-a8ec8ad112a1)
![image](https://github.com/user-attachments/assets/81be8dfa-acb3-4e6c-8450-0b5bf00cd631)
![image](https://github.com/user-attachments/assets/a2a55f9a-ff14-45c4-a6c9-69225462674a)

The new redirect uri has to be added to google and github config.

 > Add https://auth.monkeytype.com/__/auth/handler as a redirect url in google and github config. For google this is in google cloud console under api & services > credentials > OAuth 2.0 Client IDs > Web client (auto created by Google Service).

**Comment by winstonDeGreef** [comment]
Tried it again, google oath did work. Github oath still gave me that error.

**Comment by MaxSchuchart** [comment]
I am still getting this issue. I opened a new issue: https://github.com/monkeytypegame/monkeytype/issues/5994 (I was unaware of this one as it was closed). The issue I posted does not mention Google as it looks to be solved at present though I did not test it.
