### ISSUE TITLE
GitHub Authentication Is Not Working Properly

### ISSUE THREAD

**Issue by MaxSchuchart** [monkeytypegame/monkeytype#5994]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

MaxSchuchart

or maybe: VenturingSloth

### Current Behavior

# I get this error when trying to login through the GitHub authentication.
 The response from GitHub seems to imply that something is misconfigured with MonkeyType. I have tried on both FireFox and Safari and get the same result. I have tried with fresh instances of FireFox.

## here is the message received as text: 
The redirect_uri is not associated with this application.

The application might be misconfigured or could be trying to redirect you to a website you weren't expecting.

<img width="501" alt="image" src="https://github.com/user-attachments/assets/91eef4fe-274a-48b0-bfdc-38315f72b0a2">

### Expected Behavior

Normally sign in goes smoothly and the pop-up closes and I am logged in on MonkeyType.

### Steps To Reproduce

1. Go to [monkeytype.com/login](https://monkeytype.com/login)
2. Click on the GitHub OctoCat logo under ```login``` to Sign in with GitHub
3. Attempt to Authenticate through the pop-up window

<img width="413" alt="image" src="https://github.com/user-attachments/assets/b2a76a46-878d-4d98-8b03-df2fbc0e0b95">

### Environment

- OS: MacOS Sequoia 15.1
- Browser: FireFox / Safari
- Browser Version: FireFox: 131.0.3 (aarch64) Safari:  Version 18.1 (20619.2.8.11.10)

#### Is likely related to this: https://github.com/monkeytypegame/monkeytype/issues/5988 possibly prematurely closed issue.

**Comment by davidsanchez222** [comment]
I'm getting this right now as well.

**Comment by SoberMike** [comment]
Good day.
I can confirm the existence of this bug today too.

**Comment by Miodec** [comment]
Ah i know what i did, can you guys try now?

**Comment by SoberMike** [comment]
> Ah i know what i did, can you guys try now?

I've tried and now it works just fine. Thanks.

**Comment by dharmik2319** [comment]
@Miodec It still doesn't work for me on Firefox on Linux. The pop-up window is just blank. This happens both for Google and Github
