### ISSUE TITLE
In settings page in behavior section in blind mode the "on" text is not showing

### ISSUE THREAD

**Issue by Arghya-UIT** [monkeytypegame/monkeytype#6005]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The "on" text is not present

### Expected Behavior

The "on" text should present

### Steps To Reproduce

![Screenshot from 2024-11-04 12-02-12](https://github.com/user-attachments/assets/411712f4-313a-43fd-b5fa-1e6db23406fe)

### Environment

- OS: Ubuntu 24
- Browser: Edge & Firefox
- Browser Version:

**Comment by Miodec** [comment]
Duplicate issue, not a bug (just a little joke, the button is blind). Please use the search function next time.
