### ISSUE TITLE
Missing text(label) on a button!

### ISSUE THREAD

**Issue by Narendra-Mahara** [monkeytypegame/monkeytype#6008]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

narendra-mahara

### Current Behavior

A button on the section "blind mode" under setting is without text or label.

### Expected Behavior

This button have to be labeled.

### Steps To Reproduce

1. Go to "settings".
2. Scroll down and find "blind mode" section.
3. On the button, one of two is labeled but the second one is not labeled.

### Environment

- OS: Windows 11
- Browser: Google Chrome
- Browser Version: Version 130.0.6723.92 (Official Build) (64-bit)

### Anything else?

![Screenshot202411200156](https://github.com/user-attachments/assets/12a02d8e-13e5-4e62-b3a3-94b5df8a29c0)

**Comment by Miodec** [comment]
Not a bug. Please use the search function before posting.
