### ISSUE TITLE
Accuracy tooltip goes out of bounds when window isn't in fullscreen

### ISSUE THREAD

**Issue by schnow265** [monkeytypegame/monkeytype#6016]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

The box goes outside of the Browser Window

### Expected Behavior

The box doesn't go outside of the browser window

### Steps To Reproduce

1. Resize Window to not be full screen
2. complete any test
3. hover over the accuracy percentage

### Environment

- OS: Windows 11
- Browser: Mozilla Firefox
- Browser Version: 132.0.1 (64-bit)

### Anything else?

Reference: 

![image](https://github.com/user-attachments/assets/0a419110-2e48-4e1f-bffa-f1c46266eec3)

**Comment by rahulr-96** [comment]
balloon.css [issue](https://github.com/kazzkiq/balloon.css/issues/153)

**Comment by Miodec** [comment]
Fixed with a workaround, will be deployed later.
