### ISSUE TITLE
Bug: There is no cross/"X" button on the leaderboard page 

### ISSUE THREAD

**Issue by Anika-Aktar** [monkeytypegame/monkeytype#6030]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

anika_12

### Current Behavior

As the leaderboard doesn't have any cross button  i often get confused how to get out of the page! The related screenshot is given below:
![Screenshot (168)](https://github.com/user-attachments/assets/87681f4e-6092-4e9f-a72f-cd4a42158cf1)

### Expected Behavior

There should be a 'X' or cross to close the leaderboard and go back to where i was.
![expectedleaderboard](https://github.com/user-attachments/assets/d84f48a7-0e78-4834-bdbc-897956e094ab)

### Steps To Reproduce

1. Go to the leaderboard icon.
2. Click on it.
3. Observe the upper right side of the page or overall the page.
4. You will see there is no cross or 'X' to get out of the leaderboard.

### Environment

- OS: Windows 10 Pro N
- Browser: Chrome
- Browser Version:  130.0.6723.117 (Official Build) (64-bit)

**Comment by dertan1170** [comment]
The absence of a close ("X") button on the leaderboard panel is likely an intentional part of Monkeytype's minimalistic design. To exit the leaderboard, users can either press the ESC key or click outside the panel (highlighted in red).
![leaderboard](https://github.com/user-attachments/assets/57824458-2110-4f4a-9281-da9e21cc0121)

**Comment by Miodec** [comment]
As dertan mentioned, this is intentional.
