### ISSUE TITLE
Leaderboard ranking updates really slow 

### ISSUE THREAD

**Issue by yashudkl** [monkeytypegame/monkeytype#6108]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

yashudkl

### Current Behavior

leaderboard doesn't get updated sometimes 

### Expected Behavior

quick update for leaderboard

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by Miodec** [comment]
Leaderboards only update every 15 minutes to reduce load on the database. This is very unlikely to change.
