### ISSUE TITLE
Restarting Test Generates New Test Instead of Practice Words

### ISSUE THREAD

**Issue by saisab29** [monkeytypegame/monkeytype#6111]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

saisab

### Current Behavior

When completing a test and clicking on the "Practice Words" button, the expected behavior is to practice the specific words from the completed test. However, if the user decides to restart the test in the middle of practicing these words, the application generates a completely new test instead of resuming the practice session.

### Expected Behavior

Clicking "Restart Test" during a practice words session should: Resume the practice session for the same set of words.

### Steps To Reproduce

1. Complete a test.
2. Click the "Practice Words" button.
3. In the middle of the practice session, click on the "Restart Test" button.
4. Observe that a new test is generated instead of continuing to focus on the practice words.

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by KunalNasa** [comment]
Upon clicking the restart button, a toast message appears on the screen indicating a “reverting to previous settings.” Therefore, I believe this action was not made in error and should not be considered a bug. Instead, it would be more appropriate to label it as an improvement.

**Comment by m4dd0c** [comment]
I can put an additional button to restart this test, but I wonder if @Miodec approves it.

**Comment by Miodec** [comment]
This is by design. Restart test action (from clicking a button or using the keyboard shortcut) should always produce the same result - generating a fresh test.

If you want to repeat the generated test "practice words" test you need to complete it and use the repeat test button.
