### ISSUE TITLE
Min accuracy setting takes 1 second to actual fail the test

### ISSUE THREAD

**Issue by nskobelevs** [monkeytypegame/monkeytype#6125]
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

nskobelevs

### Account config

{
  "theme": "serika_dark",
  "themeLight": "serika",
  "themeDark": "serika_dark",
  "autoSwitchTheme": false,
  "customTheme": false,
  "customThemeColors": [
    "#323437",
    "#e2b714",
    "#e2b714",
    "#646669",
    "#2c2e31",
    "#d1d0c5",
    "#ca4754",
    "#7e2a33",
    "#ca4754",
    "#7e2a33"
  ],
  "favThemes": [],
  "showKeyTips": true,
  "smoothCaret": "medium",
  "codeUnindentOnBackspace": false,
  "quickRestart": "tab",
  "punctuation": false,
  "numbers": false,
  "words": 100,
  "time": 30,
  "mode": "words",
  "quoteLength": [2],
  "language": "english_5k",
  "fontSize": 2,
  "freedomMode": false,
  "difficulty": "normal",
  "blindMode": false,
  "quickEnd": true,
  "caretStyle": "default",
  "paceCaretStyle": "default",
  "flipTestColors": false,
  "layout": "default",
  "funbox": "none",
  "confidenceMode": "off",
  "indicateTypos": "replace",
  "timerStyle": "bar",
  "liveSpeedStyle": "off",
  "liveAccStyle": "mini",
  "liveBurstStyle": "off",
  "colorfulMode": false,
  "randomTheme": "off",
  "timerColor": "main",
  "timerOpacity": "1",
  "stopOnError": "word",
  "showAllLines": true,
  "keymapMode": "off",
  "keymapStyle": "staggered",
  "keymapLegendStyle": "lowercase",
  "keymapLayout": "overrideSync",
  "keymapShowTopRow": "layout",
  "keymapSize": 1,
  "fontFamily": "Cascadia_Mono",
  "smoothLineScroll": true,
  "alwaysShowDecimalPlaces": true,
  "alwaysShowWordsHistory": false,
  "singleListCommandLine": "manual",
  "capsLockWarning": true,
  "playSoundOnError": "off",
  "playSoundOnClick": "4",
  "soundVolume": 0.5,
  "startGraphsAtZero": true,
  "showOutOfFocusWarning": true,
  "paceCaret": "off",
  "paceCaretCustomSpeed": 100,
  "repeatedPace": false,
  "accountChart": ["on", "on", "on", "off"],
  "minWpm": "off",
  "minWpmCustomSpeed": 100,
  "highlightMode": "letter",
  "typingSpeedUnit": "wpm",
  "ads": "result",
  "hideExtraLetters": false,
  "strictSpace": false,
  "minAcc": "custom",
  "minAccCustom": 95,
  "monkey": false,
  "repeatQuotes": "off",
  "oppositeShiftMode": "keymap",
  "customBackground": "",
  "customBackgroundSize": "cover",
  "customBackgroundFilter": [0, 1, 1, 1],
  "customLayoutfluid": "qwerty#dvorak#colemak",
  "monkeyPowerLevel": "off",
  "minBurst": "off",
  "minBurstCustomSpeed": 100,
  "burstHeatmap": true,
  "britishEnglish": true,
  "lazyMode": false,
  "showAverage": "off",
  "tapeMode": "off",
  "maxLineWidth": 90
}

### Current Behavior

When a test fails due to min accuracy not being met (might affect other automatic failure settings) it takes 1 full second after the character is typed for the test to be marked as failed.

I am assuming this is not intended behaviour as it makes it feel unresponsive and can be quite jarring in the cases where you make a mistake only for the test to fail 1 second later when you're mid typing the next word.

### Expected Behavior

The test should fail instantly without a delay

### Steps To Reproduce

1. Enable "custom" min accuracy
2. Start test
3. Type incorrect letter
4. Wait 1 second for it to actually mark the test as failed

### Environment

- OS: MacOS 15.0.1
- Browser: Safari
- Browser Version: 18.0.1 (20619.1.26.31.7)

### Anything else?

Sample recording
https://github.com/user-attachments/assets/ffb9f761-977c-439c-b930-2e99bf052f3c

**Comment by Miodec** [comment]
Intended. Check runs on the timer step, and gives you some buffer to recover.

**Comment by nskobelevs** [comment]
Hmm interesting, so this is working as expected? The 1 second buffer to recover _is_ nice, I guess it's just hard to notice when it actually becomes beneficial.

Could there still be some modifications to fail instantly in cases where recovery is deemed not possible / not likely? (e.g. where even if you fix a mistake your accuracy will still be below the threshold or if you keep typing instead of fixing it)
Or even just an option for the check to be done on the input level and not aligned with the timer.

Personally for me the delay feels incredibly distracting and keeps throwing me off _a lot_ when trying to use min accuracy since you get that false sense of safety after a mistake so you keep going just to then get the a delayed gut punch of the failed test.

**Comment by Miodec** [comment]
Yes, its working as intended.

> Could there still be some modifications to fail instantly in cases where recovery is deemed not possible / not likely? (e.g. where even if you fix a mistake your accuracy will still be below the threshold or if you keep typing instead of fixing it)
Or even just an option for the check to be done on the input level and not aligned with the timer.

There isnt a solid way of determining that a recovery is not likely as typing speed is variable, so this is probably not a good idea.

> Personally for me the delay feels incredibly distracting and keeps throwing me off a lot when trying to use min accuracy since you get that false sense of safety after a mistake so you keep going just to then get the a delayed gut punch of the failed test.

But not every mistake will put you below the threshold. Assuming your min acc is 90, a mistake could put you at 89 or 95, so not every mistake will put you in the 'false sense of safety'.

**Comment by nskobelevs** [comment]
> But not every mistake will put you below the threshold. Assuming your min acc is 90, a mistake could put you at 89 or 95, so not every mistake will put you in the 'false sense of safety'.

Not _every_ mistake but every mistake that actually dips below the threshold does which is what's significant here.

The feedback just feels too slow here - like you make a mistake and keep going but for the cases where it caused a dip below the threshold you don't get that feedback of "test failed" until you've already finished the word or even mid typing the next word. Like again the delay here just feels jarring because it feels like everything is fine and you're still above threshold until that delayed failure 1 second later.

In terms of the 1 second being usable for recovery - I personally haven't noticed ever recovering here (tbf doesn't mean it hasn't happened before) but 1 sec feels like a pretty short time anyways to be able to notice the mistake, backspace, and fix it so I'd be curious how often this even happens.

Would you be open to a settings option to configure whether the checks runs on the timer or after key press?

**Comment by Miodec** [comment]
> Not every mistake but every mistake that actually dips below the threshold does which is what's significant here.

Yeah, and thats why its not immediate - to let you recover.

> The feedback just feels too slow here - like you make a mistake and keep going but for the cases where it caused a dip below the threshold you don't get that feedback of "test failed" until you've already finished the word or even mid typing the next word. Like again the delay here just feels jarring because it feels like everything is fine and you're still above threshold until that delayed failure 1 second later.

I think the only time you will feel the delay is when you stare at the live accuracy stat and notice that it goes below the threshold - which i don't think is a good thing to begin with.

> Would you be open to a settings option to configure whether the checks runs on the timer or after each key press?

Probably not. I usually add settings for thats that are talked about alot, so far its just you that feels the need for this change. Adding an option for evaluating min acc on keypress vs timer seems extremely too specific. Most people won't use it.

**Comment by nskobelevs** [comment]
Yeah that's fair enough, it might be pretty niche - thanks for hearing me out at least!
